/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminProductListOut,
  AdminProductWrapperOut,
  ApiAdminProductsIndexApiAdminProductsGetParams,
  ApiErrorOut,
  BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost,
  CatalogRefreshOut,
  CreateProductPayload,
  MediaListOut,
  MediaWrapperOut,
  UpdateProductPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Admin.Products.Index
 */
export const apiAdminProductsIndexApiAdminProductsGet = (
  params?: MaybeRef<ApiAdminProductsIndexApiAdminProductsGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminProductListOut>(
    { url: `/api/admin/products`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiAdminProductsIndexApiAdminProductsGetQueryKey = (
  params?: MaybeRef<ApiAdminProductsIndexApiAdminProductsGetParams>,
) => {
  return ['api', 'admin', 'products', ...(params ? [params] : [])] as const
}

export const getApiAdminProductsIndexApiAdminProductsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminProductsIndexApiAdminProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminProductsIndexApiAdminProductsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>
  > = ({ signal }) => apiAdminProductsIndexApiAdminProductsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>,
    TError,
    TData
  >
}

export type ApiAdminProductsIndexApiAdminProductsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>
>
export type ApiAdminProductsIndexApiAdminProductsGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Index
 */

export function useApiAdminProductsIndexApiAdminProductsGet<
  TData = Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminProductsIndexApiAdminProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminProductsIndexApiAdminProductsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminProductsIndexApiAdminProductsGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Products.Store
 */
export const apiAdminProductsStoreApiAdminProductsPost = (
  createProductPayload: MaybeRef<CreateProductPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  createProductPayload = unref(createProductPayload)

  return request<AdminProductWrapperOut>(
    {
      url: `/api/admin/products`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createProductPayload,
      signal,
    },
    options,
  )
}

export const getApiAdminProductsStoreApiAdminProductsPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsStoreApiAdminProductsPost>>,
    TError,
    { data: CreateProductPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsStoreApiAdminProductsPost>>,
  TError,
  { data: CreateProductPayload },
  TContext
> => {
  const mutationKey = ['apiAdminProductsStoreApiAdminProductsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsStoreApiAdminProductsPost>>,
    { data: CreateProductPayload }
  > = (props) => {
    const { data } = props ?? {}

    return apiAdminProductsStoreApiAdminProductsPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsStoreApiAdminProductsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsStoreApiAdminProductsPost>>
>
export type ApiAdminProductsStoreApiAdminProductsPostMutationBody = CreateProductPayload
export type ApiAdminProductsStoreApiAdminProductsPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Store
 */
export const useApiAdminProductsStoreApiAdminProductsPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsStoreApiAdminProductsPost>>,
      TError,
      { data: CreateProductPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsStoreApiAdminProductsPost>>,
  TError,
  { data: CreateProductPayload },
  TContext
> => {
  const mutationOptions = getApiAdminProductsStoreApiAdminProductsPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Catalog.Refresh
 */
export const apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<CatalogRefreshOut>(
    { url: `/api/admin/products/catalog/refresh`, method: 'POST', signal },
    options,
  )
}

export const getApiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationOptions = <
  TError = ApiErrorOut | ApiErrorOut | ApiErrorOut | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
    void
  > = () => {
    return apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>
  >

export type ApiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Catalog.Refresh
 */
export const useApiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost = <
  TError = ApiErrorOut | ApiErrorOut | ApiErrorOut | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Show
 */
export const apiAdminProductsShowApiAdminProductsProductIdGet = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminProductsShowApiAdminProductsProductIdGetQueryKey = (
  productId?: MaybeRef<string>,
) => {
  return ['api', 'admin', 'products', productId] as const
}

export const getApiAdminProductsShowApiAdminProductsProductIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminProductsShowApiAdminProductsProductIdGetQueryKey(productId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>
  > = ({ signal }) =>
    apiAdminProductsShowApiAdminProductsProductIdGet(productId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(productId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>,
    TError,
    TData
  >
}

export type ApiAdminProductsShowApiAdminProductsProductIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>
>
export type ApiAdminProductsShowApiAdminProductsProductIdGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Show
 */

export function useApiAdminProductsShowApiAdminProductsProductIdGet<
  TData = Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminProductsShowApiAdminProductsProductIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminProductsShowApiAdminProductsProductIdGetQueryOptions(
    productId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Products.Update
 */
export const apiAdminProductsUpdateApiAdminProductsProductIdPatch = (
  productId: MaybeRef<string>,
  updateProductPayload: MaybeRef<UpdateProductPayload>,
  options?: SecondParameter<typeof request>,
) => {
  productId = unref(productId)
  updateProductPayload = unref(updateProductPayload)

  return request<AdminProductWrapperOut>(
    {
      url: `/api/admin/products/${productId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateProductPayload,
    },
    options,
  )
}

export const getApiAdminProductsUpdateApiAdminProductsProductIdPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsUpdateApiAdminProductsProductIdPatch>>,
    TError,
    { productId: string; data: UpdateProductPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsUpdateApiAdminProductsProductIdPatch>>,
  TError,
  { productId: string; data: UpdateProductPayload },
  TContext
> => {
  const mutationKey = ['apiAdminProductsUpdateApiAdminProductsProductIdPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsUpdateApiAdminProductsProductIdPatch>>,
    { productId: string; data: UpdateProductPayload }
  > = (props) => {
    const { productId, data } = props ?? {}

    return apiAdminProductsUpdateApiAdminProductsProductIdPatch(productId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsUpdateApiAdminProductsProductIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsUpdateApiAdminProductsProductIdPatch>>
>
export type ApiAdminProductsUpdateApiAdminProductsProductIdPatchMutationBody = UpdateProductPayload
export type ApiAdminProductsUpdateApiAdminProductsProductIdPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Update
 */
export const useApiAdminProductsUpdateApiAdminProductsProductIdPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsUpdateApiAdminProductsProductIdPatch>>,
      TError,
      { productId: string; data: UpdateProductPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsUpdateApiAdminProductsProductIdPatch>>,
  TError,
  { productId: string; data: UpdateProductPayload },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsUpdateApiAdminProductsProductIdPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Destroy
 */
export const apiAdminProductsDestroyApiAdminProductsProductIdDelete = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  productId = unref(productId)

  return request<void>({ url: `/api/admin/products/${productId}`, method: 'DELETE' }, options)
}

export const getApiAdminProductsDestroyApiAdminProductsProductIdDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsDestroyApiAdminProductsProductIdDelete>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsDestroyApiAdminProductsProductIdDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['apiAdminProductsDestroyApiAdminProductsProductIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsDestroyApiAdminProductsProductIdDelete>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return apiAdminProductsDestroyApiAdminProductsProductIdDelete(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsDestroyApiAdminProductsProductIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsDestroyApiAdminProductsProductIdDelete>>
>

export type ApiAdminProductsDestroyApiAdminProductsProductIdDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Destroy
 */
export const useApiAdminProductsDestroyApiAdminProductsProductIdDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsDestroyApiAdminProductsProductIdDelete>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsDestroyApiAdminProductsProductIdDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsDestroyApiAdminProductsProductIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Force-Destroy
 */
export const apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  productId = unref(productId)

  return request<void>({ url: `/api/admin/products/${productId}/force`, method: 'DELETE' }, options)
}

export const getApiAdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete(
      productId,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete>>
  >

export type ApiAdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Force-Destroy
 */
export const useApiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Restore
 */
export const apiAdminProductsRestoreApiAdminProductsProductIdRestorePost = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}/restore`, method: 'POST', signal },
    options,
  )
}

export const getApiAdminProductsRestoreApiAdminProductsProductIdRestorePostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsRestoreApiAdminProductsProductIdRestorePost>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsRestoreApiAdminProductsProductIdRestorePost>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['apiAdminProductsRestoreApiAdminProductsProductIdRestorePost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsRestoreApiAdminProductsProductIdRestorePost>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return apiAdminProductsRestoreApiAdminProductsProductIdRestorePost(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsRestoreApiAdminProductsProductIdRestorePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsRestoreApiAdminProductsProductIdRestorePost>>
>

export type ApiAdminProductsRestoreApiAdminProductsProductIdRestorePostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Restore
 */
export const useApiAdminProductsRestoreApiAdminProductsProductIdRestorePost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsRestoreApiAdminProductsProductIdRestorePost>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsRestoreApiAdminProductsProductIdRestorePost>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsRestoreApiAdminProductsProductIdRestorePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Publish
 */
export const apiAdminProductsPublishApiAdminProductsProductIdPublishPatch = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}/publish`, method: 'POST' },
    options,
  )
}

export const getApiAdminProductsPublishApiAdminProductsProductIdPublishPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsPublishApiAdminProductsProductIdPublishPatch>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsPublishApiAdminProductsProductIdPublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['apiAdminProductsPublishApiAdminProductsProductIdPublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsPublishApiAdminProductsProductIdPublishPatch>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return apiAdminProductsPublishApiAdminProductsProductIdPublishPatch(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsPublishApiAdminProductsProductIdPublishPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminProductsPublishApiAdminProductsProductIdPublishPatch>>
  >

export type ApiAdminProductsPublishApiAdminProductsProductIdPublishPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Publish
 */
export const useApiAdminProductsPublishApiAdminProductsProductIdPublishPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsPublishApiAdminProductsProductIdPublishPatch>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsPublishApiAdminProductsProductIdPublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsPublishApiAdminProductsProductIdPublishPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Unpublish
 */
export const apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}/unpublish`, method: 'POST' },
    options,
  )
}

export const getApiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch(
      productId,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>
  >

export type ApiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Unpublish
 */
export const useApiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Media.Store
 */
export const apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost = (
  productId: MaybeRef<string>,
  bodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost: MaybeRef<BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)
  bodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost = unref(
    bodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost,
  )
  const formData = new FormData()
  formData.append(`file`, bodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost.file)

  return request<MediaWrapperOut>(
    {
      url: `/api/admin/products/${productId}/media`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options,
  )
}

export const getApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
    TError,
    { productId: string; data: BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
  TError,
  { productId: string; data: BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
  TContext
> => {
  const mutationKey = ['apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
    { productId: string; data: BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost }
  > = (props) => {
    const { productId, data } = props ?? {}

    return apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost(
      productId,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>>
  >
export type ApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationBody =
  BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost
export type ApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Media.Store
 */
export const useApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
      TError,
      { productId: string; data: BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
  TError,
  { productId: string; data: BodyApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Products.Media.Index
 */
export const apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<MediaListOut>(
    { url: `/api/admin/products/${productId}/media`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryKey = (
  productId?: MaybeRef<string>,
) => {
  return ['api', 'admin', 'products', productId, 'media'] as const
}

export const getApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryKey(productId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>
  > = ({ signal }) =>
    apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet(productId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(productId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
    TError,
    TData
  >
}

export type ApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>
>
export type ApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Media.Index
 */

export function useApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet<
  TData = Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryOptions(
    productId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Products.Media.Destroy
 */
export const apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete = (
  productId: MaybeRef<string>,
  mediaId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  productId = unref(productId)
  mediaId = unref(mediaId)

  return request<void>(
    { url: `/api/admin/products/${productId}/media/${mediaId}`, method: 'DELETE' },
    options,
  )
}

export const getApiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationOptions =
  <
    TError =
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut,
    TContext = unknown,
  >(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
      >,
      TError,
      { productId: string; mediaId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
    >,
    TError,
    { productId: string; mediaId: string },
    TContext
  > => {
    const mutationKey = ['apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete']
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined }

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
      >,
      { productId: string; mediaId: string }
    > = (props) => {
      const { productId, mediaId } = props ?? {}

      return apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete(
        productId,
        mediaId,
        requestOptions,
      )
    }

    return { mutationFn, ...mutationOptions }
  }

export type ApiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
    >
  >

export type ApiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Products.Media.Destroy
 */
export const useApiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
      >,
      TError,
      { productId: string; mediaId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<
    ReturnType<typeof apiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
  >,
  TError,
  { productId: string; mediaId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationOptions(
      options,
    )

  return useMutation(mutationOptions, queryClient)
}
