/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType,
} from '@tanstack/vue-query'

import type { ApiErrorOut, ApiTestSeedCatalogApiTestSeedCatalogPost200 } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Test-only seeder trigger. Disabled in production.

Intentionally has no DB_TX middleware so we can run seeder inserts
in one transaction and REFRESH MATERIALIZED VIEW in a separate transaction
after the data is committed (the view query cannot see uncommitted rows).
 * @summary Api.Test.Seed.Catalog
 */
export const apiTestSeedCatalogApiTestSeedCatalogPost = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<ApiTestSeedCatalogApiTestSeedCatalogPost200>(
    { url: `/api/test/seed/catalog`, method: 'POST', signal },
    options,
  )
}

export const getApiTestSeedCatalogApiTestSeedCatalogPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['apiTestSeedCatalogApiTestSeedCatalogPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
    void
  > = () => {
    return apiTestSeedCatalogApiTestSeedCatalogPost(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiTestSeedCatalogApiTestSeedCatalogPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>
>

export type ApiTestSeedCatalogApiTestSeedCatalogPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Test.Seed.Catalog
 */
export const useApiTestSeedCatalogApiTestSeedCatalogPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getApiTestSeedCatalogApiTestSeedCatalogPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
