/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminCategoryListOut,
  AdminCategoryWrapperOut,
  ApiAdminCategoriesIndexApiAdminCategoriesGetParams,
  ApiErrorOut,
  CreateCategoryPayload,
  UpdateCategoryPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Admin.Categories.Index
 */
export const apiAdminCategoriesIndexApiAdminCategoriesGet = (
  params?: MaybeRef<ApiAdminCategoriesIndexApiAdminCategoriesGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminCategoryListOut>(
    { url: `/api/admin/categories`, method: 'GET', params, signal },
    options,
  )
}

export const getApiAdminCategoriesIndexApiAdminCategoriesGetQueryKey = (
  params?: MaybeRef<ApiAdminCategoriesIndexApiAdminCategoriesGetParams>,
) => {
  return ['api', 'admin', 'categories', params] as const
}

export const getApiAdminCategoriesIndexApiAdminCategoriesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminCategoriesIndexApiAdminCategoriesGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminCategoriesIndexApiAdminCategoriesGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>
  > = ({ signal }) => apiAdminCategoriesIndexApiAdminCategoriesGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>,
    TError,
    TData
  >
}

export type ApiAdminCategoriesIndexApiAdminCategoriesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>
>
export type ApiAdminCategoriesIndexApiAdminCategoriesGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Index
 */

export function useApiAdminCategoriesIndexApiAdminCategoriesGet<
  TData = Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminCategoriesIndexApiAdminCategoriesGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminCategoriesIndexApiAdminCategoriesGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminCategoriesIndexApiAdminCategoriesGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Categories.Store
 */
export const apiAdminCategoriesStoreApiAdminCategoriesPost = (
  createCategoryPayload: MaybeRef<CreateCategoryPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  createCategoryPayload = unref(createCategoryPayload)

  return request<AdminCategoryWrapperOut>(
    {
      url: `/api/admin/categories`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCategoryPayload,
      signal,
    },
    options,
  )
}

export const getApiAdminCategoriesStoreApiAdminCategoriesPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesStoreApiAdminCategoriesPost>>,
    TError,
    { data: CreateCategoryPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminCategoriesStoreApiAdminCategoriesPost>>,
  TError,
  { data: CreateCategoryPayload },
  TContext
> => {
  const mutationKey = ['apiAdminCategoriesStoreApiAdminCategoriesPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesStoreApiAdminCategoriesPost>>,
    { data: CreateCategoryPayload }
  > = (props) => {
    const { data } = props ?? {}

    return apiAdminCategoriesStoreApiAdminCategoriesPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminCategoriesStoreApiAdminCategoriesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminCategoriesStoreApiAdminCategoriesPost>>
>
export type ApiAdminCategoriesStoreApiAdminCategoriesPostMutationBody = CreateCategoryPayload
export type ApiAdminCategoriesStoreApiAdminCategoriesPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Store
 */
export const useApiAdminCategoriesStoreApiAdminCategoriesPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminCategoriesStoreApiAdminCategoriesPost>>,
      TError,
      { data: CreateCategoryPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesStoreApiAdminCategoriesPost>>,
  TError,
  { data: CreateCategoryPayload },
  TContext
> => {
  const mutationOptions = getApiAdminCategoriesStoreApiAdminCategoriesPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Categories.Show
 */
export const apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet = (
  categoryId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  categoryId = unref(categoryId)

  return request<AdminCategoryWrapperOut>(
    { url: `/api/admin/categories/${categoryId}`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminCategoriesShowApiAdminCategoriesCategoryIdGetQueryKey = (
  categoryId?: MaybeRef<string>,
) => {
  return ['api', 'admin', 'categories', categoryId] as const
}

export const getApiAdminCategoriesShowApiAdminCategoriesCategoryIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  categoryId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminCategoriesShowApiAdminCategoriesCategoryIdGetQueryKey(categoryId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>
  > = ({ signal }) =>
    apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet(categoryId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(categoryId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>,
    TError,
    TData
  >
}

export type ApiAdminCategoriesShowApiAdminCategoriesCategoryIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>
>
export type ApiAdminCategoriesShowApiAdminCategoriesCategoryIdGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Show
 */

export function useApiAdminCategoriesShowApiAdminCategoriesCategoryIdGet<
  TData = Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  categoryId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminCategoriesShowApiAdminCategoriesCategoryIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminCategoriesShowApiAdminCategoriesCategoryIdGetQueryOptions(
    categoryId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Categories.Update
 */
export const apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch = (
  categoryId: MaybeRef<string>,
  updateCategoryPayload: MaybeRef<UpdateCategoryPayload>,
  options?: SecondParameter<typeof request>,
) => {
  categoryId = unref(categoryId)
  updateCategoryPayload = unref(updateCategoryPayload)

  return request<AdminCategoryWrapperOut>(
    {
      url: `/api/admin/categories/${categoryId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateCategoryPayload,
    },
    options,
  )
}

export const getApiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch>>,
    TError,
    { categoryId: string; data: UpdateCategoryPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch>>,
  TError,
  { categoryId: string; data: UpdateCategoryPayload },
  TContext
> => {
  const mutationKey = ['apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch>>,
    { categoryId: string; data: UpdateCategoryPayload }
  > = (props) => {
    const { categoryId, data } = props ?? {}

    return apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch(
      categoryId,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch>>
>
export type ApiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatchMutationBody =
  UpdateCategoryPayload
export type ApiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Update
 */
export const useApiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch>>,
      TError,
      { categoryId: string; data: UpdateCategoryPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatch>>,
  TError,
  { categoryId: string; data: UpdateCategoryPayload },
  TContext
> => {
  const mutationOptions =
    getApiAdminCategoriesUpdateApiAdminCategoriesCategoryIdPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Categories.Destroy
 */
export const apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete = (
  categoryId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  categoryId = unref(categoryId)

  return request<void>({ url: `/api/admin/categories/${categoryId}`, method: 'DELETE' }, options)
}

export const getApiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete>>,
    TError,
    { categoryId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationKey = ['apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete>>,
    { categoryId: string }
  > = (props) => {
    const { categoryId } = props ?? {}

    return apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete(categoryId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete>>
>

export type ApiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Destroy
 */
export const useApiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete>>,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDelete>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminCategoriesDestroyApiAdminCategoriesCategoryIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Categories.Publish
 */
export const apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch = (
  categoryId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  categoryId = unref(categoryId)

  return request<AdminCategoryWrapperOut>(
    { url: `/api/admin/categories/${categoryId}/publish`, method: 'POST' },
    options,
  )
}

export const getApiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch>>,
    TError,
    { categoryId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationKey = ['apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch>>,
    { categoryId: string }
  > = (props) => {
    const { categoryId } = props ?? {}

    return apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch(
      categoryId,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch>>
  >

export type ApiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Publish
 */
export const useApiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch>>,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatch>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminCategoriesPublishApiAdminCategoriesCategoryIdPublishPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Categories.Unpublish
 */
export const apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch = (
  categoryId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  categoryId = unref(categoryId)

  return request<AdminCategoryWrapperOut>(
    { url: `/api/admin/categories/${categoryId}/unpublish`, method: 'POST' },
    options,
  )
}

export const getApiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatchMutationOptions =
  <
    TError =
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut,
    TContext = unknown,
  >(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch>
      >,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch>
    >,
    TError,
    { categoryId: string },
    TContext
  > => {
    const mutationKey = ['apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch']
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined }

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch>
      >,
      { categoryId: string }
    > = (props) => {
      const { categoryId } = props ?? {}

      return apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch(
        categoryId,
        requestOptions,
      )
    }

    return { mutationFn, ...mutationOptions }
  }

export type ApiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatchMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch>
    >
  >

export type ApiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Unpublish
 */
export const useApiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch>
      >,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatch>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminCategoriesUnpublishApiAdminCategoriesCategoryIdUnpublishPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Categories.Force-Destroy
 */
export const apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete = (
  categoryId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  categoryId = unref(categoryId)

  return request<void>(
    { url: `/api/admin/categories/${categoryId}/force`, method: 'DELETE' },
    options,
  )
}

export const getApiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDeleteMutationOptions =
  <
    TError =
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut,
    TContext = unknown,
  >(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete>
      >,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete>
    >,
    TError,
    { categoryId: string },
    TContext
  > => {
    const mutationKey = ['apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete']
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined }

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete>
      >,
      { categoryId: string }
    > = (props) => {
      const { categoryId } = props ?? {}

      return apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete(
        categoryId,
        requestOptions,
      )
    }

    return { mutationFn, ...mutationOptions }
  }

export type ApiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDeleteMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete>
    >
  >

export type ApiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Force-Destroy
 */
export const useApiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete>
      >,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDelete>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminCategoriesForceDestroyApiAdminCategoriesCategoryIdForceDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Categories.Restore
 */
export const apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost = (
  categoryId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  categoryId = unref(categoryId)

  return request<AdminCategoryWrapperOut>(
    { url: `/api/admin/categories/${categoryId}/restore`, method: 'POST', signal },
    options,
  )
}

export const getApiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost>>,
    TError,
    { categoryId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationKey = ['apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost>>,
    { categoryId: string }
  > = (props) => {
    const { categoryId } = props ?? {}

    return apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost(
      categoryId,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost>>
  >

export type ApiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Categories.Restore
 */
export const useApiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost>>,
      TError,
      { categoryId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePost>>,
  TError,
  { categoryId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminCategoriesRestoreApiAdminCategoriesCategoryIdRestorePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
