/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AddCartItemPayload {
  product_id: string
  /** @minimum 1 */
  quantity?: number
}
