/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminCategoryOutName } from './adminCategoryOutName.ts'
import type { AdminCategoryOutSlug } from './adminCategoryOutSlug.ts'

export interface AdminCategoryOut {
  id: string
  name: AdminCategoryOutName
  slug: AdminCategoryOutSlug
  status: string
  published_at: string | null
  parent_id: string | null
  deleted_at: string | null
}
