/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AdminCategoriesIndexApiAdminCategoriesGetTrashed =
  (typeof AdminCategoriesIndexApiAdminCategoriesGetTrashed)[keyof typeof AdminCategoriesIndexApiAdminCategoriesGetTrashed]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCategoriesIndexApiAdminCategoriesGetTrashed = {
  without: 'without',
  with: 'with',
  only: 'only',
} as const
