/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AdminCategoriesIndexApiAdminCategoriesGetTrashed =
  (typeof AdminCategoriesIndexApiAdminCategoriesGetTrashed)[keyof typeof AdminCategoriesIndexApiAdminCategoriesGetTrashed]

export const AdminCategoriesIndexApiAdminCategoriesGetTrashed = {
  without: 'without',
  with: 'with',
  only: 'only',
} as const
