/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminOrderOutShippingAddress } from './adminOrderOutShippingAddress'
import type { AdminOrderItemOut } from './adminOrderItemOut'
import type { AdminOrderOutUser } from './adminOrderOutUser'

export interface AdminOrderOut {
  id: string
  user_id: number
  status: string
  total: number
  shipping_address: AdminOrderOutShippingAddress
  created_at: string
  items: AdminOrderItemOut[]
  user?: AdminOrderOutUser
}
