/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminCategoriesIndexApiAdminCategoriesGetTrashed } from './adminCategoriesIndexApiAdminCategoriesGetTrashed'

export type AdminCategoriesIndexApiAdminCategoriesGetParams = {
  trashed?: AdminCategoriesIndexApiAdminCategoriesGetTrashed
  limit?: number
  offset?: number
}
