/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminProductOutDescription } from './adminProductOutDescription.ts'
import type { AdminProductOutName } from './adminProductOutName.ts'
import type { AdminProductOutSlug } from './adminProductOutSlug.ts'

export interface AdminProductOut {
  id: string
  name: AdminProductOutName
  slug: AdminProductOutSlug
  description: AdminProductOutDescription
  price: number
  stock_qty: number
  status: string
  real_status: string | null
  published_at: string | null
  category_id: string | null
  vendor_id: string | null
  created_at: string | null
  updated_at: string | null
  deleted_at: string | null
}
