/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminUserOutSuspendedAt } from './adminUserOutSuspendedAt'
import type { AdminUserOutDeletedAt } from './adminUserOutDeletedAt'

export interface AdminUserOut {
  id: number
  name: string
  email: string
  roles: string[]
  permissions: string[]
  suspended_at: AdminUserOutSuspendedAt
  deleted_at: AdminUserOutDeletedAt
}
