/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AdminVendorsIndexApiAdminVendorsGetTrashed =
  (typeof AdminVendorsIndexApiAdminVendorsGetTrashed)[keyof typeof AdminVendorsIndexApiAdminVendorsGetTrashed]

export const AdminVendorsIndexApiAdminVendorsGetTrashed = {
  without: 'without',
  with: 'with',
  only: 'only',
} as const
