/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminUserOut } from './adminUserOut.ts'

export interface AdminUserWrapperOut {
  data: AdminUserOut
}
