/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminOrderItemProductOut } from './adminOrderItemProductOut.ts'

export interface AdminOrderItemOut {
  id: string
  product_id: string | null
  product_name: string
  quantity: number
  unit_price: number
  subtotal: number
  product?: AdminOrderItemProductOut | null
}
