/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminProductsIndexApiAdminProductsGetTrashed } from './adminProductsIndexApiAdminProductsGetTrashed.ts'

export type AdminProductsIndexApiAdminProductsGetParams = {
  trashed?: AdminProductsIndexApiAdminProductsGetTrashed
  limit?: number
  offset?: number
}
