/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminOrderItemOut } from './adminOrderItemOut.ts'
import type { AdminOrderOutShippingAddress } from './adminOrderOutShippingAddress.ts'
import type { AdminOrderUserOut } from './adminOrderUserOut.ts'

export interface AdminOrderOut {
  id: string
  user_id: number
  status: string
  total: number
  shipping_address: AdminOrderOutShippingAddress
  created_at: string
  items: AdminOrderItemOut[]
  user?: AdminOrderUserOut | null
}
