/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminCategoryOutName } from './adminCategoryOutName'
import type { AdminCategoryOutSlug } from './adminCategoryOutSlug'
import type { AdminCategoryOutPublishedAt } from './adminCategoryOutPublishedAt'
import type { AdminCategoryOutParentId } from './adminCategoryOutParentId'
import type { AdminCategoryOutDeletedAt } from './adminCategoryOutDeletedAt'

export interface AdminCategoryOut {
  id: string
  name: AdminCategoryOutName
  slug: AdminCategoryOutSlug
  status: string
  published_at: AdminCategoryOutPublishedAt
  parent_id: AdminCategoryOutParentId
  deleted_at: AdminCategoryOutDeletedAt
}
