/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AdminProductsIndexApiAdminProductsGetTrashed =
  (typeof AdminProductsIndexApiAdminProductsGetTrashed)[keyof typeof AdminProductsIndexApiAdminProductsGetTrashed]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminProductsIndexApiAdminProductsGetTrashed = {
  without: 'without',
  with: 'with',
  only: 'only',
} as const
