/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BestSellerOutProductId } from './bestSellerOutProductId'

export interface BestSellerOut {
  product_id: BestSellerOutProductId
  name: string
  revenue: number
  units_sold: number
}
