/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BestSellerOut {
  product_id: string | null
  name: string
  revenue: number
  units_sold: number
}
