/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProductPayloadDescription } from './createProductPayloadDescription.ts'
import type { CreateProductPayloadName } from './createProductPayloadName.ts'
import type { CreateProductPayloadSlug } from './createProductPayloadSlug.ts'

export interface CreateProductPayload {
  name: CreateProductPayloadName
  slug?: CreateProductPayloadSlug
  description?: CreateProductPayloadDescription
  /** @minimum 0 */
  price: number
  /** @minimum 0 */
  stock_qty?: number
  category_id: string
  vendor_id?: string
}
