/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreateCategoryPayloadStatus =
  (typeof CreateCategoryPayloadStatus)[keyof typeof CreateCategoryPayloadStatus]

export const CreateCategoryPayloadStatus = {
  draft: 'draft',
  published: 'published',
} as const
