/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateVendorPayloadDescription } from './createVendorPayloadDescription'
import type { CreateVendorPayloadPublishedAt } from './createVendorPayloadPublishedAt'

export interface CreateVendorPayload {
  name: string
  slug: string
  description?: CreateVendorPayloadDescription
  status?: string
  published_at?: CreateVendorPayloadPublishedAt
}
