/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreateVendorPayloadStatus =
  (typeof CreateVendorPayloadStatus)[keyof typeof CreateVendorPayloadStatus]

export const CreateVendorPayloadStatus = {
  draft: 'draft',
  published: 'published',
} as const
