/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateVendorPayloadStatus } from './createVendorPayloadStatus.ts'

export interface CreateVendorPayload {
  name: string
  slug: string
  description?: string | null
  status?: CreateVendorPayloadStatus
  published_at?: string | null
}
