/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCategoryPayloadName } from './createCategoryPayloadName.ts'
import type { CreateCategoryPayloadSlug } from './createCategoryPayloadSlug.ts'

export interface CreateCategoryPayload {
  name: CreateCategoryPayloadName
  slug: CreateCategoryPayloadSlug
  parent_id?: string | null
  status?: string
  published_at?: string | null
}
