/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardRevenuePointOut } from './dashboardRevenuePointOut.ts'
import type { DashboardStatsOutStatusCounts } from './dashboardStatsOutStatusCounts.ts'

export interface DashboardStatsOut {
  total_revenue: number
  total_orders: number
  unique_customers: number
  avg_order_value: number
  status_counts: DashboardStatsOutStatusCounts
  revenue_last_7_days: DashboardRevenuePointOut[]
}
