/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * ``POST /auth/login`` body.
 */
export interface LoginRequest {
  email: string
  /**
   * @minLength 1
   * @maxLength 128
   */
  password: string
  remember?: boolean
}
