/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface MeOut {
  id: number
  name: string
  email: string
  locale: string
  theme: string
  roles: string[]
  permissions: string[]
}
