/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OrderItemOut } from './orderItemOut.ts'
import type { OrderOutShippingAddress } from './orderOutShippingAddress.ts'

export interface OrderOut {
  id: string
  user_id: number
  status: string
  total: number
  shipping_address: OrderOutShippingAddress
  created_at: string
  items: OrderItemOut[]
}
