/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCardOut } from './productCardOut'
import type { PaginationMeta } from './paginationMeta'

export interface ProductListOut {
  data: ProductCardOut[]
  pagination: PaginationMeta
}
