/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCardOut } from './productCardOut.ts'
import type { StorefrontProductImageOut } from './storefrontProductImageOut.ts'

export interface ProductDetailCardOut extends ProductCardOut {
  images: StorefrontProductImageOut[]
}
