/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * ``POST /auth/register`` body.
 */
export interface RegisterRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  email: string
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string
  /**
   * @minLength 8
   * @maxLength 128
   */
  password_confirmation: string
  locale?: string | null
}
