/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ShippingAddress {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string
  /**
   * @minLength 1
   * @maxLength 200
   */
  street: string
  /**
   * @minLength 1
   * @maxLength 120
   */
  city: string
  /**
   * @minLength 1
   * @maxLength 120
   */
  country: string
}
