/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface StorefrontProductImageOut {
  id: string
  uuid?: string | null
  collection_name: string
  name: string
  file_name: string
  mime_type?: string | null
  size: number
  disk: string
  order?: number | null
  custom_properties?: Record<string, unknown>
  url: string
  conversions?: Record<string, string>
  srcsets?: Record<string, string>
  placeholder_svg?: string
  created_at?: string | null
  updated_at?: string | null
}
