/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StorefrontProductsCatalogApiCategoriesSlugGetParams = {
  limit?: number
  cursor?: string | null
  locale?: string | null
}
