/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationEntryOutFields } from './translationEntryOutFields.ts'

export interface TranslationEntryOut {
  model: string
  id: string
  fields: TranslationEntryOutFields
}
