/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationEntryOutFields } from './translationEntryOutFields'

export interface TranslationEntryOut {
  model: string
  id: string
  fields: TranslationEntryOutFields
}
