/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateVendorPayload {
  name?: string | null
  slug?: string | null
  description?: string | null
  status?: string | null
  published_at?: string | null
}
