/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateVendorPayloadName } from './updateVendorPayloadName'
import type { UpdateVendorPayloadSlug } from './updateVendorPayloadSlug'
import type { UpdateVendorPayloadDescription } from './updateVendorPayloadDescription'
import type { UpdateVendorPayloadStatus } from './updateVendorPayloadStatus'
import type { UpdateVendorPayloadPublishedAt } from './updateVendorPayloadPublishedAt'

export interface UpdateVendorPayload {
  name?: UpdateVendorPayloadName
  slug?: UpdateVendorPayloadSlug
  description?: UpdateVendorPayloadDescription
  status?: UpdateVendorPayloadStatus
  published_at?: UpdateVendorPayloadPublishedAt
}
