/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateProductPayloadSlugAnyOf } from './updateProductPayloadSlugAnyOf'

export type UpdateProductPayloadSlug = UpdateProductPayloadSlugAnyOf | null
