/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type UpdateCategoryPayloadStatus =
  | (typeof UpdateCategoryPayloadStatus)[keyof typeof UpdateCategoryPayloadStatus]
  | null

export const UpdateCategoryPayloadStatus = {
  draft: 'draft',
  published: 'published',
} as const
