/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateProductPayloadDescription } from './updateProductPayloadDescription.ts'
import type { UpdateProductPayloadName } from './updateProductPayloadName.ts'
import type { UpdateProductPayloadSlug } from './updateProductPayloadSlug.ts'

export interface UpdateProductPayload {
  name?: UpdateProductPayloadName
  slug?: UpdateProductPayloadSlug
  description?: UpdateProductPayloadDescription
  price?: number | null
  stock_qty?: number | null
  category_id?: string | null
  vendor_id?: string | null
}
