/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type UpdateOrderStatusPayloadStatus =
  (typeof UpdateOrderStatusPayloadStatus)[keyof typeof UpdateOrderStatusPayloadStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateOrderStatusPayloadStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
} as const
