/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserResourceLocale } from './userResourceLocale'
import type { UserResourceEmailVerifiedAt } from './userResourceEmailVerifiedAt'
import type { UserResourceCreatedAt } from './userResourceCreatedAt'

/**
 * Serialised view of a ``User`` model sent to the client.

``model_config`` uses ``from_attributes=True`` so ``model_validate(user_orm_row)``
works without an explicit ``model_dump()`` call on the ORM instance.
Sensitive fields (``password``, ``remember_token``) are never declared
here — they're absent by construction.
 */
export interface UserResource {
  id: string
  name: string
  email: string
  locale?: UserResourceLocale
  email_verified_at?: UserResourceEmailVerifiedAt
  created_at?: UserResourceCreatedAt
}
