/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { ApiErrorOut, OrderListOut, OrderWrapperOut } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Account.Orders.List
 */
export const apiAccountOrdersListApiAccountOrdersGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<OrderListOut>({ url: `/api/account/orders`, method: 'GET', signal }, options)
}

export const getApiAccountOrdersListApiAccountOrdersGetQueryKey = () => {
  return ['api', 'account', 'orders'] as const
}

export const getApiAccountOrdersListApiAccountOrdersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAccountOrdersListApiAccountOrdersGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>
  > = ({ signal }) => apiAccountOrdersListApiAccountOrdersGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>,
    TError,
    TData
  >
}

export type ApiAccountOrdersListApiAccountOrdersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>
>
export type ApiAccountOrdersListApiAccountOrdersGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Account.Orders.List
 */

export function useApiAccountOrdersListApiAccountOrdersGet<
  TData = Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAccountOrdersListApiAccountOrdersGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAccountOrdersListApiAccountOrdersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Account.Orders.Show
 */
export const apiAccountOrdersShowApiAccountOrdersOrderIdGet = (
  orderId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  orderId = unref(orderId)

  return request<OrderWrapperOut>(
    { url: `/api/account/orders/${orderId}`, method: 'GET', signal },
    options,
  )
}

export const getApiAccountOrdersShowApiAccountOrdersOrderIdGetQueryKey = (
  orderId?: MaybeRef<string>,
) => {
  return ['api', 'account', 'orders', orderId] as const
}

export const getApiAccountOrdersShowApiAccountOrdersOrderIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  orderId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAccountOrdersShowApiAccountOrdersOrderIdGetQueryKey(orderId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>
  > = ({ signal }) =>
    apiAccountOrdersShowApiAccountOrdersOrderIdGet(orderId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(orderId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>,
    TError,
    TData
  >
}

export type ApiAccountOrdersShowApiAccountOrdersOrderIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>
>
export type ApiAccountOrdersShowApiAccountOrdersOrderIdGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Account.Orders.Show
 */

export function useApiAccountOrdersShowApiAccountOrdersOrderIdGet<
  TData = Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  orderId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAccountOrdersShowApiAccountOrdersOrderIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAccountOrdersShowApiAccountOrdersOrderIdGetQueryOptions(
    orderId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
