/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AddCartItemPayload,
  CartItemsDestroyApiCartItemsItemIdDeleteParams,
  CartItemsStoreApiCartItemsPostParams,
  CartItemsUpdateApiCartItemsItemIdPatchParams,
  CartShowApiCartGetParams,
  CartWrapperOut,
  HTTPValidationError,
  UpdateCartItemPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Cart.Show
 */
export const cartShowApiCartGet = (
  params?: MaybeRef<CartShowApiCartGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<CartWrapperOut>(
    { url: `/api/cart`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getCartShowApiCartGetQueryKey = (params?: MaybeRef<CartShowApiCartGetParams>) => {
  return ['api', 'cart', ...(params ? [params] : [])] as const
}

export const getCartShowApiCartGetQueryOptions = <
  TData = Awaited<ReturnType<typeof cartShowApiCartGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<CartShowApiCartGetParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof cartShowApiCartGet>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getCartShowApiCartGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof cartShowApiCartGet>>> = ({ signal }) =>
    cartShowApiCartGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof cartShowApiCartGet>>,
    TError,
    TData
  >
}

export type CartShowApiCartGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof cartShowApiCartGet>>
>
export type CartShowApiCartGetQueryError = HTTPValidationError

/**
 * @summary Cart.Show
 */

export function useCartShowApiCartGet<
  TData = Awaited<ReturnType<typeof cartShowApiCartGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<CartShowApiCartGetParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof cartShowApiCartGet>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCartShowApiCartGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Cart.Items.Store
 */
export const cartItemsStoreApiCartItemsPost = (
  addCartItemPayload: MaybeRef<AddCartItemPayload>,
  params?: MaybeRef<CartItemsStoreApiCartItemsPostParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  addCartItemPayload = unref(addCartItemPayload)
  params = unref(params)

  return request<CartWrapperOut>(
    {
      url: `/api/cart/items`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCartItemPayload,
      params: unref(params),
      signal,
    },
    options,
  )
}

export const getCartItemsStoreApiCartItemsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cartItemsStoreApiCartItemsPost>>,
    TError,
    { data: AddCartItemPayload; params?: CartItemsStoreApiCartItemsPostParams },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cartItemsStoreApiCartItemsPost>>,
  TError,
  { data: AddCartItemPayload; params?: CartItemsStoreApiCartItemsPostParams },
  TContext
> => {
  const mutationKey = ['cartItemsStoreApiCartItemsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cartItemsStoreApiCartItemsPost>>,
    { data: AddCartItemPayload; params?: CartItemsStoreApiCartItemsPostParams }
  > = (props) => {
    const { data, params } = props ?? {}

    return cartItemsStoreApiCartItemsPost(data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CartItemsStoreApiCartItemsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof cartItemsStoreApiCartItemsPost>>
>
export type CartItemsStoreApiCartItemsPostMutationBody = AddCartItemPayload
export type CartItemsStoreApiCartItemsPostMutationError = HTTPValidationError

/**
 * @summary Cart.Items.Store
 */
export const useCartItemsStoreApiCartItemsPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cartItemsStoreApiCartItemsPost>>,
      TError,
      { data: AddCartItemPayload; params?: CartItemsStoreApiCartItemsPostParams },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof cartItemsStoreApiCartItemsPost>>,
  TError,
  { data: AddCartItemPayload; params?: CartItemsStoreApiCartItemsPostParams },
  TContext
> => {
  const mutationOptions = getCartItemsStoreApiCartItemsPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Cart.Items.Update
 */
export const cartItemsUpdateApiCartItemsItemIdPatch = (
  itemId: MaybeRef<string>,
  updateCartItemPayload: MaybeRef<UpdateCartItemPayload>,
  params?: MaybeRef<CartItemsUpdateApiCartItemsItemIdPatchParams>,
  options?: SecondParameter<typeof request>,
) => {
  itemId = unref(itemId)
  updateCartItemPayload = unref(updateCartItemPayload)
  params = unref(params)

  return request<CartWrapperOut>(
    {
      url: `/api/cart/items/${itemId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateCartItemPayload,
      params: unref(params),
    },
    options,
  )
}

export const getCartItemsUpdateApiCartItemsItemIdPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cartItemsUpdateApiCartItemsItemIdPatch>>,
    TError,
    {
      itemId: string
      data: UpdateCartItemPayload
      params?: CartItemsUpdateApiCartItemsItemIdPatchParams
    },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cartItemsUpdateApiCartItemsItemIdPatch>>,
  TError,
  {
    itemId: string
    data: UpdateCartItemPayload
    params?: CartItemsUpdateApiCartItemsItemIdPatchParams
  },
  TContext
> => {
  const mutationKey = ['cartItemsUpdateApiCartItemsItemIdPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cartItemsUpdateApiCartItemsItemIdPatch>>,
    {
      itemId: string
      data: UpdateCartItemPayload
      params?: CartItemsUpdateApiCartItemsItemIdPatchParams
    }
  > = (props) => {
    const { itemId, data, params } = props ?? {}

    return cartItemsUpdateApiCartItemsItemIdPatch(itemId, data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CartItemsUpdateApiCartItemsItemIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof cartItemsUpdateApiCartItemsItemIdPatch>>
>
export type CartItemsUpdateApiCartItemsItemIdPatchMutationBody = UpdateCartItemPayload
export type CartItemsUpdateApiCartItemsItemIdPatchMutationError = HTTPValidationError

/**
 * @summary Cart.Items.Update
 */
export const useCartItemsUpdateApiCartItemsItemIdPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cartItemsUpdateApiCartItemsItemIdPatch>>,
      TError,
      {
        itemId: string
        data: UpdateCartItemPayload
        params?: CartItemsUpdateApiCartItemsItemIdPatchParams
      },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof cartItemsUpdateApiCartItemsItemIdPatch>>,
  TError,
  {
    itemId: string
    data: UpdateCartItemPayload
    params?: CartItemsUpdateApiCartItemsItemIdPatchParams
  },
  TContext
> => {
  const mutationOptions = getCartItemsUpdateApiCartItemsItemIdPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Cart.Items.Destroy
 */
export const cartItemsDestroyApiCartItemsItemIdDelete = (
  itemId: MaybeRef<string>,
  params?: MaybeRef<CartItemsDestroyApiCartItemsItemIdDeleteParams>,
  options?: SecondParameter<typeof request>,
) => {
  itemId = unref(itemId)
  params = unref(params)

  return request<CartWrapperOut>(
    { url: `/api/cart/items/${itemId}`, method: 'DELETE', params: unref(params) },
    options,
  )
}

export const getCartItemsDestroyApiCartItemsItemIdDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cartItemsDestroyApiCartItemsItemIdDelete>>,
    TError,
    { itemId: string; params?: CartItemsDestroyApiCartItemsItemIdDeleteParams },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cartItemsDestroyApiCartItemsItemIdDelete>>,
  TError,
  { itemId: string; params?: CartItemsDestroyApiCartItemsItemIdDeleteParams },
  TContext
> => {
  const mutationKey = ['cartItemsDestroyApiCartItemsItemIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cartItemsDestroyApiCartItemsItemIdDelete>>,
    { itemId: string; params?: CartItemsDestroyApiCartItemsItemIdDeleteParams }
  > = (props) => {
    const { itemId, params } = props ?? {}

    return cartItemsDestroyApiCartItemsItemIdDelete(itemId, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CartItemsDestroyApiCartItemsItemIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof cartItemsDestroyApiCartItemsItemIdDelete>>
>

export type CartItemsDestroyApiCartItemsItemIdDeleteMutationError = HTTPValidationError

/**
 * @summary Cart.Items.Destroy
 */
export const useCartItemsDestroyApiCartItemsItemIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cartItemsDestroyApiCartItemsItemIdDelete>>,
      TError,
      { itemId: string; params?: CartItemsDestroyApiCartItemsItemIdDeleteParams },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof cartItemsDestroyApiCartItemsItemIdDelete>>,
  TError,
  { itemId: string; params?: CartItemsDestroyApiCartItemsItemIdDeleteParams },
  TContext
> => {
  const mutationOptions = getCartItemsDestroyApiCartItemsItemIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
