/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AddCartItemPayload,
  ApiCartItemsAddApiCartItemsPostParams,
  ApiCartItemsRemoveApiCartItemsItemIdDeleteParams,
  ApiCartItemsUpdateApiCartItemsItemIdPatchParams,
  ApiCartShowApiCartGetParams,
  ApiErrorOut,
  CartWrapperOut,
  UpdateCartItemPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Cart.Show
 */
export const apiCartShowApiCartGet = (
  params?: MaybeRef<ApiCartShowApiCartGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<CartWrapperOut>(
    { url: `/api/cart`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiCartShowApiCartGetQueryKey = (
  params?: MaybeRef<ApiCartShowApiCartGetParams>,
) => {
  return ['api', 'cart', ...(params ? [params] : [])] as const
}

export const getApiCartShowApiCartGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiCartShowApiCartGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiCartShowApiCartGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiCartShowApiCartGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiCartShowApiCartGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiCartShowApiCartGet>>> = ({ signal }) =>
    apiCartShowApiCartGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiCartShowApiCartGet>>,
    TError,
    TData
  >
}

export type ApiCartShowApiCartGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiCartShowApiCartGet>>
>
export type ApiCartShowApiCartGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Cart.Show
 */

export function useApiCartShowApiCartGet<
  TData = Awaited<ReturnType<typeof apiCartShowApiCartGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiCartShowApiCartGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiCartShowApiCartGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiCartShowApiCartGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Cart.Items.Add
 */
export const apiCartItemsAddApiCartItemsPost = (
  addCartItemPayload: MaybeRef<AddCartItemPayload>,
  params?: MaybeRef<ApiCartItemsAddApiCartItemsPostParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  addCartItemPayload = unref(addCartItemPayload)
  params = unref(params)

  return request<CartWrapperOut>(
    {
      url: `/api/cart/items`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCartItemPayload,
      params: unref(params),
      signal,
    },
    options,
  )
}

export const getApiCartItemsAddApiCartItemsPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCartItemsAddApiCartItemsPost>>,
    TError,
    { data: AddCartItemPayload; params?: ApiCartItemsAddApiCartItemsPostParams },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCartItemsAddApiCartItemsPost>>,
  TError,
  { data: AddCartItemPayload; params?: ApiCartItemsAddApiCartItemsPostParams },
  TContext
> => {
  const mutationKey = ['apiCartItemsAddApiCartItemsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCartItemsAddApiCartItemsPost>>,
    { data: AddCartItemPayload; params?: ApiCartItemsAddApiCartItemsPostParams }
  > = (props) => {
    const { data, params } = props ?? {}

    return apiCartItemsAddApiCartItemsPost(data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiCartItemsAddApiCartItemsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCartItemsAddApiCartItemsPost>>
>
export type ApiCartItemsAddApiCartItemsPostMutationBody = AddCartItemPayload
export type ApiCartItemsAddApiCartItemsPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Cart.Items.Add
 */
export const useApiCartItemsAddApiCartItemsPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiCartItemsAddApiCartItemsPost>>,
      TError,
      { data: AddCartItemPayload; params?: ApiCartItemsAddApiCartItemsPostParams },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiCartItemsAddApiCartItemsPost>>,
  TError,
  { data: AddCartItemPayload; params?: ApiCartItemsAddApiCartItemsPostParams },
  TContext
> => {
  const mutationOptions = getApiCartItemsAddApiCartItemsPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Cart.Items.Update
 */
export const apiCartItemsUpdateApiCartItemsItemIdPatch = (
  itemId: MaybeRef<string>,
  updateCartItemPayload: MaybeRef<UpdateCartItemPayload>,
  params?: MaybeRef<ApiCartItemsUpdateApiCartItemsItemIdPatchParams>,
  options?: SecondParameter<typeof request>,
) => {
  itemId = unref(itemId)
  updateCartItemPayload = unref(updateCartItemPayload)
  params = unref(params)

  return request<CartWrapperOut>(
    {
      url: `/api/cart/items/${itemId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateCartItemPayload,
      params: unref(params),
    },
    options,
  )
}

export const getApiCartItemsUpdateApiCartItemsItemIdPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCartItemsUpdateApiCartItemsItemIdPatch>>,
    TError,
    {
      itemId: string
      data: UpdateCartItemPayload
      params?: ApiCartItemsUpdateApiCartItemsItemIdPatchParams
    },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCartItemsUpdateApiCartItemsItemIdPatch>>,
  TError,
  {
    itemId: string
    data: UpdateCartItemPayload
    params?: ApiCartItemsUpdateApiCartItemsItemIdPatchParams
  },
  TContext
> => {
  const mutationKey = ['apiCartItemsUpdateApiCartItemsItemIdPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCartItemsUpdateApiCartItemsItemIdPatch>>,
    {
      itemId: string
      data: UpdateCartItemPayload
      params?: ApiCartItemsUpdateApiCartItemsItemIdPatchParams
    }
  > = (props) => {
    const { itemId, data, params } = props ?? {}

    return apiCartItemsUpdateApiCartItemsItemIdPatch(itemId, data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiCartItemsUpdateApiCartItemsItemIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCartItemsUpdateApiCartItemsItemIdPatch>>
>
export type ApiCartItemsUpdateApiCartItemsItemIdPatchMutationBody = UpdateCartItemPayload
export type ApiCartItemsUpdateApiCartItemsItemIdPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Cart.Items.Update
 */
export const useApiCartItemsUpdateApiCartItemsItemIdPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiCartItemsUpdateApiCartItemsItemIdPatch>>,
      TError,
      {
        itemId: string
        data: UpdateCartItemPayload
        params?: ApiCartItemsUpdateApiCartItemsItemIdPatchParams
      },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiCartItemsUpdateApiCartItemsItemIdPatch>>,
  TError,
  {
    itemId: string
    data: UpdateCartItemPayload
    params?: ApiCartItemsUpdateApiCartItemsItemIdPatchParams
  },
  TContext
> => {
  const mutationOptions = getApiCartItemsUpdateApiCartItemsItemIdPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Cart.Items.Remove
 */
export const apiCartItemsRemoveApiCartItemsItemIdDelete = (
  itemId: MaybeRef<string>,
  params?: MaybeRef<ApiCartItemsRemoveApiCartItemsItemIdDeleteParams>,
  options?: SecondParameter<typeof request>,
) => {
  itemId = unref(itemId)
  params = unref(params)

  return request<CartWrapperOut>(
    { url: `/api/cart/items/${itemId}`, method: 'DELETE', params: unref(params) },
    options,
  )
}

export const getApiCartItemsRemoveApiCartItemsItemIdDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCartItemsRemoveApiCartItemsItemIdDelete>>,
    TError,
    { itemId: string; params?: ApiCartItemsRemoveApiCartItemsItemIdDeleteParams },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCartItemsRemoveApiCartItemsItemIdDelete>>,
  TError,
  { itemId: string; params?: ApiCartItemsRemoveApiCartItemsItemIdDeleteParams },
  TContext
> => {
  const mutationKey = ['apiCartItemsRemoveApiCartItemsItemIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCartItemsRemoveApiCartItemsItemIdDelete>>,
    { itemId: string; params?: ApiCartItemsRemoveApiCartItemsItemIdDeleteParams }
  > = (props) => {
    const { itemId, params } = props ?? {}

    return apiCartItemsRemoveApiCartItemsItemIdDelete(itemId, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiCartItemsRemoveApiCartItemsItemIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCartItemsRemoveApiCartItemsItemIdDelete>>
>

export type ApiCartItemsRemoveApiCartItemsItemIdDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Cart.Items.Remove
 */
export const useApiCartItemsRemoveApiCartItemsItemIdDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiCartItemsRemoveApiCartItemsItemIdDelete>>,
      TError,
      { itemId: string; params?: ApiCartItemsRemoveApiCartItemsItemIdDeleteParams },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiCartItemsRemoveApiCartItemsItemIdDelete>>,
  TError,
  { itemId: string; params?: ApiCartItemsRemoveApiCartItemsItemIdDeleteParams },
  TContext
> => {
  const mutationOptions = getApiCartItemsRemoveApiCartItemsItemIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
