/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { ApiErrorOut, CheckoutPayload, OrderWrapperOut } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Checkout
 */
export const apiCheckoutApiCheckoutPost = (
  checkoutPayload: MaybeRef<CheckoutPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  checkoutPayload = unref(checkoutPayload)

  return request<OrderWrapperOut>(
    {
      url: `/api/checkout`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: checkoutPayload,
      signal,
    },
    options,
  )
}

export const getApiCheckoutApiCheckoutPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiCheckoutApiCheckoutPost>>,
    TError,
    { data: CheckoutPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiCheckoutApiCheckoutPost>>,
  TError,
  { data: CheckoutPayload },
  TContext
> => {
  const mutationKey = ['apiCheckoutApiCheckoutPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiCheckoutApiCheckoutPost>>,
    { data: CheckoutPayload }
  > = (props) => {
    const { data } = props ?? {}

    return apiCheckoutApiCheckoutPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiCheckoutApiCheckoutPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiCheckoutApiCheckoutPost>>
>
export type ApiCheckoutApiCheckoutPostMutationBody = CheckoutPayload
export type ApiCheckoutApiCheckoutPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Checkout
 */
export const useApiCheckoutApiCheckoutPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiCheckoutApiCheckoutPost>>,
      TError,
      { data: CheckoutPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiCheckoutApiCheckoutPost>>,
  TError,
  { data: CheckoutPayload },
  TContext
> => {
  const mutationOptions = getApiCheckoutApiCheckoutPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
