/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { CheckoutPayload, HTTPValidationError, OrderWrapperOut } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Checkout
 */
export const checkoutApiCheckoutPost = (
  checkoutPayload: MaybeRef<CheckoutPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  checkoutPayload = unref(checkoutPayload)

  return request<OrderWrapperOut>(
    {
      url: `/api/checkout`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: checkoutPayload,
      signal,
    },
    options,
  )
}

export const getCheckoutApiCheckoutPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof checkoutApiCheckoutPost>>,
    TError,
    { data: CheckoutPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof checkoutApiCheckoutPost>>,
  TError,
  { data: CheckoutPayload },
  TContext
> => {
  const mutationKey = ['checkoutApiCheckoutPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof checkoutApiCheckoutPost>>,
    { data: CheckoutPayload }
  > = (props) => {
    const { data } = props ?? {}

    return checkoutApiCheckoutPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CheckoutApiCheckoutPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof checkoutApiCheckoutPost>>
>
export type CheckoutApiCheckoutPostMutationBody = CheckoutPayload
export type CheckoutApiCheckoutPostMutationError = HTTPValidationError

/**
 * @summary Checkout
 */
export const useCheckoutApiCheckoutPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof checkoutApiCheckoutPost>>,
      TError,
      { data: CheckoutPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof checkoutApiCheckoutPost>>,
  TError,
  { data: CheckoutPayload },
  TContext
> => {
  const mutationOptions = getCheckoutApiCheckoutPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
