/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminProductListOut,
  AdminProductWrapperOut,
  AdminProductsIndexApiAdminProductsGetParams,
  BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost,
  CatalogRefreshOut,
  CreateProductPayload,
  HTTPValidationError,
  MediaListOut,
  MediaWrapperOut,
  UpdateProductPayload,
} from '../schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Admin.Products.Index
 */
export const adminProductsIndexApiAdminProductsGet = (
  params?: MaybeRef<AdminProductsIndexApiAdminProductsGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminProductListOut>(
    { url: `/api/admin/products`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getAdminProductsIndexApiAdminProductsGetQueryKey = (
  params?: MaybeRef<AdminProductsIndexApiAdminProductsGetParams>,
) => {
  return ['api', 'admin', 'products', ...(params ? [params] : [])] as const
}

export const getAdminProductsIndexApiAdminProductsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminProductsIndexApiAdminProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminProductsIndexApiAdminProductsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>
  > = ({ signal }) => adminProductsIndexApiAdminProductsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>,
    TError,
    TData
  >
}

export type AdminProductsIndexApiAdminProductsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>
>
export type AdminProductsIndexApiAdminProductsGetQueryError = HTTPValidationError

/**
 * @summary Admin.Products.Index
 */

export function useAdminProductsIndexApiAdminProductsGet<
  TData = Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminProductsIndexApiAdminProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProductsIndexApiAdminProductsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminProductsIndexApiAdminProductsGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Products.Store
 */
export const adminProductsStoreApiAdminProductsPost = (
  createProductPayload: MaybeRef<CreateProductPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  createProductPayload = unref(createProductPayload)

  return request<AdminProductWrapperOut>(
    {
      url: `/api/admin/products`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createProductPayload,
      signal,
    },
    options,
  )
}

export const getAdminProductsStoreApiAdminProductsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsStoreApiAdminProductsPost>>,
    TError,
    { data: CreateProductPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsStoreApiAdminProductsPost>>,
  TError,
  { data: CreateProductPayload },
  TContext
> => {
  const mutationKey = ['adminProductsStoreApiAdminProductsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsStoreApiAdminProductsPost>>,
    { data: CreateProductPayload }
  > = (props) => {
    const { data } = props ?? {}

    return adminProductsStoreApiAdminProductsPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsStoreApiAdminProductsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsStoreApiAdminProductsPost>>
>
export type AdminProductsStoreApiAdminProductsPostMutationBody = CreateProductPayload
export type AdminProductsStoreApiAdminProductsPostMutationError = HTTPValidationError

/**
 * @summary Admin.Products.Store
 */
export const useAdminProductsStoreApiAdminProductsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsStoreApiAdminProductsPost>>,
      TError,
      { data: CreateProductPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsStoreApiAdminProductsPost>>,
  TError,
  { data: CreateProductPayload },
  TContext
> => {
  return useMutation(getAdminProductsStoreApiAdminProductsPostMutationOptions(options), queryClient)
}
/**
 * @summary Admin.Products.Catalog.Refresh
 */
export const adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<CatalogRefreshOut>(
    { url: `/api/admin/products/catalog/refresh`, method: 'POST', signal },
    options,
  )
}

export const getAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
    void
  > = () => {
    return adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>
  >

export type AdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationError = unknown

/**
 * @summary Admin.Products.Catalog.Refresh
 */
export const useAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsCatalogRefreshApiAdminProductsCatalogRefreshPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAdminProductsCatalogRefreshApiAdminProductsCatalogRefreshPostMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Show
 */
export const adminProductsShowApiAdminProductsProductIdGet = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}`, method: 'GET', signal },
    options,
  )
}

export const getAdminProductsShowApiAdminProductsProductIdGetQueryKey = (
  productId: MaybeRef<string>,
) => {
  return ['api', 'admin', 'products', productId] as const
}

export const getAdminProductsShowApiAdminProductsProductIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>,
  TError = HTTPValidationError,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminProductsShowApiAdminProductsProductIdGetQueryKey(productId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>
  > = ({ signal }) =>
    adminProductsShowApiAdminProductsProductIdGet(productId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => unref(productId) !== null && unref(productId) !== undefined),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>,
    TError,
    TData
  >
}

export type AdminProductsShowApiAdminProductsProductIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>
>
export type AdminProductsShowApiAdminProductsProductIdGetQueryError = HTTPValidationError

/**
 * @summary Admin.Products.Show
 */

export function useAdminProductsShowApiAdminProductsProductIdGet<
  TData = Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>,
  TError = HTTPValidationError,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProductsShowApiAdminProductsProductIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminProductsShowApiAdminProductsProductIdGetQueryOptions(
    productId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Products.Update
 */
export const adminProductsUpdateApiAdminProductsProductIdPatch = (
  productId: MaybeRef<string>,
  updateProductPayload: MaybeRef<UpdateProductPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)
  updateProductPayload = unref(updateProductPayload)

  return request<AdminProductWrapperOut>(
    {
      url: `/api/admin/products/${productId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateProductPayload,
      signal,
    },
    options,
  )
}

export const getAdminProductsUpdateApiAdminProductsProductIdPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsUpdateApiAdminProductsProductIdPatch>>,
    TError,
    { productId: string; data: UpdateProductPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsUpdateApiAdminProductsProductIdPatch>>,
  TError,
  { productId: string; data: UpdateProductPayload },
  TContext
> => {
  const mutationKey = ['adminProductsUpdateApiAdminProductsProductIdPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsUpdateApiAdminProductsProductIdPatch>>,
    { productId: string; data: UpdateProductPayload }
  > = (props) => {
    const { productId, data } = props ?? {}

    return adminProductsUpdateApiAdminProductsProductIdPatch(productId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsUpdateApiAdminProductsProductIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsUpdateApiAdminProductsProductIdPatch>>
>
export type AdminProductsUpdateApiAdminProductsProductIdPatchMutationBody = UpdateProductPayload
export type AdminProductsUpdateApiAdminProductsProductIdPatchMutationError = HTTPValidationError

/**
 * @summary Admin.Products.Update
 */
export const useAdminProductsUpdateApiAdminProductsProductIdPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsUpdateApiAdminProductsProductIdPatch>>,
      TError,
      { productId: string; data: UpdateProductPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsUpdateApiAdminProductsProductIdPatch>>,
  TError,
  { productId: string; data: UpdateProductPayload },
  TContext
> => {
  return useMutation(
    getAdminProductsUpdateApiAdminProductsProductIdPatchMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Destroy
 */
export const adminProductsDestroyApiAdminProductsProductIdDelete = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<unknown>(
    { url: `/api/admin/products/${productId}`, method: 'DELETE', signal },
    options,
  )
}

export const getAdminProductsDestroyApiAdminProductsProductIdDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsDestroyApiAdminProductsProductIdDelete>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsDestroyApiAdminProductsProductIdDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['adminProductsDestroyApiAdminProductsProductIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsDestroyApiAdminProductsProductIdDelete>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return adminProductsDestroyApiAdminProductsProductIdDelete(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsDestroyApiAdminProductsProductIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsDestroyApiAdminProductsProductIdDelete>>
>

export type AdminProductsDestroyApiAdminProductsProductIdDeleteMutationError = HTTPValidationError

/**
 * @summary Admin.Products.Destroy
 */
export const useAdminProductsDestroyApiAdminProductsProductIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsDestroyApiAdminProductsProductIdDelete>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsDestroyApiAdminProductsProductIdDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  return useMutation(
    getAdminProductsDestroyApiAdminProductsProductIdDeleteMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Force Destroy
 */
export const adminProductsForceDestroyApiAdminProductsProductIdForceDelete = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<unknown>(
    { url: `/api/admin/products/${productId}/force`, method: 'DELETE', signal },
    options,
  )
}

export const getAdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['adminProductsForceDestroyApiAdminProductsProductIdForceDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return adminProductsForceDestroyApiAdminProductsProductIdForceDelete(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof adminProductsForceDestroyApiAdminProductsProductIdForceDelete>>
  >

export type AdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationError =
  HTTPValidationError

/**
 * @summary Admin.Products.Force Destroy
 */
export const useAdminProductsForceDestroyApiAdminProductsProductIdForceDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsForceDestroyApiAdminProductsProductIdForceDelete>>,
  TError,
  { productId: string },
  TContext
> => {
  return useMutation(
    getAdminProductsForceDestroyApiAdminProductsProductIdForceDeleteMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Restore
 */
export const adminProductsRestoreApiAdminProductsProductIdRestorePost = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}/restore`, method: 'POST', signal },
    options,
  )
}

export const getAdminProductsRestoreApiAdminProductsProductIdRestorePostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsRestoreApiAdminProductsProductIdRestorePost>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsRestoreApiAdminProductsProductIdRestorePost>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['adminProductsRestoreApiAdminProductsProductIdRestorePost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsRestoreApiAdminProductsProductIdRestorePost>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return adminProductsRestoreApiAdminProductsProductIdRestorePost(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsRestoreApiAdminProductsProductIdRestorePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsRestoreApiAdminProductsProductIdRestorePost>>
>

export type AdminProductsRestoreApiAdminProductsProductIdRestorePostMutationError =
  HTTPValidationError

/**
 * @summary Admin.Products.Restore
 */
export const useAdminProductsRestoreApiAdminProductsProductIdRestorePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsRestoreApiAdminProductsProductIdRestorePost>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsRestoreApiAdminProductsProductIdRestorePost>>,
  TError,
  { productId: string },
  TContext
> => {
  return useMutation(
    getAdminProductsRestoreApiAdminProductsProductIdRestorePostMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Publish
 */
export const adminProductsPublishApiAdminProductsProductIdPublishPatch = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}/publish`, method: 'PATCH', signal },
    options,
  )
}

export const getAdminProductsPublishApiAdminProductsProductIdPublishPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsPublishApiAdminProductsProductIdPublishPatch>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsPublishApiAdminProductsProductIdPublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['adminProductsPublishApiAdminProductsProductIdPublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsPublishApiAdminProductsProductIdPublishPatch>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return adminProductsPublishApiAdminProductsProductIdPublishPatch(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsPublishApiAdminProductsProductIdPublishPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsPublishApiAdminProductsProductIdPublishPatch>>
>

export type AdminProductsPublishApiAdminProductsProductIdPublishPatchMutationError =
  HTTPValidationError

/**
 * @summary Admin.Products.Publish
 */
export const useAdminProductsPublishApiAdminProductsProductIdPublishPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsPublishApiAdminProductsProductIdPublishPatch>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsPublishApiAdminProductsProductIdPublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  return useMutation(
    getAdminProductsPublishApiAdminProductsProductIdPublishPatchMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Unpublish
 */
export const adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<AdminProductWrapperOut>(
    { url: `/api/admin/products/${productId}/unpublish`, method: 'PATCH', signal },
    options,
  )
}

export const getAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
    TError,
    { productId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  const mutationKey = ['adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
    { productId: string }
  > = (props) => {
    const { productId } = props ?? {}

    return adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch(productId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>
  >

export type AdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationError =
  HTTPValidationError

/**
 * @summary Admin.Products.Unpublish
 */
export const useAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
      TError,
      { productId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsUnpublishApiAdminProductsProductIdUnpublishPatch>>,
  TError,
  { productId: string },
  TContext
> => {
  return useMutation(
    getAdminProductsUnpublishApiAdminProductsProductIdUnpublishPatchMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Media.Index
 */
export const adminProductsMediaIndexApiAdminProductsProductIdMediaGet = (
  productId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)

  return request<MediaListOut>(
    { url: `/api/admin/products/${productId}/media`, method: 'GET', signal },
    options,
  )
}

export const getAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryKey = (
  productId: MaybeRef<string>,
) => {
  return ['api', 'admin', 'products', productId, 'media'] as const
}

export const getAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
  TError = HTTPValidationError,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryKey(productId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>
  > = ({ signal }) =>
    adminProductsMediaIndexApiAdminProductsProductIdMediaGet(productId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => unref(productId) !== null && unref(productId) !== undefined),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
    TError,
    TData
  >
}

export type AdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>
>
export type AdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryError = HTTPValidationError

/**
 * @summary Admin.Products.Media.Index
 */

export function useAdminProductsMediaIndexApiAdminProductsProductIdMediaGet<
  TData = Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
  TError = HTTPValidationError,
>(
  productId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminProductsMediaIndexApiAdminProductsProductIdMediaGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminProductsMediaIndexApiAdminProductsProductIdMediaGetQueryOptions(
    productId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Products.Media.Store
 */
export const adminProductsMediaStoreApiAdminProductsProductIdMediaPost = (
  productId: MaybeRef<string>,
  bodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost: MaybeRef<BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)
  bodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost = unref(
    bodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost,
  )
  const formData = new FormData()
  formData.append(`file`, bodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost.file)

  return request<MediaWrapperOut>(
    {
      url: `/api/admin/products/${productId}/media`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options,
  )
}

export const getAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
    TError,
    { productId: string; data: BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
  TError,
  { productId: string; data: BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
  TContext
> => {
  const mutationKey = ['adminProductsMediaStoreApiAdminProductsProductIdMediaPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
    { productId: string; data: BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost }
  > = (props) => {
    const { productId, data } = props ?? {}

    return adminProductsMediaStoreApiAdminProductsProductIdMediaPost(
      productId,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminProductsMediaStoreApiAdminProductsProductIdMediaPost>>
>
export type AdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationBody =
  BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost
export type AdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationError =
  HTTPValidationError

/**
 * @summary Admin.Products.Media.Store
 */
export const useAdminProductsMediaStoreApiAdminProductsProductIdMediaPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
      TError,
      { productId: string; data: BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsMediaStoreApiAdminProductsProductIdMediaPost>>,
  TError,
  { productId: string; data: BodyAdminProductsMediaStoreApiAdminProductsProductIdMediaPost },
  TContext
> => {
  return useMutation(
    getAdminProductsMediaStoreApiAdminProductsProductIdMediaPostMutationOptions(options),
    queryClient,
  )
}
/**
 * @summary Admin.Products.Media.Destroy
 */
export const adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete = (
  productId: MaybeRef<string>,
  mediaId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  productId = unref(productId)
  mediaId = unref(mediaId)

  return request<unknown>(
    { url: `/api/admin/products/${productId}/media/${mediaId}`, method: 'DELETE', signal },
    options,
  )
}

export const getAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationOptions =
  <TError = HTTPValidationError, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
      >,
      TError,
      { productId: string; mediaId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
    >,
    TError,
    { productId: string; mediaId: string },
    TContext
  > => {
    const mutationKey = ['adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete']
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined }

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
      >,
      { productId: string; mediaId: string }
    > = (props) => {
      const { productId, mediaId } = props ?? {}

      return adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete(
        productId,
        mediaId,
        requestOptions,
      )
    }

    return { mutationFn, ...mutationOptions }
  }

export type AdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>>
  >

export type AdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationError =
  HTTPValidationError

/**
 * @summary Admin.Products.Media.Destroy
 */
export const useAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>
      >,
      TError,
      { productId: string; mediaId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDelete>>,
  TError,
  { productId: string; mediaId: string },
  TContext
> => {
  return useMutation(
    getAdminProductsMediaDestroyApiAdminProductsProductIdMediaMediaIdDeleteMutationOptions(options),
    queryClient,
  )
}
