"""``make:*`` code generators.

Each generator is a single-command ``typer.Typer`` app (mounted lazily by
``LazyGroup``). They scaffold a typed stub into the app's ``app/<area>/`` package.
The pure file-writing core (:func:`generate`) takes a ``base`` path so it is unit
testable. Grounded in knowledge/port/13-console.md.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

import typer

_CREATE_MIGRATION = (
    "from arvel.database import Blueprint, Migration\n"
    "from arvel.database.migrations import Schema\n\n\n"
    "class {cls}(Migration):\n"
    "    def up(self, schema: Schema) -> None:\n"
    "        def define(t: Blueprint) -> None:\n"
    "            t.id()\n"
    "            t.timestamps()\n\n"
    '        schema.create("{table}", define)\n\n'
    "    def down(self, schema: Schema) -> None:\n"
    '        schema.drop("{table}")\n'
)
_GENERIC_MIGRATION = (
    "from arvel.database import Migration\n"
    "from arvel.database.migrations import Schema\n\n\n"
    "class {cls}(Migration):\n"
    "    def up(self, schema: Schema) -> None:\n"
    "        ...\n\n"
    "    def down(self, schema: Schema) -> None:\n"
    "        ...\n"
)


def _load_stub(base: Path | None, filename: str, fallback: str) -> str:
    """An app-published stub (``stubs/<filename>`` — see ``stub:publish``) overrides the built-in
    template; editing it changes what the generators write, without a code change here."""
    path = (base or Path()) / "stubs" / filename
    return path.read_text() if path.is_file() else fallback


def generate_migration(
    name: str, base: Path | None = None, *, create: str | None = None, table: str | None = None
) -> Path:
    """Write a timestamped migration ``database/migrations/<ts>_<name>.py`` (
    ``make:migration``). ``--create=<table>`` forces the create/drop stub for that table;
    ``--table=<table>`` forces the generic (alter) stub against it. Otherwise the stub is inferred
    from the name: a ``create_<table>_table`` name gets create/drop, any other gets generic."""
    from arvel.support import Str

    directory = (base or Path()) / "database" / "migrations"
    directory.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(UTC).strftime("%Y_%m_%d_%H%M%S")
    target = directory / f"{stamp}_{name}.py"
    if target.exists():
        message = f"migration {name!r} already exists at {target}"
        raise FileExistsError(message)
    cls = Str.studly(name)
    inferred = re.fullmatch(r"create_(\w+?)_table", name)
    create_table = create or (inferred.group(1) if inferred and not table else None)
    if create_table:
        template = _load_stub(base, "migration.create.stub", _CREATE_MIGRATION)
        body = template.format(cls=cls, table=create_table)
    else:
        template = _load_stub(base, "migration.generic.stub", _GENERIC_MIGRATION)
        body = template.format(cls=cls)
    target.write_text(body)
    return target


# kind -> (target folder, stub template keyed on {name})
_STUBS: dict[str, tuple[str, str]] = {
    "model": (
        "app/models",
        "from typing import ClassVar\n\n"
        "from arvel import Model\n\n\n"
        "class {name}(Model):\n"
        "    __fillable__: ClassVar[list[str]] = []\n",
    ),
    "controller": (
        "app/controllers",
        "from typing import Any\n\n"
        "from arvel.http import Request\n"
        "from arvel.routing import Controller\n\n\n"
        "class {name}(Controller):\n"
        "    async def index(self, request: Request) -> dict[str, Any]:\n"
        "        return {{}}\n",
    ),
    # resourceful controllers — method set matches Route.resource's 7 routes (the api variant
    # drops the form-display create/edit actions). Generated by `make:model -c -r` / `--api`.
    "resource_controller": (
        "app/controllers",
        "from typing import Any\n\n"
        "from arvel.http import Request\n"
        "from arvel.routing import Controller\n\n\n"
        "class {name}(Controller):\n"
        "    async def index(self, request: Request) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def create(self, request: Request) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def store(self, request: Request) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def show(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def edit(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def update(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def destroy(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n",
    ),
    "api_controller": (
        "app/controllers",
        "from typing import Any\n\n"
        "from arvel.http import Request\n"
        "from arvel.routing import Controller\n\n\n"
        "class {name}(Controller):\n"
        "    async def index(self, request: Request) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def store(self, request: Request) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def show(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def update(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n\n"
        "    async def destroy(self, request: Request, id: str) -> dict[str, Any]:\n        return {{}}\n",
    ),
    "invokable_controller": (
        "app/controllers",
        "from typing import Any\n\n"
        "from arvel.http import Request\n"
        "from arvel.routing import Controller\n\n\n"
        "class {name}(Controller):\n"
        "    async def __call__(self, request: Request) -> dict[str, Any]:\n"
        "        return {{}}\n",
    ),
    "middleware": (
        "app/middleware",
        "from collections.abc import Awaitable, Callable\n"
        "from typing import Any\n\n"
        "from arvel.http import Request\n"
        "from arvel.http.middleware import Middleware\n\n\n"
        "class {name}(Middleware):\n"
        "    async def handle(\n"
        "        self, request: Request, call_next: Callable[[Request], Awaitable[Any]]\n"
        "    ) -> Any:\n"
        "        return await call_next(request)\n",
    ),
    "request": (
        "app/requests",
        "from arvel.validation import FormRequest\n\n\nclass {name}(FormRequest):\n    pass\n",
    ),
    "job": (
        "app/jobs",
        "from typing import Any\n\n"
        "from arvel.queue import Job\n\n\n"
        "class {name}(Job):\n"
        "    async def handle(self) -> Any:\n"
        "        ...\n",
    ),
    "policy": (
        "app/policies",
        "from typing import Any\n\n"
        "from arvel.auth import Authenticatable\n\n\n"
        "class {name}:\n"
        "    async def view(self, user: Authenticatable, model: Any) -> bool:\n"
        "        return False\n\n"
        "    async def create(self, user: Authenticatable) -> bool:\n"
        "        return False\n",
    ),
    "notification": (
        "app/notifications",
        "from typing import Any\n\n"
        "from arvel.notifications import Notifiable, Notification\n\n\n"
        "class {name}(Notification):\n"
        "    def via(self, notifiable: Notifiable) -> list[str]:\n"
        '        return ["mail"]\n\n'
        "    def to_array(self, notifiable: Notifiable) -> dict[str, Any]:\n"
        "        return {{}}\n",
    ),
    "mail": (
        "app/mail",
        "from arvel.mail import Mailable\n\n\n"
        "class {name}(Mailable):\n"
        "    def build(self) -> Mailable:\n"
        '        return self.subject("{name}").html("<p>Hello</p>")\n',
    ),
    "rule": (
        "app/rules",
        "from typing import Any\n\n"
        "from arvel.validation import Rule\n\n\n"
        "class {name}(Rule):\n"
        '    message = "The :attribute is invalid."\n\n'
        "    def passes(self, attribute: str, value: Any) -> bool:\n"
        "        return True\n",
    ),
    "seeder": (
        "database/seeders",
        "from arvel.database import Seeder\n\n\n"
        "class {name}(Seeder):\n"
        "    async def run(self) -> None:\n"
        "        ...\n",
    ),
    "factory": (
        "database/factories",
        "from typing import Any\n\n"
        "from arvel.database import Factory\n\n\n"
        "class {name}(Factory[Any]):\n"
        "    # model = ...  # the model this factory builds (parametrize Factory[YourModel])\n"
        "    def definition(self) -> dict[str, Any]:\n"
        "        return {{}}\n",
    ),
    "provider": (
        "app/providers",
        "from arvel.kernel import ServiceProvider\n\n\n"
        "class {name}(ServiceProvider):\n"
        "    def register(self) -> None:\n"
        "        ...\n\n"
        "    def boot(self) -> None:\n"
        "        ...\n",
    ),
    "command": (
        "app/commands",
        "from typing import Any\n\n"
        "from arvel.console import Command\n\n\n"
        "class {name}(Command):\n"
        '    signature = "app:command"  # the CLI invocation name (edit me)\n'
        '    description = ""\n\n'
        "    async def handle(self, *deps: Any) -> Any:\n"
        "        # register this command in a provider's commands() to wire it into the CLI\n"
        '        self.info("{name} ran")\n',
    ),
    "event": (
        "app/events",
        "from typing import Any\n\n\n"
        "class {name}:\n"
        '    """A domain event — dispatch with ``await Event.dispatch({name}(...))``."""\n\n'
        "    def __init__(self, *args: Any) -> None: ...\n",
    ),
    "listener": (
        "app/listeners",
        "from typing import Any\n\n\n"
        "class {name}:\n"
        '    """An event listener — register with ``Event.listen(SomeEvent, {name}().handle)``."""\n\n'
        "    async def handle(self, event: Any) -> None: ...\n",
    ),
    "cast": (
        "app/casts",
        "from typing import Any\n\n"
        "from arvel import Model\n\n\n"
        "class {name}:\n"
        '    """A custom attribute cast. Use via\n'
        '    ``__casts__ = {{"column": {name}()}}``."""\n\n'
        "    def get(self, model: Model, key: str, value: Any, attributes: dict[str, Any]) -> Any:\n"
        "        return value\n\n"
        "    def set(self, model: Model, key: str, value: Any, attributes: dict[str, Any]) -> Any:\n"
        "        return value\n",
    ),
    "observer": (
        "app/observers",
        "from arvel import Model\n\n\n"
        "class {name}:\n"
        '    """A model observer. Declare on the model: ``__observers__ = ({name},)``;\n'
        '    `saving` may return False to cancel the save."""\n\n'
        "    async def saving(self, model: Model) -> bool | None: ...\n\n"
        "    async def saved(self, model: Model) -> None: ...\n\n"
        "    async def deleted(self, model: Model) -> None: ...\n",
    ),
    "enum": (
        "app/enums",
        "from enum import StrEnum\n\n\n"
        "class {name}(StrEnum):\n"
        '    """A string-backed enum — a typed closed value set (use as a model `__casts__` enum)."""\n\n'
        '    EXAMPLE = "example"\n',
    ),
    "exception": (
        "app/exceptions",
        "class {name}(Exception):\n"
        '    """An application exception. Set `status` (+ optionally a `detail`) and the HTTP kernel\n'
        '    renders it with that status code."""\n\n'
        "    status = 500\n",
    ),
}

# pytest discovers `test_*.py`, so make:test writes `tests/test_<name>.py`, unlike the other generators
_TEST_STUB = (
    "from __future__ import annotations\n\n\n"
    "def test_{name}() -> None:\n"
    "    assert True  # TODO: write the test\n"
)


def generate_test(name: str, base: Path | None = None, *, force: bool = False) -> Path:
    """Write ``tests/test_<name>.py``."""
    from arvel.support import Str

    directory = (base or Path()) / "tests"
    directory.mkdir(parents=True, exist_ok=True)
    slug = Str.snake(name).removeprefix("test_")
    target = directory / f"test_{slug}.py"
    if target.exists() and not force:
        message = f"test {name!r} already exists at {target}"
        raise FileExistsError(message)
    template = _load_stub(base, "test.stub", _TEST_STUB)
    target.write_text(template.format(name=slug))
    return target


def generate(kind: str, name: str, base: Path | None = None, *, force: bool = False) -> Path:
    """Write the ``kind`` stub for class ``name`` under ``base`` (defaults to cwd). ``force``
    overwrites an existing file instead of raising ``FileExistsError``."""
    from arvel.support import Str

    folder, fallback_template = _STUBS[kind]
    template = _load_stub(base, f"{kind}.stub", fallback_template)
    directory = (base or Path()) / folder
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "__init__.py").touch()
    target = directory / f"{Str.snake(name)}.py"
    if target.exists() and not force:
        message = f"{kind} {name!r} already exists at {target}"
        raise FileExistsError(message)
    target.write_text(template.format(name=name))
    return target


#: shared ``--force`` option for the generator commands (overwrite an existing file).
_FORCE = typer.Option(False, "--force", help="Overwrite the file if it already exists.")


def _run(kind: str, name: str, *, force: bool = False) -> None:
    try:
        target = generate(kind, name, force=force)
    except FileExistsError as exc:
        typer.echo(str(exc))
        raise typer.Exit(1) from exc
    typer.echo(f"created {target}")


make_model_app = typer.Typer()


@make_model_app.command()
def make_model(
    name: str,
    migration: bool = typer.Option(
        False, "-m", "--migration", help="Also generate a create_<table>_table migration."
    ),
    factory: bool = typer.Option(False, "-f", "--factory", help="Also generate a factory."),
    seeder: bool = typer.Option(False, "-s", "--seed", help="Also generate a seeder."),
    controller: bool = typer.Option(False, "-c", "--controller", help="Also generate a controller."),
    resource: bool = typer.Option(
        False, "-r", "--resource", help="Make the controller resourceful (CRUD)."
    ),
    api: bool = typer.Option(
        False, "--api", help="Make the controller an API resource (no create/edit)."
    ),
    policy: bool = typer.Option(False, "-p", "--policy", help="Also generate a policy."),
    all_: bool = typer.Option(
        False, "-a", "--all", help="Generate migration, factory, seeder, resource controller + policy."
    ),
) -> None:
    """Generate an Active-Record model (app/models/), with optional companions: -m migration,
    -f factory, -s seeder, -c controller (-r resourceful / --api), -p policy, or -a for all."""
    from arvel.support import Str

    if all_:
        migration = factory = seeder = controller = resource = policy = True
    if resource or api:
        controller = True  # -r / --api imply a controller

    studly = Str.studly(name)
    created: list[str] = []
    skipped: list[str] = []

    def emit(produce: Callable[[], Path]) -> None:
        # a companion that already exists is skipped with a note, not fatal to the rest of the scaffold
        try:
            created.append(f"created {produce()}")
        except FileExistsError as exc:
            skipped.append(str(exc))

    emit(lambda: generate("model", studly))
    if controller:
        kind = "api_controller" if api else "resource_controller" if resource else "controller"
        emit(lambda: generate(kind, f"{studly}Controller"))
    if migration:
        table = Str.snake(Str.plural(studly))
        emit(lambda: generate_migration(f"create_{table}_table"))
    if factory:
        emit(lambda: generate("factory", f"{studly}Factory"))
    if seeder:
        emit(lambda: generate("seeder", f"{studly}Seeder"))
    if policy:
        emit(lambda: generate("policy", f"{studly}Policy"))

    for line in (*created, *skipped):
        typer.echo(line)
    if skipped and not created:  # everything asked for already existed
        raise typer.Exit(1)


make_controller_app = typer.Typer()


@make_controller_app.command()
def make_controller(
    name: str,
    resource: bool = typer.Option(
        False, "-r", "--resource", help="Resourceful controller (7 CRUD actions)."
    ),
    api: bool = typer.Option(False, "--api", help="API resource controller (no create/edit)."),
    invokable: bool = typer.Option(
        False, "-i", "--invokable", help="Single-action __call__ controller."
    ),
    force: bool = _FORCE,
) -> None:
    """Generate a controller (app/controllers/): -r resourceful, --api API resource, -i invokable."""
    kind = (
        "api_controller"
        if api
        else "resource_controller"
        if resource
        else "invokable_controller"
        if invokable
        else "controller"
    )
    _run(kind, name, force=force)


make_middleware_app = typer.Typer()


@make_middleware_app.command()
def make_middleware(name: str, force: bool = _FORCE) -> None:
    """Generate a middleware (app/middleware/)."""
    _run("middleware", name, force=force)


make_request_app = typer.Typer()


@make_request_app.command()
def make_request(name: str, force: bool = _FORCE) -> None:
    """Generate a FormRequest (app/requests/)."""
    _run("request", name, force=force)


make_job_app = typer.Typer()


@make_job_app.command()
def make_job(name: str, force: bool = _FORCE) -> None:
    """Generate a queued job (app/jobs/)."""
    _run("job", name, force=force)


make_policy_app = typer.Typer()


@make_policy_app.command()
def make_policy(name: str, force: bool = _FORCE) -> None:
    """Generate an authorization policy (app/policies/)."""
    _run("policy", name, force=force)


make_notification_app = typer.Typer()


@make_notification_app.command()
def make_notification(name: str, force: bool = _FORCE) -> None:
    """Generate a notification (app/notifications/)."""
    _run("notification", name, force=force)


make_mail_app = typer.Typer()


@make_mail_app.command()
def make_mail(name: str, force: bool = _FORCE) -> None:
    """Generate a mailable (app/mail/)."""
    _run("mail", name, force=force)


make_rule_app = typer.Typer()


@make_rule_app.command()
def make_rule(name: str, force: bool = _FORCE) -> None:
    """Generate a validation rule (app/rules/)."""
    _run("rule", name, force=force)


make_seeder_app = typer.Typer()


@make_seeder_app.command()
def make_seeder(name: str, force: bool = _FORCE) -> None:
    """Generate a database seeder (database/seeders/)."""
    _run("seeder", name, force=force)


make_factory_app = typer.Typer()


@make_factory_app.command()
def make_factory(name: str, force: bool = _FORCE) -> None:
    """Generate a model factory (database/factories/)."""
    _run("factory", name, force=force)


make_provider_app = typer.Typer()


@make_provider_app.command()
def make_provider(name: str, force: bool = _FORCE) -> None:
    """Generate a service provider (app/providers/)."""
    _run("provider", name, force=force)


make_command_app = typer.Typer()


@make_command_app.command()
def make_command(name: str, force: bool = _FORCE) -> None:
    """Generate a console command (app/commands/) — register it in a provider's commands()."""
    _run("command", name, force=force)


make_migration_app = typer.Typer()


@make_migration_app.command()
def make_migration(
    name: str,
    create: str = typer.Option("", "--create", help="Force a create-table stub for TABLE."),
    table: str = typer.Option("", "--table", help="Force a generic (alter) stub against TABLE."),
) -> None:
    """Generate a timestamped migration (database/migrations/), e.g. create_posts_table.
    ``--create=<table>`` / ``--table=<table>`` set the stub explicitly instead of inferring it."""
    try:
        target = generate_migration(name, create=create or None, table=table or None)
    except FileExistsError as exc:
        typer.echo(str(exc))
        raise typer.Exit(1) from exc
    typer.echo(f"created {target}")


make_event_app = typer.Typer()


@make_event_app.command()
def make_event(name: str, force: bool = _FORCE) -> None:
    """Generate a domain event class (app/events/)."""
    _run("event", name, force=force)


make_listener_app = typer.Typer()


@make_listener_app.command()
def make_listener(name: str, force: bool = _FORCE) -> None:
    """Generate an event listener (app/listeners/) — register via Event.listen(...)."""
    _run("listener", name, force=force)


make_cast_app = typer.Typer()


@make_cast_app.command()
def make_cast(name: str, force: bool = _FORCE) -> None:
    """Generate a custom attribute cast (app/casts/) — use via a model's __casts__."""
    _run("cast", name, force=force)


make_observer_app = typer.Typer()


@make_observer_app.command()
def make_observer(name: str, force: bool = _FORCE) -> None:
    """Generate a model observer (app/observers/) — declare via ``__observers__`` on the model."""
    _run("observer", name, force=force)


make_enum_app = typer.Typer()


@make_enum_app.command()
def make_enum(name: str, force: bool = _FORCE) -> None:
    """Generate a string-backed enum (app/enums/)."""
    _run("enum", name, force=force)


make_exception_app = typer.Typer()


@make_exception_app.command()
def make_exception(name: str, force: bool = _FORCE) -> None:
    """Generate an exception class (app/exceptions/)."""
    _run("exception", name, force=force)


make_test_app = typer.Typer()


@make_test_app.command()
def make_test(name: str, force: bool = _FORCE) -> None:
    """Generate a test (tests/test_<name>.py)."""
    try:
        target = generate_test(name, force=force)
    except FileExistsError as exc:
        typer.echo(str(exc))
        raise typer.Exit(1) from exc
    typer.echo(f"created {target}")


#: every ``kind.stub`` a generator consults (see ``_load_stub``) — the ``make:*`` template
#: filenames plus the two migration variants and the test stub.
_ALL_STUBS: dict[str, str] = {
    **{f"{kind}.stub": template for kind, (_, template) in _STUBS.items()},
    "migration.create.stub": _CREATE_MIGRATION,
    "migration.generic.stub": _GENERIC_MIGRATION,
    "test.stub": _TEST_STUB,
}

stub_publish_app = typer.Typer()


@stub_publish_app.command()
def stub_publish(
    force: bool = typer.Option(False, "--force", help="Overwrite already-published stubs."),
) -> None:
    """Publish the generator stubs to./stubs so you can customize them —
    a generator prefers ``stubs/<kind>.stub`` over its built-in template once one is published."""
    directory = Path() / "stubs"
    directory.mkdir(parents=True, exist_ok=True)
    published = skipped = 0
    for filename, template in _ALL_STUBS.items():
        target = directory / filename
        if target.exists() and not force:
            skipped += 1
            continue
        target.write_text(template)
        published += 1
    note = f", {skipped} already existed (skipped; pass --force to overwrite)" if skipped else ""
    typer.echo(f"[stub:publish] published {published} stub(s) to {directory}{note}")
