"""``make:schema`` — generate Pydantic Create/Update/Read schemas from a model.

The lesson behind this command (L6 from the SQLModel research at
``.context/research/002-sqlmodel-vs-sqla-typed-mappers.md``): SQLModel's
appeal is one definition for storage + boundary, but the price is a
metaclass fusion that breaks pyright strict-mode and ties the storage layer
to a Pydantic version. The Arvel alternative is **codegen, not fusion** —
the storage layer stays SQLAlchemy, the boundary stays Pydantic, and
this command writes the boundary schemas mechanically from the storage
shape so they never drift::

    $ arvel make:schema User
    Created: app/schemas/user_schema.py

The generated file contains three classes::

    class UserRead(BaseModel)    # every persisted column, ``from_attributes=True``
    class UserCreate(BaseModel)  # input shape — server-managed fields excluded
    class UserUpdate(BaseModel)  # partial-update shape — every Create field optional

Server-managed fields excluded from ``Create``: primary keys with
``autoincrement=True``, columns marked in ``__hidden__``, and the
``Timestamps`` columns (``created_at`` / ``updated_at`` / ``deleted_at``).
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path
from typing import Annotated, Any, ClassVar

import typer
from sqlalchemy import inspect as sqla_inspect
from sqlalchemy.orm import ColumnProperty, Mapper
from sqlalchemy.types import (
    JSON,
    BigInteger,
    Boolean,
    Date,
    DateTime,
    Float,
    Integer,
    LargeBinary,
    Numeric,
    SmallInteger,
    String,
    Text,
    Time,
)

from arvel.console import Command, Context
from arvel.console._t import Argument as _Argument
from arvel.console._t import Option as _Option
from arvel.support.str import Str

# Fields the framework manages — never appear on a Create payload.
_SERVER_MANAGED: frozenset[str] = frozenset({"created_at", "updated_at", "deleted_at"})


# SQLA-type → (python annotation, set of import lines needed). Order matters
# only for subclass relationships: ``BigInteger`` is a subclass of ``Integer``
# so a Tuple-keyed lookup must check more specific types first. We use
# ``isinstance`` against a tuple of (type, mapping_entry) below to preserve
# that ordering predictably without a long if/elif ladder.
_TYPE_MAP: tuple[tuple[type, str, frozenset[str]], ...] = (
    (Boolean, "bool", frozenset()),
    (BigInteger, "int", frozenset()),
    (SmallInteger, "int", frozenset()),
    (Integer, "int", frozenset()),
    (String, "str", frozenset()),
    (Text, "str", frozenset()),
    (DateTime, "datetime", frozenset({"from datetime import datetime"})),
    (Date, "date", frozenset({"from datetime import date"})),
    (Time, "time", frozenset({"from datetime import time"})),
    (Numeric, "Decimal", frozenset({"from decimal import Decimal"})),
    (Float, "float", frozenset()),
    (LargeBinary, "bytes", frozenset()),
    (JSON, "dict[str, Any]", frozenset({"from typing import Any"})),
)


def _is_email_column(name: str, col_type: Any) -> bool:
    """``email``-named string columns get ``EmailStr`` at the boundary.

    The storage layer stays VARCHAR. This heuristic catches
    the common Laravel-style naming — ``email``, ``contact_email``,
    ``billing_email`` — without forcing users to hand-edit the generated
    schema. To opt out, run ``make:schema --force`` and edit the file.
    """
    if not isinstance(col_type, String):
        return False
    return name == "email" or name.endswith("_email")


def _sqla_to_python(name: str, col_type: Any) -> tuple[str, set[str]]:
    """Map an SQLAlchemy column to ``(python_annotation, imports_needed)``.

    The second element is a set of import lines (``"from x import y"``) that
    must appear at the top of the generated file. Unknown types fall back to
    ``Any`` — better honest than wrong.

    The column ``name`` is consulted only for the ``email`` → ``EmailStr``
    upgrade; everything else is dispatched purely on the SQLA type.
    """
    if _is_email_column(name, col_type):
        return "EmailStr", {"from pydantic import EmailStr"}
    for sa_type, annotation, imports in _TYPE_MAP:
        if isinstance(col_type, sa_type):
            return annotation, set(imports)
    return "Any", {"from typing import Any"}


def _is_server_managed(col_attr: ColumnProperty[Any], hidden: set[str]) -> bool:
    """Is this column managed by the framework / hidden / autoincrement-PK?"""
    if col_attr.key in _SERVER_MANAGED or col_attr.key in hidden:
        return True
    col = col_attr.columns[0]
    return bool(col.primary_key and col.autoincrement)


_TEMPLATE = '''"""Pydantic schemas for {model_pascal} — generated by ``arvel make:schema``.

Regenerate with: ``arvel make:schema {model_pascal} --force``
This file is meant to be edited; ``--force`` will overwrite it.
"""

from __future__ import annotations

{imports}
from pydantic import BaseModel, ConfigDict


class {model_pascal}Read(BaseModel):
    """Read-side projection — every persisted column."""

    model_config = ConfigDict(from_attributes=True)

{read_fields}


class {model_pascal}Create(BaseModel):
    """Input shape for creating a {model_pascal} — server-managed fields excluded."""

    model_config = ConfigDict(extra="forbid")

{create_fields}


class {model_pascal}Update(BaseModel):
    """Partial-update shape — every Create field optional."""

    model_config = ConfigDict(extra="forbid")

{update_fields}
'''


def _render(
    model_pascal: str,
    *,
    read_fields: list[tuple[str, str, bool]],  # (name, type, nullable)
    create_fields: list[tuple[str, str, bool]],
    update_fields: list[tuple[str, str]],
    imports: set[str],
) -> str:
    """Stitch the template together."""

    def fmt_read(rows: list[tuple[str, str, bool]]) -> str:
        if not rows:
            return "    pass"
        out: list[str] = []
        for name, py_type, nullable in rows:
            annotation = f"{py_type} | None" if nullable else py_type
            out.append(f"    {name}: {annotation}")
        return "\n".join(out)

    def fmt_create(rows: list[tuple[str, str, bool]]) -> str:
        if not rows:
            return "    pass"
        out: list[str] = []
        for name, py_type, nullable in rows:
            if nullable:
                out.append(f"    {name}: {py_type} | None = None")
            else:
                out.append(f"    {name}: {py_type}")
        return "\n".join(out)

    def fmt_update(rows: list[tuple[str, str]]) -> str:
        if not rows:
            return "    pass"
        return "\n".join(f"    {name}: {py_type} | None = None" for name, py_type in rows)

    import_block = "\n".join(sorted(imports)) + ("\n" if imports else "")
    return _TEMPLATE.format(
        model_pascal=model_pascal,
        imports=import_block,
        read_fields=fmt_read(read_fields),
        create_fields=fmt_create(create_fields),
        update_fields=fmt_update(update_fields),
    )


class MakeSchemaCommand(Command):
    """Generate Pydantic schemas from a model class."""

    name: ClassVar[str] = "make:schema"
    help: ClassVar[str] = "Generate Pydantic Create/Update/Read schemas from a model"

    def register(self, app: typer.Typer) -> None:
        cmd_self = self

        def _callback(
            name: Annotated[str, _Argument(help="Model name (e.g. User)")],
            *,
            force: Annotated[
                bool, _Option("--force", help="Overwrite an existing schema file")
            ] = False,
        ) -> None:
            code = cmd_self.make(name, force=force)
            if code != 0:
                raise typer.Exit(code)

        app.command(name=self.name, help=self.help)(_callback)

    def handle(self, ctx: Context) -> int:
        raise NotImplementedError

    def make(self, name: str, *, force: bool = False) -> int:
        pascal = Str.pascal(name)
        snake = Str.snake(pascal)

        model_cls = self._import_model(snake, pascal)
        if model_cls is None:
            return 2

        try:
            mapper: Mapper[Any] = sqla_inspect(model_cls)
        except Exception as exc:  # noqa: BLE001 — surface the SQLA error to the user
            typer.echo(f"arvel: {pascal} is not a mapped SQLA class: {exc}", err=True)
            return 2

        hidden_attr: list[str] | None = getattr(model_cls, "__hidden__", None)
        hidden_set: set[str] = set(hidden_attr) if hidden_attr else set()

        read_fields: list[tuple[str, str, bool]] = []
        create_fields: list[tuple[str, str, bool]] = []
        update_fields: list[tuple[str, str]] = []
        imports: set[str] = set()

        col_attr: ColumnProperty[Any]
        for col_attr in mapper.column_attrs:
            col = col_attr.columns[0]
            py_type, ann_imports = _sqla_to_python(col_attr.key, col.type)
            imports.update(ann_imports)
            nullable = bool(col.nullable)
            key: str = col_attr.key
            # Read includes everything (including server-managed columns).
            # Hidden columns are excluded from Read because to_dict() hides them too.
            if key not in hidden_set:
                read_fields.append((key, py_type, nullable))
            if not _is_server_managed(col_attr, hidden_set):
                create_fields.append((key, py_type, nullable))
                update_fields.append((key, py_type))

        contents = _render(
            pascal,
            read_fields=read_fields,
            create_fields=create_fields,
            update_fields=update_fields,
            imports=imports,
        )

        target_dir = Path("app") / "schemas"
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / f"{snake}_schema.py"

        if target.exists() and not force:
            typer.echo(f"arvel: {target} already exists. Pass --force to overwrite.", err=True)
            return 1

        target.write_text(contents)
        typer.echo(f"Created: {target}")
        return 0

    def _import_model(self, snake: str, pascal: str) -> type[Any] | None:
        """Import ``app.models.<snake>.<pascal>`` from the current working directory.

        Returns the class on success; prints a diagnostic and returns ``None``
        on any failure. The cwd is prepended to ``sys.path`` for the duration
        of the import so the command works in any Arvel project layout.
        """
        cwd = str(Path.cwd().resolve())
        added = False
        if cwd not in sys.path:
            sys.path.insert(0, cwd)
            added = True
        try:
            module = importlib.import_module(f"app.models.{snake}")
        except ImportError as exc:
            typer.echo(
                f"arvel: cannot import app.models.{snake}: {exc}\n"
                f"       Run `arvel make:model {pascal}` first, or check the model lives "
                f"at app/models/{snake}.py.",
                err=True,
            )
            return None
        finally:
            if added:
                sys.path.remove(cwd)

        model_cls: Any = getattr(module, pascal, None)
        if model_cls is None:
            typer.echo(f"arvel: app.models.{snake} does not define class {pascal}.", err=True)
            return None
        if not isinstance(model_cls, type):
            typer.echo(f"arvel: app.models.{snake}.{pascal} is not a class.", err=True)
            return None
        return model_cls


__all__ = ["MakeSchemaCommand"]
