/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  HTTPValidationError,
  ProductDetailOut,
  ProductListOut,
  SearchOut,
  StorefrontCategoryListOut,
  StorefrontIndexApiProductsGetParams,
  StorefrontProductsCatalogAltApiCategoriesSlugProductsGetParams,
  StorefrontProductsCatalogApiCategoriesSlugGetParams,
  StorefrontSearchApiSearchGetParams,
  StorefrontShowApiProductsSlugGetParams,
} from '../schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Storefront.Index
 */
export const storefrontIndexApiProductsGet = (
  params?: MaybeRef<StorefrontIndexApiProductsGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<ProductListOut>(
    { url: `/api/products`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getStorefrontIndexApiProductsGetQueryKey = (
  params?: MaybeRef<StorefrontIndexApiProductsGetParams>,
) => {
  return ['api', 'products', ...(params ? [params] : [])] as const
}

export const getStorefrontIndexApiProductsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<StorefrontIndexApiProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getStorefrontIndexApiProductsGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>> = ({
    signal,
  }) => storefrontIndexApiProductsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>,
    TError,
    TData
  >
}

export type StorefrontIndexApiProductsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>
>
export type StorefrontIndexApiProductsGetQueryError = HTTPValidationError

/**
 * @summary Storefront.Index
 */

export function useStorefrontIndexApiProductsGet<
  TData = Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<StorefrontIndexApiProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof storefrontIndexApiProductsGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStorefrontIndexApiProductsGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Storefront.Show
 */
export const storefrontShowApiProductsSlugGet = (
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontShowApiProductsSlugGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  slug = unref(slug)
  params = unref(params)

  return request<ProductDetailOut>(
    { url: `/api/products/${slug}`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getStorefrontShowApiProductsSlugGetQueryKey = (
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontShowApiProductsSlugGetParams>,
) => {
  return ['api', 'products', slug, ...(params ? [params] : [])] as const
}

export const getStorefrontShowApiProductsSlugGetQueryOptions = <
  TData = Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>,
  TError = HTTPValidationError,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontShowApiProductsSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getStorefrontShowApiProductsSlugGetQueryKey(slug, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>> = ({
    signal,
  }) => storefrontShowApiProductsSlugGet(slug, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => unref(slug) !== null && unref(slug) !== undefined),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>, TError, TData>
}

export type StorefrontShowApiProductsSlugGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>
>
export type StorefrontShowApiProductsSlugGetQueryError = HTTPValidationError

/**
 * @summary Storefront.Show
 */

export function useStorefrontShowApiProductsSlugGet<
  TData = Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>,
  TError = HTTPValidationError,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontShowApiProductsSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof storefrontShowApiProductsSlugGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStorefrontShowApiProductsSlugGetQueryOptions(slug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Storefront.Categories.Index
 */
export const storefrontCategoriesIndexApiCategoriesGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<StorefrontCategoryListOut>(
    { url: `/api/categories`, method: 'GET', signal },
    options,
  )
}

export const getStorefrontCategoriesIndexApiCategoriesGetQueryKey = () => {
  return ['api', 'categories'] as const
}

export const getStorefrontCategoriesIndexApiCategoriesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getStorefrontCategoriesIndexApiCategoriesGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>
  > = ({ signal }) => storefrontCategoriesIndexApiCategoriesGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>,
    TError,
    TData
  >
}

export type StorefrontCategoriesIndexApiCategoriesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>
>
export type StorefrontCategoriesIndexApiCategoriesGetQueryError = unknown

/**
 * @summary Storefront.Categories.Index
 */

export function useStorefrontCategoriesIndexApiCategoriesGet<
  TData = Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storefrontCategoriesIndexApiCategoriesGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStorefrontCategoriesIndexApiCategoriesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Storefront.Products Catalog
 */
export const storefrontProductsCatalogApiCategoriesSlugGet = (
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogApiCategoriesSlugGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  slug = unref(slug)
  params = unref(params)

  return request<ProductListOut>(
    { url: `/api/categories/${slug}`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getStorefrontProductsCatalogApiCategoriesSlugGetQueryKey = (
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogApiCategoriesSlugGetParams>,
) => {
  return ['api', 'categories', slug, ...(params ? [params] : [])] as const
}

export const getStorefrontProductsCatalogApiCategoriesSlugGetQueryOptions = <
  TData = Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>,
  TError = HTTPValidationError,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogApiCategoriesSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getStorefrontProductsCatalogApiCategoriesSlugGetQueryKey(slug, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>
  > = ({ signal }) =>
    storefrontProductsCatalogApiCategoriesSlugGet(slug, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => unref(slug) !== null && unref(slug) !== undefined),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>,
    TError,
    TData
  >
}

export type StorefrontProductsCatalogApiCategoriesSlugGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>
>
export type StorefrontProductsCatalogApiCategoriesSlugGetQueryError = HTTPValidationError

/**
 * @summary Storefront.Products Catalog
 */

export function useStorefrontProductsCatalogApiCategoriesSlugGet<
  TData = Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>,
  TError = HTTPValidationError,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogApiCategoriesSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storefrontProductsCatalogApiCategoriesSlugGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStorefrontProductsCatalogApiCategoriesSlugGetQueryOptions(
    slug,
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Storefront.Products Catalog Alt
 */
export const storefrontProductsCatalogAltApiCategoriesSlugProductsGet = (
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogAltApiCategoriesSlugProductsGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  slug = unref(slug)
  params = unref(params)

  return request<ProductListOut>(
    { url: `/api/categories/${slug}/products`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getStorefrontProductsCatalogAltApiCategoriesSlugProductsGetQueryKey = (
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogAltApiCategoriesSlugProductsGetParams>,
) => {
  return ['api', 'categories', slug, 'products', ...(params ? [params] : [])] as const
}

export const getStorefrontProductsCatalogAltApiCategoriesSlugProductsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>,
  TError = HTTPValidationError,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogAltApiCategoriesSlugProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getStorefrontProductsCatalogAltApiCategoriesSlugProductsGetQueryKey(slug, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>
  > = ({ signal }) =>
    storefrontProductsCatalogAltApiCategoriesSlugProductsGet(slug, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => unref(slug) !== null && unref(slug) !== undefined),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>,
    TError,
    TData
  >
}

export type StorefrontProductsCatalogAltApiCategoriesSlugProductsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>
>
export type StorefrontProductsCatalogAltApiCategoriesSlugProductsGetQueryError = HTTPValidationError

/**
 * @summary Storefront.Products Catalog Alt
 */

export function useStorefrontProductsCatalogAltApiCategoriesSlugProductsGet<
  TData = Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>,
  TError = HTTPValidationError,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<StorefrontProductsCatalogAltApiCategoriesSlugProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storefrontProductsCatalogAltApiCategoriesSlugProductsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStorefrontProductsCatalogAltApiCategoriesSlugProductsGetQueryOptions(
    slug,
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Storefront.Search
 */
export const storefrontSearchApiSearchGet = (
  params: MaybeRef<StorefrontSearchApiSearchGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<SearchOut>(
    { url: `/api/search`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getStorefrontSearchApiSearchGetQueryKey = (
  params?: MaybeRef<StorefrontSearchApiSearchGetParams>,
) => {
  return ['api', 'search', ...(params ? [params] : [])] as const
}

export const getStorefrontSearchApiSearchGetQueryOptions = <
  TData = Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>,
  TError = HTTPValidationError,
>(
  params: MaybeRef<StorefrontSearchApiSearchGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getStorefrontSearchApiSearchGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>> = ({
    signal,
  }) => storefrontSearchApiSearchGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>,
    TError,
    TData
  >
}

export type StorefrontSearchApiSearchGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>
>
export type StorefrontSearchApiSearchGetQueryError = HTTPValidationError

/**
 * @summary Storefront.Search
 */

export function useStorefrontSearchApiSearchGet<
  TData = Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>,
  TError = HTTPValidationError,
>(
  params: MaybeRef<StorefrontSearchApiSearchGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof storefrontSearchApiSearchGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStorefrontSearchApiSearchGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
