/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type { ApiErrorOut, TranslationsListOut } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Admin.Translations.Index
 */
export const apiAdminTranslationsIndexApiAdminTranslationsGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<TranslationsListOut>(
    { url: `/api/admin/translations`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminTranslationsIndexApiAdminTranslationsGetQueryKey = () => {
  return ['api', 'admin', 'translations'] as const
}

export const getApiAdminTranslationsIndexApiAdminTranslationsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminTranslationsIndexApiAdminTranslationsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>
  > = ({ signal }) => apiAdminTranslationsIndexApiAdminTranslationsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>,
    TError,
    TData
  >
}

export type ApiAdminTranslationsIndexApiAdminTranslationsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>
>
export type ApiAdminTranslationsIndexApiAdminTranslationsGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Translations.Index
 */

export function useApiAdminTranslationsIndexApiAdminTranslationsGet<
  TData = Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminTranslationsIndexApiAdminTranslationsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminTranslationsIndexApiAdminTranslationsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
