"""Provider discovery — the plugin seam.

Merges three provider sources (framework defaults → installed-package
``arvel.providers`` entry points → the app's own providers), de-duplicated, and
registers them (deferring any that declare ``provides()``). A ``uv add arvel-x``
package is auto-discovered with no app edits.

Grounded in knowledge/port/03-application-providers-bootstrap.md.
"""

from __future__ import annotations

import importlib.metadata as md
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from arvel.kernel.application import Application

#: Framework providers not exposed as entry points (the kernel provider is one, so it's not listed here).
FRAMEWORK_PROVIDERS: list[type] = []

_cache: list[type] | None = None


def manifest_path(base: str | None = None) -> Path:
    """Where the persistent package manifest lives (doc 13 §cached discovery)."""
    root = Path(base) if base is not None else Path.cwd()
    return root / "bootstrap" / "cache" / "packages.py"


def write_manifest(base: str | None = None) -> Path:
    """Resolve the ``arvel.providers`` entry points and cache them to ``bootstrap/cache/packages.py``
    so cold starts read one Python file instead of re-scanning entry points (~10-50 ms). Rebuilt by
    ``arvel package:discover`` (or when the lockfile changes)."""
    names = sorted(ep.value for ep in md.entry_points(group="arvel.providers"))
    path = manifest_path(base)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "# Generated by `arvel package:discover` — do not edit.\nPROVIDERS = [\n"
    body += "".join(f"    {name!r},\n" for name in names)
    body += "]\n"
    path.write_text(body)
    return path


def _load_manifest(base: str | None = None) -> list[type] | None:
    """Load providers from the persistent manifest, or ``None`` if it isn't present."""
    import importlib.util

    path = manifest_path(base)
    if not path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("arvel_packages_cache", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    from arvel.kernel.logging import LogManager

    providers: list[type] = []
    for ref in getattr(module, "PROVIDERS", []):
        module_name, _, attr = str(ref).partition(":")
        try:  # a stale manifest entry (package uninstalled/renamed) must not crash boot
            providers.append(getattr(importlib.import_module(module_name), attr))
        except Exception:
            LogManager().channel("discovery").warning(
                "cached_provider_load_failed", ref=ref, exc_info=True
            )
    return providers


def _load_entry_points(dont: list[str]) -> list[type]:
    """Load the ``arvel.providers`` entry points, **isolating per-package failures** so one broken
    ecosystem package (a bad import in its provider module) can't crash discovery — and with it the
    whole app boot. A failing ``ep.load()`` is skipped with a warning instead of propagating."""
    from arvel.kernel.logging import LogManager

    providers: list[type] = []
    for ep in md.entry_points(group="arvel.providers"):
        if ep.name in dont:
            continue
        try:
            providers.append(ep.load())
        except Exception:
            LogManager().channel("discovery").warning(
                "provider_entry_point_load_failed", entry_point=ep.name, exc_info=True
            )
    return providers


def discover_providers(app: Application, *, use_cache: bool = True) -> list[type]:
    """Return the merged, de-duplicated provider classes for ``app``."""
    global _cache
    entry_point_providers: list[type]
    if use_cache and _cache is not None:
        entry_point_providers = _cache
    elif use_cache and (cached := _load_manifest()) is not None:  # persistent manifest → no scan
        entry_point_providers = cached
        _cache = cached
    else:
        dont: list[str] = app.config("app.dont_discover", []) or []
        entry_point_providers = _load_entry_points(dont)
        _cache = entry_point_providers

    merged: list[type] = [*FRAMEWORK_PROVIDERS, *entry_point_providers, *app.app_provider_classes]
    seen: set[type] = set()
    ordered: list[type] = []
    for provider in merged:
        if provider not in seen:
            seen.add(provider)
            ordered.append(provider)
    return ordered


def bootstrap_providers(app: Application) -> None:
    """Instantiate + register discovered providers (deferring those with provides())."""
    for cls in discover_providers(app):
        if cls in app.registered_provider_types:
            continue
        provider: Any = cls(app)
        if provider.provides():
            app.register_deferred(provider)
        else:
            app.register(provider)


def clear_cache() -> None:
    """Drop the cached entry-point scan (tests / after install)."""
    global _cache
    _cache = None
