/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type { ApiErrorOut, HealthzHealthzGet200 } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Healthz
 */
export const healthzHealthzGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<HealthzHealthzGet200>({ url: `/healthz`, method: 'GET', signal }, options)
}

export const getHealthzHealthzGetQueryKey = () => {
  return ['healthz'] as const
}

export const getHealthzHealthzGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getHealthzHealthzGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthzHealthzGet>>> = ({ signal }) =>
    healthzHealthzGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthzHealthzGet>>,
    TError,
    TData
  >
}

export type HealthzHealthzGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthzHealthzGet>>
>
export type HealthzHealthzGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Healthz
 */

export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthzHealthzGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
