/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type { TranslationsListOut } from '../schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Admin.Translations.Index
 */
export const adminTranslationsIndexApiAdminTranslationsGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<TranslationsListOut>(
    { url: `/api/admin/translations`, method: 'GET', signal },
    options,
  )
}

export const getAdminTranslationsIndexApiAdminTranslationsGetQueryKey = () => {
  return ['api', 'admin', 'translations'] as const
}

export const getAdminTranslationsIndexApiAdminTranslationsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminTranslationsIndexApiAdminTranslationsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>
  > = ({ signal }) => adminTranslationsIndexApiAdminTranslationsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>,
    TError,
    TData
  >
}

export type AdminTranslationsIndexApiAdminTranslationsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>
>
export type AdminTranslationsIndexApiAdminTranslationsGetQueryError = unknown

/**
 * @summary Admin.Translations.Index
 */

export function useAdminTranslationsIndexApiAdminTranslationsGet<
  TData = Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminTranslationsIndexApiAdminTranslationsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminTranslationsIndexApiAdminTranslationsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
