/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type { ApiErrorOut, PermissionsListOut, RolesListOut } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Admin.Roles.Index
 */
export const apiAdminRolesIndexApiAdminRolesGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<RolesListOut>({ url: `/api/admin/roles`, method: 'GET', signal }, options)
}

export const getApiAdminRolesIndexApiAdminRolesGetQueryKey = () => {
  return ['api', 'admin', 'roles'] as const
}

export const getApiAdminRolesIndexApiAdminRolesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>, TError, TData>
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminRolesIndexApiAdminRolesGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>> = ({
    signal,
  }) => apiAdminRolesIndexApiAdminRolesGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>,
    TError,
    TData
  >
}

export type ApiAdminRolesIndexApiAdminRolesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>
>
export type ApiAdminRolesIndexApiAdminRolesGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Roles.Index
 */

export function useApiAdminRolesIndexApiAdminRolesGet<
  TData = Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiAdminRolesIndexApiAdminRolesGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminRolesIndexApiAdminRolesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Permissions.Index
 */
export const apiAdminPermissionsIndexApiAdminPermissionsGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<PermissionsListOut>(
    { url: `/api/admin/permissions`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminPermissionsIndexApiAdminPermissionsGetQueryKey = () => {
  return ['api', 'admin', 'permissions'] as const
}

export const getApiAdminPermissionsIndexApiAdminPermissionsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminPermissionsIndexApiAdminPermissionsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>
  > = ({ signal }) => apiAdminPermissionsIndexApiAdminPermissionsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>,
    TError,
    TData
  >
}

export type ApiAdminPermissionsIndexApiAdminPermissionsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>
>
export type ApiAdminPermissionsIndexApiAdminPermissionsGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Permissions.Index
 */

export function useApiAdminPermissionsIndexApiAdminPermissionsGet<
  TData = Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminPermissionsIndexApiAdminPermissionsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminPermissionsIndexApiAdminPermissionsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
