/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { HTTPValidationError } from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary I18N.Catalogue
 */
export const i18nCatalogueApiI18nLocaleGet = (
  locale: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  locale = unref(locale)

  return request<unknown>({ url: `/api/i18n/${locale}`, method: 'GET', signal }, options)
}

export const getI18nCatalogueApiI18nLocaleGetQueryKey = (locale?: MaybeRef<string>) => {
  return ['api', 'i18n', locale] as const
}

export const getI18nCatalogueApiI18nLocaleGetQueryOptions = <
  TData = Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>,
  TError = HTTPValidationError,
>(
  locale: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getI18nCatalogueApiI18nLocaleGetQueryKey(locale)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>> = ({
    signal,
  }) => i18nCatalogueApiI18nLocaleGet(locale, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(locale)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>, TError, TData>
}

export type I18nCatalogueApiI18nLocaleGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>
>
export type I18nCatalogueApiI18nLocaleGetQueryError = HTTPValidationError

/**
 * @summary I18N.Catalogue
 */

export function useI18nCatalogueApiI18nLocaleGet<
  TData = Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>,
  TError = HTTPValidationError,
>(
  locale: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof i18nCatalogueApiI18nLocaleGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getI18nCatalogueApiI18nLocaleGetQueryOptions(locale, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
