/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminUserOut } from './adminUserOut'

export interface AdminUserWrapperOut {
  data: AdminUserOut
}
