/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminProductOutName } from './adminProductOutName'
import type { AdminProductOutSlug } from './adminProductOutSlug'
import type { AdminProductOutDescription } from './adminProductOutDescription'
import type { AdminProductOutPublishedAt } from './adminProductOutPublishedAt'
import type { AdminProductOutCategoryId } from './adminProductOutCategoryId'
import type { AdminProductOutVendorId } from './adminProductOutVendorId'
import type { AdminProductOutDeletedAt } from './adminProductOutDeletedAt'

export interface AdminProductOut {
  id: string
  name: AdminProductOutName
  slug: AdminProductOutSlug
  description: AdminProductOutDescription
  price: number
  stock_qty: number
  status: string
  published_at: AdminProductOutPublishedAt
  category_id: AdminProductOutCategoryId
  vendor_id: AdminProductOutVendorId
  created_at: string
  updated_at: string
  deleted_at: AdminProductOutDeletedAt
}
