/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminProductsIndexApiAdminProductsGetTrashed } from './adminProductsIndexApiAdminProductsGetTrashed'

export type AdminProductsIndexApiAdminProductsGetParams = {
  trashed?: AdminProductsIndexApiAdminProductsGetTrashed
  limit?: number
  offset?: number
}
