/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminOrderItemProductOutName } from './adminOrderItemProductOutName'

export interface AdminOrderItemProductOut {
  name: AdminOrderItemProductOutName
}
