/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminVendorOut } from './adminVendorOut'

export interface AdminVendorListOut {
  data: AdminVendorOut[]
  total: number
}
