/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ApiAdminProductsIndexApiAdminProductsGetParams = {
  trashed?: string
  status?: string | null
  real_status?: string | null
  slug?: string | null
  limit?: number
  offset?: number
}
