/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorBodyOut } from './errorBodyOut'

/**
 * Unified error envelope returned for 400/401/403/404/409/422/500.
 */
export interface ApiErrorOut {
  error: ErrorBodyOut
}
