/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProductPayloadName } from './createProductPayloadName'
import type { CreateProductPayloadSlug } from './createProductPayloadSlug'
import type { CreateProductPayloadDescription } from './createProductPayloadDescription'

export interface CreateProductPayload {
  name: CreateProductPayloadName
  slug: CreateProductPayloadSlug
  description: CreateProductPayloadDescription
  price: number
  stock_qty: number
  category_id: string
  vendor_id: string
}
