/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorBodyOutDetails } from './errorBodyOutDetails'

export interface ErrorBodyOut {
  code: string
  message: string
  details?: ErrorBodyOutDetails
}
