/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * OAuth-compatible token response body for ``login`` and ``refresh``.

``refresh_token`` and ``csrf_token`` travel as HttpOnly / readable
cookies respectively, not in this body — this shape is intentionally
minimal to reduce the risk of a JS script accidentally logging the
refresh token.
 */
export interface LoginResponse {
  access_token: string
  token_type?: string
  /**
   * Access token lifetime in seconds
   * @minimum 1
   */
  expires_in: number
}
