/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PaginationMetaNextCursor } from './paginationMetaNextCursor'

export interface PaginationMeta {
  next_cursor: PaginationMetaNextCursor
  has_more: boolean
}
