/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCardOutShortDescription } from './productCardOutShortDescription'
import type { ProductCardOutOriginalPrice } from './productCardOutOriginalPrice'
import type { ProductCardOutThumbnailUrl } from './productCardOutThumbnailUrl'
import type { ProductCardOutRating } from './productCardOutRating'
import type { ProductCardOutRatingCount } from './productCardOutRatingCount'
import type { ProductCardOutCategoryId } from './productCardOutCategoryId'
import type { ProductCardOutCategoryName } from './productCardOutCategoryName'
import type { ProductCardOutCategorySlug } from './productCardOutCategorySlug'
import type { ProductCardOutCategoryParentId } from './productCardOutCategoryParentId'
import type { ProductCardOutParentCategoryName } from './productCardOutParentCategoryName'
import type { ProductCardOutParentCategorySlug } from './productCardOutParentCategorySlug'
import type { ProductCardOutVendorId } from './productCardOutVendorId'
import type { ProductCardOutVendorName } from './productCardOutVendorName'
import type { ProductCardOutVendorSlug } from './productCardOutVendorSlug'

export interface ProductCardOut {
  id: string
  name: string
  slug: string
  short_description: ProductCardOutShortDescription
  price: number
  stock: number
  original_price: ProductCardOutOriginalPrice
  thumbnail_url: ProductCardOutThumbnailUrl
  image_srcset: string
  image_sizes: string
  rating: ProductCardOutRating
  rating_count: ProductCardOutRatingCount
  is_new: boolean
  is_bestseller: boolean
  category_id: ProductCardOutCategoryId
  category_name: ProductCardOutCategoryName
  category_slug: ProductCardOutCategorySlug
  category_parent_id: ProductCardOutCategoryParentId
  parent_category_name: ProductCardOutParentCategoryName
  parent_category_slug: ProductCardOutParentCategorySlug
  vendor_id: ProductCardOutVendorId
  vendor_name: ProductCardOutVendorName
  vendor_slug: ProductCardOutVendorSlug
}
