/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StorefrontCategoryProductsApiCategoriesSlugProductsGetParams = {
  limit?: number
  cursor?: string | null
  locale?: string | null
}
