/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateCategoryPayloadName } from './updateCategoryPayloadName'
import type { UpdateCategoryPayloadSlug } from './updateCategoryPayloadSlug'
import type { UpdateCategoryPayloadParentId } from './updateCategoryPayloadParentId'
import type { UpdateCategoryPayloadStatus } from './updateCategoryPayloadStatus'
import type { UpdateCategoryPayloadPublishedAt } from './updateCategoryPayloadPublishedAt'

export interface UpdateCategoryPayload {
  name?: UpdateCategoryPayloadName
  slug?: UpdateCategoryPayloadSlug
  parent_id?: UpdateCategoryPayloadParentId
  status?: UpdateCategoryPayloadStatus
  published_at?: UpdateCategoryPayloadPublishedAt
}
