/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateProductPayloadName } from './updateProductPayloadName'
import type { UpdateProductPayloadSlug } from './updateProductPayloadSlug'
import type { UpdateProductPayloadDescription } from './updateProductPayloadDescription'
import type { UpdateProductPayloadPrice } from './updateProductPayloadPrice'
import type { UpdateProductPayloadStockQty } from './updateProductPayloadStockQty'
import type { UpdateProductPayloadCategoryId } from './updateProductPayloadCategoryId'
import type { UpdateProductPayloadVendorId } from './updateProductPayloadVendorId'

export interface UpdateProductPayload {
  name?: UpdateProductPayloadName
  slug?: UpdateProductPayloadSlug
  description?: UpdateProductPayloadDescription
  price?: UpdateProductPayloadPrice
  stock_qty?: UpdateProductPayloadStockQty
  category_id?: UpdateProductPayloadCategoryId
  vendor_id?: UpdateProductPayloadVendorId
}
