/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminUserListOut,
  AdminUserWrapperOut,
  AdminUsersIndexApiAdminUsersGetParams,
  AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams,
  AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams,
  AssignRolePayload,
  GrantPermissionPayload,
  HTTPValidationError,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Admin.Users.Index
 */
export const adminUsersIndexApiAdminUsersGet = (
  params?: MaybeRef<AdminUsersIndexApiAdminUsersGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminUserListOut>(
    { url: `/api/admin/users`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getAdminUsersIndexApiAdminUsersGetQueryKey = (
  params?: MaybeRef<AdminUsersIndexApiAdminUsersGetParams>,
) => {
  return ['api', 'admin', 'users', ...(params ? [params] : [])] as const
}

export const getAdminUsersIndexApiAdminUsersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminUsersIndexApiAdminUsersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminUsersIndexApiAdminUsersGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>> = ({
    signal,
  }) => adminUsersIndexApiAdminUsersGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>,
    TError,
    TData
  >
}

export type AdminUsersIndexApiAdminUsersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>
>
export type AdminUsersIndexApiAdminUsersGetQueryError = HTTPValidationError

/**
 * @summary Admin.Users.Index
 */

export function useAdminUsersIndexApiAdminUsersGet<
  TData = Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminUsersIndexApiAdminUsersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminUsersIndexApiAdminUsersGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminUsersIndexApiAdminUsersGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Users.Show
 */
export const adminUsersShowApiAdminUsersUserIdGet = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}`, method: 'GET', signal },
    options,
  )
}

export const getAdminUsersShowApiAdminUsersUserIdGetQueryKey = (userId?: MaybeRef<number>) => {
  return ['api', 'admin', 'users', userId] as const
}

export const getAdminUsersShowApiAdminUsersUserIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminUsersShowApiAdminUsersUserIdGetQueryKey(userId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>
  > = ({ signal }) => adminUsersShowApiAdminUsersUserIdGet(userId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(userId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>,
    TError,
    TData
  >
}

export type AdminUsersShowApiAdminUsersUserIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>
>
export type AdminUsersShowApiAdminUsersUserIdGetQueryError = HTTPValidationError

/**
 * @summary Admin.Users.Show
 */

export function useAdminUsersShowApiAdminUsersUserIdGet<
  TData = Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminUsersShowApiAdminUsersUserIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminUsersShowApiAdminUsersUserIdGetQueryOptions(userId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Users.Destroy
 */
export const adminUsersDestroyApiAdminUsersUserIdDelete = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<unknown>({ url: `/api/admin/users/${userId}`, method: 'DELETE' }, options)
}

export const getAdminUsersDestroyApiAdminUsersUserIdDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersDestroyApiAdminUsersUserIdDelete>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersDestroyApiAdminUsersUserIdDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['adminUsersDestroyApiAdminUsersUserIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersDestroyApiAdminUsersUserIdDelete>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return adminUsersDestroyApiAdminUsersUserIdDelete(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersDestroyApiAdminUsersUserIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersDestroyApiAdminUsersUserIdDelete>>
>

export type AdminUsersDestroyApiAdminUsersUserIdDeleteMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Destroy
 */
export const useAdminUsersDestroyApiAdminUsersUserIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersDestroyApiAdminUsersUserIdDelete>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersDestroyApiAdminUsersUserIdDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions = getAdminUsersDestroyApiAdminUsersUserIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Force Destroy
 */
export const adminUsersForceDestroyApiAdminUsersUserIdForceDelete = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<unknown>({ url: `/api/admin/users/${userId}/force`, method: 'DELETE' }, options)
}

export const getAdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['adminUsersForceDestroyApiAdminUsersUserIdForceDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return adminUsersForceDestroyApiAdminUsersUserIdForceDelete(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersForceDestroyApiAdminUsersUserIdForceDelete>>
>

export type AdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Force Destroy
 */
export const useAdminUsersForceDestroyApiAdminUsersUserIdForceDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getAdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Restore
 */
export const adminUsersRestoreApiAdminUsersUserIdRestorePost = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/restore`, method: 'POST', signal },
    options,
  )
}

export const getAdminUsersRestoreApiAdminUsersUserIdRestorePostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersRestoreApiAdminUsersUserIdRestorePost>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersRestoreApiAdminUsersUserIdRestorePost>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['adminUsersRestoreApiAdminUsersUserIdRestorePost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersRestoreApiAdminUsersUserIdRestorePost>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return adminUsersRestoreApiAdminUsersUserIdRestorePost(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersRestoreApiAdminUsersUserIdRestorePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersRestoreApiAdminUsersUserIdRestorePost>>
>

export type AdminUsersRestoreApiAdminUsersUserIdRestorePostMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Restore
 */
export const useAdminUsersRestoreApiAdminUsersUserIdRestorePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersRestoreApiAdminUsersUserIdRestorePost>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersRestoreApiAdminUsersUserIdRestorePost>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions = getAdminUsersRestoreApiAdminUsersUserIdRestorePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Suspend
 */
export const adminUsersSuspendApiAdminUsersUserIdSuspendPatch = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/suspend`, method: 'PATCH' },
    options,
  )
}

export const getAdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['adminUsersSuspendApiAdminUsersUserIdSuspendPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return adminUsersSuspendApiAdminUsersUserIdSuspendPatch(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersSuspendApiAdminUsersUserIdSuspendPatch>>
>

export type AdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Suspend
 */
export const useAdminUsersSuspendApiAdminUsersUserIdSuspendPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getAdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Unsuspend
 */
export const adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/unsuspend`, method: 'PATCH' },
    options,
  )
}

export const getAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>
>

export type AdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Unsuspend
 */
export const useAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Roles.Assign
 */
export const adminUsersRolesAssignApiAdminUsersUserIdRolesPost = (
  userId: MaybeRef<number>,
  assignRolePayload: MaybeRef<AssignRolePayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)
  assignRolePayload = unref(assignRolePayload)

  return request<AdminUserWrapperOut>(
    {
      url: `/api/admin/users/${userId}/roles`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assignRolePayload,
      signal,
    },
    options,
  )
}

export const getAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
    TError,
    { userId: number; data: AssignRolePayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
  TError,
  { userId: number; data: AssignRolePayload },
  TContext
> => {
  const mutationKey = ['adminUsersRolesAssignApiAdminUsersUserIdRolesPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
    { userId: number; data: AssignRolePayload }
  > = (props) => {
    const { userId, data } = props ?? {}

    return adminUsersRolesAssignApiAdminUsersUserIdRolesPost(userId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersRolesAssignApiAdminUsersUserIdRolesPost>>
>
export type AdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationBody = AssignRolePayload
export type AdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Roles.Assign
 */
export const useAdminUsersRolesAssignApiAdminUsersUserIdRolesPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
      TError,
      { userId: number; data: AssignRolePayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
  TError,
  { userId: number; data: AssignRolePayload },
  TContext
> => {
  const mutationOptions =
    getAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Roles.Revoke
 */
export const adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete = (
  userId: MaybeRef<number>,
  params: MaybeRef<AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)
  params = unref(params)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/roles`, method: 'DELETE', params: unref(params) },
    options,
  )
}

export const getAdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete>>,
    TError,
    { userId: number; params: AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete>>,
  TError,
  { userId: number; params: AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams },
  TContext
> => {
  const mutationKey = ['adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete>>,
    { userId: number; params: AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams }
  > = (props) => {
    const { userId, params } = props ?? {}

    return adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete(userId, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete>>
>

export type AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteMutationError = HTTPValidationError

/**
 * @summary Admin.Users.Roles.Revoke
 */
export const useAdminUsersRolesRevokeApiAdminUsersUserIdRolesDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete>>,
      TError,
      { userId: number; params: AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersRolesRevokeApiAdminUsersUserIdRolesDelete>>,
  TError,
  { userId: number; params: AdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteParams },
  TContext
> => {
  const mutationOptions =
    getAdminUsersRolesRevokeApiAdminUsersUserIdRolesDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Permissions.Grant
 */
export const adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost = (
  userId: MaybeRef<number>,
  grantPermissionPayload: MaybeRef<GrantPermissionPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)
  grantPermissionPayload = unref(grantPermissionPayload)

  return request<AdminUserWrapperOut>(
    {
      url: `/api/admin/users/${userId}/permissions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: grantPermissionPayload,
      signal,
    },
    options,
  )
}

export const getAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
    TError,
    { userId: number; data: GrantPermissionPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
  TError,
  { userId: number; data: GrantPermissionPayload },
  TContext
> => {
  const mutationKey = ['adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
    { userId: number; data: GrantPermissionPayload }
  > = (props) => {
    const { userId, data } = props ?? {}

    return adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost(
      userId,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>
  >
export type AdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationBody =
  GrantPermissionPayload
export type AdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationError =
  HTTPValidationError

/**
 * @summary Admin.Users.Permissions.Grant
 */
export const useAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
      TError,
      { userId: number; data: GrantPermissionPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
  TError,
  { userId: number; data: GrantPermissionPayload },
  TContext
> => {
  const mutationOptions =
    getAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Admin.Users.Permissions.Revoke
 */
export const adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete = (
  userId: MaybeRef<number>,
  params: MaybeRef<AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)
  params = unref(params)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/permissions`, method: 'DELETE', params: unref(params) },
    options,
  )
}

export const getAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete>>,
    TError,
    {
      userId: number
      params: AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams
    },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete>>,
  TError,
  { userId: number; params: AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams },
  TContext
> => {
  const mutationKey = ['adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete>>,
    {
      userId: number
      params: AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams
    }
  > = (props) => {
    const { userId, params } = props ?? {}

    return adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete(
      userId,
      params,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete>>
  >

export type AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteMutationError =
  HTTPValidationError

/**
 * @summary Admin.Users.Permissions.Revoke
 */
export const useAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete>>,
      TError,
      {
        userId: number
        params: AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams
      },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDelete>>,
  TError,
  { userId: number; params: AdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteParams },
  TContext
> => {
  const mutationOptions =
    getAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
