/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type {
  ApiTestCatalogRefreshApiTestCatalogRefreshPost200,
  ApiTestSeedCatalogApiTestSeedCatalogPost200,
  HealthzHealthzGet200,
} from '../schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Healthz
 */
export const healthzHealthzGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<HealthzHealthzGet200>({ url: `/healthz`, method: 'GET', signal }, options)
}

export const getHealthzHealthzGetQueryKey = () => {
  return ['healthz'] as const
}

export const getHealthzHealthzGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getHealthzHealthzGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthzHealthzGet>>> = ({ signal }) =>
    healthzHealthzGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthzHealthzGet>>,
    TError,
    TData
  >
}

export type HealthzHealthzGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthzHealthzGet>>
>
export type HealthzHealthzGetQueryError = unknown

/**
 * @summary Healthz
 */

export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthzHealthzGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Test-only seeder trigger. Disabled in production.
 *
 * Intentionally has no DB_TX middleware so we can run seeder inserts
 * in one transaction and REFRESH MATERIALIZED VIEW in a separate transaction
 * after the data is committed (the view query cannot see uncommitted rows).
 * @summary Api.Test.Seed.Catalog
 */
export const apiTestSeedCatalogApiTestSeedCatalogPost = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<ApiTestSeedCatalogApiTestSeedCatalogPost200>(
    { url: `/api/test/seed/catalog`, method: 'POST', signal },
    options,
  )
}

export const getApiTestSeedCatalogApiTestSeedCatalogPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['apiTestSeedCatalogApiTestSeedCatalogPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
    void
  > = () => {
    return apiTestSeedCatalogApiTestSeedCatalogPost(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiTestSeedCatalogApiTestSeedCatalogPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>
>

export type ApiTestSeedCatalogApiTestSeedCatalogPostMutationError = unknown

/**
 * @summary Api.Test.Seed.Catalog
 */
export const useApiTestSeedCatalogApiTestSeedCatalogPost = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiTestSeedCatalogApiTestSeedCatalogPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getApiTestSeedCatalogApiTestSeedCatalogPostMutationOptions(options),
    queryClient,
  )
}
/**
 * Trigger an immediate refresh of the products_catalog materialized view.
 *
 * Used by ``make seed`` after ``arvel db:seed`` commits, since the refresh
 * must run in a separate transaction to see the newly committed rows.
 * Disabled in production.
 * @summary Api.Test.Catalog.Refresh
 */
export const apiTestCatalogRefreshApiTestCatalogRefreshPost = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<ApiTestCatalogRefreshApiTestCatalogRefreshPost200>(
    { url: `/api/test/catalog/refresh`, method: 'POST', signal },
    options,
  )
}

export const getApiTestCatalogRefreshApiTestCatalogRefreshPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiTestCatalogRefreshApiTestCatalogRefreshPost>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiTestCatalogRefreshApiTestCatalogRefreshPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['apiTestCatalogRefreshApiTestCatalogRefreshPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiTestCatalogRefreshApiTestCatalogRefreshPost>>,
    void
  > = () => {
    return apiTestCatalogRefreshApiTestCatalogRefreshPost(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiTestCatalogRefreshApiTestCatalogRefreshPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiTestCatalogRefreshApiTestCatalogRefreshPost>>
>

export type ApiTestCatalogRefreshApiTestCatalogRefreshPostMutationError = unknown

/**
 * @summary Api.Test.Catalog.Refresh
 */
export const useApiTestCatalogRefreshApiTestCatalogRefreshPost = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiTestCatalogRefreshApiTestCatalogRefreshPost>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiTestCatalogRefreshApiTestCatalogRefreshPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getApiTestCatalogRefreshApiTestCatalogRefreshPostMutationOptions(options),
    queryClient,
  )
}
