/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AuthEnvelopeUserResource,
  HTTPValidationError,
  LoginRequest,
  LoginResponse,
  MeOut,
  RegisterRequest,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * ``POST /auth/login`` — issue JWT + set refresh/CSRF cookie pair.
 * @summary Auth.Login
 */
export const authLoginApiAuthLoginPost = (
  loginRequest: MaybeRef<LoginRequest>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  loginRequest = unref(loginRequest)

  return request<LoginResponse>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequest,
      signal,
    },
    options,
  )
}

export const getAuthLoginApiAuthLoginPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLoginApiAuthLoginPost>>,
    TError,
    { data: LoginRequest },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLoginApiAuthLoginPost>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationKey = ['authLoginApiAuthLoginPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLoginApiAuthLoginPost>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {}

    return authLoginApiAuthLoginPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthLoginApiAuthLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLoginApiAuthLoginPost>>
>
export type AuthLoginApiAuthLoginPostMutationBody = LoginRequest
export type AuthLoginApiAuthLoginPostMutationError = HTTPValidationError

/**
 * @summary Auth.Login
 */
export const useAuthLoginApiAuthLoginPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLoginApiAuthLoginPost>>,
      TError,
      { data: LoginRequest },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof authLoginApiAuthLoginPost>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationOptions = getAuthLoginApiAuthLoginPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * ``POST /auth/register`` — create a user and queue a verification email.
 * @summary Auth.Register
 */
export const authRegisterApiAuthRegisterPost = (
  registerRequest: MaybeRef<RegisterRequest>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  registerRequest = unref(registerRequest)

  return request<AuthEnvelopeUserResource>(
    {
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequest,
      signal,
    },
    options,
  )
}

export const getAuthRegisterApiAuthRegisterPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegisterApiAuthRegisterPost>>,
    TError,
    { data: RegisterRequest },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegisterApiAuthRegisterPost>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationKey = ['authRegisterApiAuthRegisterPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegisterApiAuthRegisterPost>>,
    { data: RegisterRequest }
  > = (props) => {
    const { data } = props ?? {}

    return authRegisterApiAuthRegisterPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthRegisterApiAuthRegisterPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRegisterApiAuthRegisterPost>>
>
export type AuthRegisterApiAuthRegisterPostMutationBody = RegisterRequest
export type AuthRegisterApiAuthRegisterPostMutationError = HTTPValidationError

/**
 * @summary Auth.Register
 */
export const useAuthRegisterApiAuthRegisterPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegisterApiAuthRegisterPost>>,
      TError,
      { data: RegisterRequest },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof authRegisterApiAuthRegisterPost>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationOptions = getAuthRegisterApiAuthRegisterPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Auth.Me
 */
export const authMeApiAuthMeGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<MeOut>({ url: `/api/auth/me`, method: 'GET', signal }, options)
}

export const getAuthMeApiAuthMeGetQueryKey = () => {
  return ['api', 'auth', 'me'] as const
}

export const getAuthMeApiAuthMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof authMeApiAuthMeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeApiAuthMeGet>>, TError, TData>>
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAuthMeApiAuthMeGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeApiAuthMeGet>>> = ({ signal }) =>
    authMeApiAuthMeGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authMeApiAuthMeGet>>,
    TError,
    TData
  >
}

export type AuthMeApiAuthMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof authMeApiAuthMeGet>>
>
export type AuthMeApiAuthMeGetQueryError = unknown

/**
 * @summary Auth.Me
 */

export function useAuthMeApiAuthMeGet<
  TData = Awaited<ReturnType<typeof authMeApiAuthMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeApiAuthMeGet>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthMeApiAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
