"""StorageDisk protocol — implemented by all storage drivers."""

from __future__ import annotations

from typing import BinaryIO, Protocol


class StorageDisk(Protocol):
    """Async storage disk interface."""

    async def exists(self, path: str) -> bool: ...
    async def get(self, path: str) -> bytes: ...
    async def put(self, path: str, contents: bytes | str | BinaryIO) -> bool: ...
    async def delete(self, path: str) -> bool: ...
    async def list(self, directory: str = "") -> list[str]: ...
    def url(self, path: str) -> str: ...
    def temporary_url(self, path: str, expiry: int) -> str: ...


__all__ = ["StorageDisk"]
