/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiCategoriesShowApiCategoriesSlugGetParams,
  ApiErrorOut,
  ApiProductsIndexApiProductsGetParams,
  ApiProductsShowApiProductsSlugGetParams,
  ApiSearchApiSearchGetParams,
  ProductDetailOut,
  ProductListOut,
  SearchOut,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Products.Index
 */
export const apiProductsIndexApiProductsGet = (
  params?: MaybeRef<ApiProductsIndexApiProductsGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<ProductListOut>(
    { url: `/api/products`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiProductsIndexApiProductsGetQueryKey = (
  params?: MaybeRef<ApiProductsIndexApiProductsGetParams>,
) => {
  return ['api', 'products', ...(params ? [params] : [])] as const
}

export const getApiProductsIndexApiProductsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiProductsIndexApiProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiProductsIndexApiProductsGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>> = ({
    signal,
  }) => apiProductsIndexApiProductsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>,
    TError,
    TData
  >
}

export type ApiProductsIndexApiProductsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>
>
export type ApiProductsIndexApiProductsGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Products.Index
 */

export function useApiProductsIndexApiProductsGet<
  TData = Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiProductsIndexApiProductsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiProductsIndexApiProductsGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiProductsIndexApiProductsGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Products.Show
 */
export const apiProductsShowApiProductsSlugGet = (
  slug: MaybeRef<string>,
  params?: MaybeRef<ApiProductsShowApiProductsSlugGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  slug = unref(slug)
  params = unref(params)

  return request<ProductDetailOut>(
    { url: `/api/products/${slug}`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiProductsShowApiProductsSlugGetQueryKey = (
  slug?: MaybeRef<string>,
  params?: MaybeRef<ApiProductsShowApiProductsSlugGetParams>,
) => {
  return ['api', 'products', slug, ...(params ? [params] : [])] as const
}

export const getApiProductsShowApiProductsSlugGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<ApiProductsShowApiProductsSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiProductsShowApiProductsSlugGetQueryKey(slug, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>> = ({
    signal,
  }) => apiProductsShowApiProductsSlugGet(slug, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(slug)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>, TError, TData>
}

export type ApiProductsShowApiProductsSlugGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>
>
export type ApiProductsShowApiProductsSlugGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Products.Show
 */

export function useApiProductsShowApiProductsSlugGet<
  TData = Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<ApiProductsShowApiProductsSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiProductsShowApiProductsSlugGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiProductsShowApiProductsSlugGetQueryOptions(slug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Categories.Show
 */
export const apiCategoriesShowApiCategoriesSlugGet = (
  slug: MaybeRef<string>,
  params?: MaybeRef<ApiCategoriesShowApiCategoriesSlugGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  slug = unref(slug)
  params = unref(params)

  return request<ProductListOut>(
    { url: `/api/categories/${slug}`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiCategoriesShowApiCategoriesSlugGetQueryKey = (
  slug?: MaybeRef<string>,
  params?: MaybeRef<ApiCategoriesShowApiCategoriesSlugGetParams>,
) => {
  return ['api', 'categories', slug, ...(params ? [params] : [])] as const
}

export const getApiCategoriesShowApiCategoriesSlugGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<ApiCategoriesShowApiCategoriesSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiCategoriesShowApiCategoriesSlugGetQueryKey(slug, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>
  > = ({ signal }) => apiCategoriesShowApiCategoriesSlugGet(slug, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(slug)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>,
    TError,
    TData
  >
}

export type ApiCategoriesShowApiCategoriesSlugGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>
>
export type ApiCategoriesShowApiCategoriesSlugGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Categories.Show
 */

export function useApiCategoriesShowApiCategoriesSlugGet<
  TData = Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  slug: MaybeRef<string>,
  params?: MaybeRef<ApiCategoriesShowApiCategoriesSlugGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiCategoriesShowApiCategoriesSlugGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiCategoriesShowApiCategoriesSlugGetQueryOptions(slug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Search
 */
export const apiSearchApiSearchGet = (
  params: MaybeRef<ApiSearchApiSearchGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<SearchOut>(
    { url: `/api/search`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiSearchApiSearchGetQueryKey = (
  params?: MaybeRef<ApiSearchApiSearchGetParams>,
) => {
  return ['api', 'search', ...(params ? [params] : [])] as const
}

export const getApiSearchApiSearchGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiSearchApiSearchGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params: MaybeRef<ApiSearchApiSearchGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiSearchApiSearchGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiSearchApiSearchGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiSearchApiSearchGet>>> = ({ signal }) =>
    apiSearchApiSearchGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiSearchApiSearchGet>>,
    TError,
    TData
  >
}

export type ApiSearchApiSearchGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiSearchApiSearchGet>>
>
export type ApiSearchApiSearchGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Search
 */

export function useApiSearchApiSearchGet<
  TData = Awaited<ReturnType<typeof apiSearchApiSearchGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params: MaybeRef<ApiSearchApiSearchGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiSearchApiSearchGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiSearchApiSearchGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
