/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type { PermissionsListOut, RolesListOut } from '../schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Admin.Roles.Index
 */
export const adminRolesIndexApiAdminRolesGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<RolesListOut>({ url: `/api/admin/roles`, method: 'GET', signal }, options)
}

export const getAdminRolesIndexApiAdminRolesGetQueryKey = () => {
  return ['api', 'admin', 'roles'] as const
}

export const getAdminRolesIndexApiAdminRolesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>, TError, TData>
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminRolesIndexApiAdminRolesGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>> = ({
    signal,
  }) => adminRolesIndexApiAdminRolesGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>,
    TError,
    TData
  >
}

export type AdminRolesIndexApiAdminRolesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>
>
export type AdminRolesIndexApiAdminRolesGetQueryError = unknown

/**
 * @summary Admin.Roles.Index
 */

export function useAdminRolesIndexApiAdminRolesGet<
  TData = Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminRolesIndexApiAdminRolesGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminRolesIndexApiAdminRolesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Roles.Permissions.Index
 */
export const adminRolesPermissionsIndexApiAdminRolesPermissionsGet = (
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  return request<PermissionsListOut>(
    { url: `/api/admin/roles/permissions`, method: 'GET', signal },
    options,
  )
}

export const getAdminRolesPermissionsIndexApiAdminRolesPermissionsGetQueryKey = () => {
  return ['api', 'admin', 'roles', 'permissions'] as const
}

export const getAdminRolesPermissionsIndexApiAdminRolesPermissionsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminRolesPermissionsIndexApiAdminRolesPermissionsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>
  > = ({ signal }) => adminRolesPermissionsIndexApiAdminRolesPermissionsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>,
    TError,
    TData
  >
}

export type AdminRolesPermissionsIndexApiAdminRolesPermissionsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>
>
export type AdminRolesPermissionsIndexApiAdminRolesPermissionsGetQueryError = unknown

/**
 * @summary Admin.Roles.Permissions.Index
 */

export function useAdminRolesPermissionsIndexApiAdminRolesPermissionsGet<
  TData = Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminRolesPermissionsIndexApiAdminRolesPermissionsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminRolesPermissionsIndexApiAdminRolesPermissionsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
