/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminVendorListOut,
  AdminVendorWrapperOut,
  ApiAdminVendorsIndexApiAdminVendorsGetParams,
  ApiErrorOut,
  CreateVendorPayload,
  UpdateVendorPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Admin.Vendors.Index
 */
export const apiAdminVendorsIndexApiAdminVendorsGet = (
  params?: MaybeRef<ApiAdminVendorsIndexApiAdminVendorsGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminVendorListOut>(
    { url: `/api/admin/vendors`, method: 'GET', params, signal },
    options,
  )
}

export const getApiAdminVendorsIndexApiAdminVendorsGetQueryKey = (
  params?: MaybeRef<ApiAdminVendorsIndexApiAdminVendorsGetParams>,
) => {
  return ['api', 'admin', 'vendors', params] as const
}

export const getApiAdminVendorsIndexApiAdminVendorsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminVendorsIndexApiAdminVendorsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminVendorsIndexApiAdminVendorsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>
  > = ({ signal }) => apiAdminVendorsIndexApiAdminVendorsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>,
    TError,
    TData
  >
}

export type ApiAdminVendorsIndexApiAdminVendorsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>
>
export type ApiAdminVendorsIndexApiAdminVendorsGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Index
 */

export function useApiAdminVendorsIndexApiAdminVendorsGet<
  TData = Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminVendorsIndexApiAdminVendorsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminVendorsIndexApiAdminVendorsGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminVendorsIndexApiAdminVendorsGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Vendors.Store
 */
export const apiAdminVendorsStoreApiAdminVendorsPost = (
  createVendorPayload: MaybeRef<CreateVendorPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  createVendorPayload = unref(createVendorPayload)

  return request<AdminVendorWrapperOut>(
    {
      url: `/api/admin/vendors`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createVendorPayload,
      signal,
    },
    options,
  )
}

export const getApiAdminVendorsStoreApiAdminVendorsPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsStoreApiAdminVendorsPost>>,
    TError,
    { data: CreateVendorPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsStoreApiAdminVendorsPost>>,
  TError,
  { data: CreateVendorPayload },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsStoreApiAdminVendorsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsStoreApiAdminVendorsPost>>,
    { data: CreateVendorPayload }
  > = (props) => {
    const { data } = props ?? {}

    return apiAdminVendorsStoreApiAdminVendorsPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsStoreApiAdminVendorsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsStoreApiAdminVendorsPost>>
>
export type ApiAdminVendorsStoreApiAdminVendorsPostMutationBody = CreateVendorPayload
export type ApiAdminVendorsStoreApiAdminVendorsPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Store
 */
export const useApiAdminVendorsStoreApiAdminVendorsPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsStoreApiAdminVendorsPost>>,
      TError,
      { data: CreateVendorPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsStoreApiAdminVendorsPost>>,
  TError,
  { data: CreateVendorPayload },
  TContext
> => {
  const mutationOptions = getApiAdminVendorsStoreApiAdminVendorsPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Vendors.Show
 */
export const apiAdminVendorsShowApiAdminVendorsVendorIdGet = (
  vendorId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  vendorId = unref(vendorId)

  return request<AdminVendorWrapperOut>(
    { url: `/api/admin/vendors/${vendorId}`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminVendorsShowApiAdminVendorsVendorIdGetQueryKey = (
  vendorId?: MaybeRef<string>,
) => {
  return ['api', 'admin', 'vendors', vendorId] as const
}

export const getApiAdminVendorsShowApiAdminVendorsVendorIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  vendorId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminVendorsShowApiAdminVendorsVendorIdGetQueryKey(vendorId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>
  > = ({ signal }) =>
    apiAdminVendorsShowApiAdminVendorsVendorIdGet(vendorId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(vendorId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>,
    TError,
    TData
  >
}

export type ApiAdminVendorsShowApiAdminVendorsVendorIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>
>
export type ApiAdminVendorsShowApiAdminVendorsVendorIdGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Show
 */

export function useApiAdminVendorsShowApiAdminVendorsVendorIdGet<
  TData = Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  vendorId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminVendorsShowApiAdminVendorsVendorIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminVendorsShowApiAdminVendorsVendorIdGetQueryOptions(
    vendorId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Vendors.Update
 */
export const apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch = (
  vendorId: MaybeRef<string>,
  updateVendorPayload: MaybeRef<UpdateVendorPayload>,
  options?: SecondParameter<typeof request>,
) => {
  vendorId = unref(vendorId)
  updateVendorPayload = unref(updateVendorPayload)

  return request<AdminVendorWrapperOut>(
    {
      url: `/api/admin/vendors/${vendorId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateVendorPayload,
    },
    options,
  )
}

export const getApiAdminVendorsUpdateApiAdminVendorsVendorIdPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch>>,
    TError,
    { vendorId: string; data: UpdateVendorPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch>>,
  TError,
  { vendorId: string; data: UpdateVendorPayload },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch>>,
    { vendorId: string; data: UpdateVendorPayload }
  > = (props) => {
    const { vendorId, data } = props ?? {}

    return apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch(vendorId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsUpdateApiAdminVendorsVendorIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch>>
>
export type ApiAdminVendorsUpdateApiAdminVendorsVendorIdPatchMutationBody = UpdateVendorPayload
export type ApiAdminVendorsUpdateApiAdminVendorsVendorIdPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Update
 */
export const useApiAdminVendorsUpdateApiAdminVendorsVendorIdPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch>>,
      TError,
      { vendorId: string; data: UpdateVendorPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsUpdateApiAdminVendorsVendorIdPatch>>,
  TError,
  { vendorId: string; data: UpdateVendorPayload },
  TContext
> => {
  const mutationOptions =
    getApiAdminVendorsUpdateApiAdminVendorsVendorIdPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Vendors.Destroy
 */
export const apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete = (
  vendorId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  vendorId = unref(vendorId)

  return request<void>({ url: `/api/admin/vendors/${vendorId}`, method: 'DELETE' }, options)
}

export const getApiAdminVendorsDestroyApiAdminVendorsVendorIdDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete>>,
    TError,
    { vendorId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete>>,
    { vendorId: string }
  > = (props) => {
    const { vendorId } = props ?? {}

    return apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete(vendorId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsDestroyApiAdminVendorsVendorIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete>>
>

export type ApiAdminVendorsDestroyApiAdminVendorsVendorIdDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Destroy
 */
export const useApiAdminVendorsDestroyApiAdminVendorsVendorIdDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete>>,
      TError,
      { vendorId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsDestroyApiAdminVendorsVendorIdDelete>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminVendorsDestroyApiAdminVendorsVendorIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Vendors.Publish
 */
export const apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch = (
  vendorId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  vendorId = unref(vendorId)

  return request<AdminVendorWrapperOut>(
    { url: `/api/admin/vendors/${vendorId}/publish`, method: 'POST' },
    options,
  )
}

export const getApiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch>>,
    TError,
    { vendorId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch>>,
    { vendorId: string }
  > = (props) => {
    const { vendorId } = props ?? {}

    return apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch(vendorId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch>>
>

export type ApiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Publish
 */
export const useApiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch>>,
      TError,
      { vendorId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatch>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminVendorsPublishApiAdminVendorsVendorIdPublishPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Vendors.Unpublish
 */
export const apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch = (
  vendorId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  vendorId = unref(vendorId)

  return request<AdminVendorWrapperOut>(
    { url: `/api/admin/vendors/${vendorId}/unpublish`, method: 'POST' },
    options,
  )
}

export const getApiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch>>,
    TError,
    { vendorId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch>>,
    { vendorId: string }
  > = (props) => {
    const { vendorId } = props ?? {}

    return apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch(vendorId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch>>
  >

export type ApiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Unpublish
 */
export const useApiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch>>,
      TError,
      { vendorId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatch>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminVendorsUnpublishApiAdminVendorsVendorIdUnpublishPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Vendors.Force-Destroy
 */
export const apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete = (
  vendorId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  vendorId = unref(vendorId)

  return request<void>({ url: `/api/admin/vendors/${vendorId}/force`, method: 'DELETE' }, options)
}

export const getApiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete>>,
    TError,
    { vendorId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete>>,
    { vendorId: string }
  > = (props) => {
    const { vendorId } = props ?? {}

    return apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete(vendorId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete>>
  >

export type ApiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Force-Destroy
 */
export const useApiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete>>,
      TError,
      { vendorId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDelete>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminVendorsForceDestroyApiAdminVendorsVendorIdForceDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Vendors.Restore
 */
export const apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost = (
  vendorId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  vendorId = unref(vendorId)

  return request<AdminVendorWrapperOut>(
    { url: `/api/admin/vendors/${vendorId}/restore`, method: 'POST', signal },
    options,
  )
}

export const getApiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost>>,
    TError,
    { vendorId: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationKey = ['apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost>>,
    { vendorId: string }
  > = (props) => {
    const { vendorId } = props ?? {}

    return apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost(vendorId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost>>
>

export type ApiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Vendors.Restore
 */
export const useApiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost>>,
      TError,
      { vendorId: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePost>>,
  TError,
  { vendorId: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminVendorsRestoreApiAdminVendorsVendorIdRestorePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
