/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminUserListOut,
  AdminUserWrapperOut,
  ApiAdminUsersIndexApiAdminUsersGetParams,
  ApiErrorOut,
  AssignRolePayload,
  GrantPermissionPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Api.Admin.Users.Index
 */
export const apiAdminUsersIndexApiAdminUsersGet = (
  params?: MaybeRef<ApiAdminUsersIndexApiAdminUsersGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminUserListOut>(
    { url: `/api/admin/users`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getApiAdminUsersIndexApiAdminUsersGetQueryKey = (
  params?: MaybeRef<ApiAdminUsersIndexApiAdminUsersGetParams>,
) => {
  return ['api', 'admin', 'users', ...(params ? [params] : [])] as const
}

export const getApiAdminUsersIndexApiAdminUsersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminUsersIndexApiAdminUsersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminUsersIndexApiAdminUsersGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>> = ({
    signal,
  }) => apiAdminUsersIndexApiAdminUsersGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>,
    TError,
    TData
  >
}

export type ApiAdminUsersIndexApiAdminUsersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>
>
export type ApiAdminUsersIndexApiAdminUsersGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Index
 */

export function useApiAdminUsersIndexApiAdminUsersGet<
  TData = Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  params?: MaybeRef<ApiAdminUsersIndexApiAdminUsersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof apiAdminUsersIndexApiAdminUsersGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminUsersIndexApiAdminUsersGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Users.Show
 */
export const apiAdminUsersShowApiAdminUsersUserIdGet = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}`, method: 'GET', signal },
    options,
  )
}

export const getApiAdminUsersShowApiAdminUsersUserIdGetQueryKey = (userId?: MaybeRef<number>) => {
  return ['api', 'admin', 'users', userId] as const
}

export const getApiAdminUsersShowApiAdminUsersUserIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  userId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getApiAdminUsersShowApiAdminUsersUserIdGetQueryKey(userId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>
  > = ({ signal }) => apiAdminUsersShowApiAdminUsersUserIdGet(userId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(userId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>,
    TError,
    TData
  >
}

export type ApiAdminUsersShowApiAdminUsersUserIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>
>
export type ApiAdminUsersShowApiAdminUsersUserIdGetQueryError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Show
 */

export function useApiAdminUsersShowApiAdminUsersUserIdGet<
  TData = Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>,
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
>(
  userId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiAdminUsersShowApiAdminUsersUserIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApiAdminUsersShowApiAdminUsersUserIdGetQueryOptions(userId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Api.Admin.Users.Destroy
 */
export const apiAdminUsersDestroyApiAdminUsersUserIdDelete = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<void>({ url: `/api/admin/users/${userId}`, method: 'DELETE' }, options)
}

export const getApiAdminUsersDestroyApiAdminUsersUserIdDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersDestroyApiAdminUsersUserIdDelete>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersDestroyApiAdminUsersUserIdDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['apiAdminUsersDestroyApiAdminUsersUserIdDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersDestroyApiAdminUsersUserIdDelete>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return apiAdminUsersDestroyApiAdminUsersUserIdDelete(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersDestroyApiAdminUsersUserIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersDestroyApiAdminUsersUserIdDelete>>
>

export type ApiAdminUsersDestroyApiAdminUsersUserIdDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Destroy
 */
export const useApiAdminUsersDestroyApiAdminUsersUserIdDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersDestroyApiAdminUsersUserIdDelete>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersDestroyApiAdminUsersUserIdDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions = getApiAdminUsersDestroyApiAdminUsersUserIdDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Force-Destroy
 */
export const apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<void>({ url: `/api/admin/users/${userId}/force`, method: 'DELETE' }, options)
}

export const getApiAdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete>>
>

export type ApiAdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Force-Destroy
 */
export const useApiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersForceDestroyApiAdminUsersUserIdForceDelete>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersForceDestroyApiAdminUsersUserIdForceDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Suspend
 */
export const apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/suspend`, method: 'PATCH' },
    options,
  )
}

export const getApiAdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch>>
>

export type ApiAdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Suspend
 */
export const useApiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersSuspendApiAdminUsersUserIdSuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersSuspendApiAdminUsersUserIdSuspendPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Unsuspend
 */
export const apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/unsuspend`, method: 'PATCH' },
    options,
  )
}

export const getApiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>
>

export type ApiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Unsuspend
 */
export const useApiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatch>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersUnsuspendApiAdminUsersUserIdUnsuspendPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Restore
 */
export const apiAdminUsersRestoreApiAdminUsersUserIdRestorePost = (
  userId: MaybeRef<number>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/restore`, method: 'POST', signal },
    options,
  )
}

export const getApiAdminUsersRestoreApiAdminUsersUserIdRestorePostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersRestoreApiAdminUsersUserIdRestorePost>>,
    TError,
    { userId: number },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersRestoreApiAdminUsersUserIdRestorePost>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ['apiAdminUsersRestoreApiAdminUsersUserIdRestorePost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersRestoreApiAdminUsersUserIdRestorePost>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {}

    return apiAdminUsersRestoreApiAdminUsersUserIdRestorePost(userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersRestoreApiAdminUsersUserIdRestorePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersRestoreApiAdminUsersUserIdRestorePost>>
>

export type ApiAdminUsersRestoreApiAdminUsersUserIdRestorePostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Restore
 */
export const useApiAdminUsersRestoreApiAdminUsersUserIdRestorePost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersRestoreApiAdminUsersUserIdRestorePost>>,
      TError,
      { userId: number },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersRestoreApiAdminUsersUserIdRestorePost>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersRestoreApiAdminUsersUserIdRestorePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Roles.Assign
 */
export const apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost = (
  userId: MaybeRef<number>,
  assignRolePayload: MaybeRef<AssignRolePayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)
  assignRolePayload = unref(assignRolePayload)

  return request<AdminUserWrapperOut>(
    {
      url: `/api/admin/users/${userId}/roles`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assignRolePayload,
      signal,
    },
    options,
  )
}

export const getApiAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
    TError,
    { userId: number; data: AssignRolePayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
  TError,
  { userId: number; data: AssignRolePayload },
  TContext
> => {
  const mutationKey = ['apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
    { userId: number; data: AssignRolePayload }
  > = (props) => {
    const { userId, data } = props ?? {}

    return apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost(userId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost>>
>
export type ApiAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationBody = AssignRolePayload
export type ApiAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Roles.Assign
 */
export const useApiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
      TError,
      { userId: number; data: AssignRolePayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersRolesAssignApiAdminUsersUserIdRolesPost>>,
  TError,
  { userId: number; data: AssignRolePayload },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersRolesAssignApiAdminUsersUserIdRolesPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Roles.Revoke
 */
export const apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete = (
  userId: MaybeRef<number>,
  roleName: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)
  roleName = unref(roleName)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/roles/${roleName}`, method: 'DELETE' },
    options,
  )
}

export const getApiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDeleteMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete>>,
    TError,
    { userId: number; roleName: string },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete>>,
  TError,
  { userId: number; roleName: string },
  TContext
> => {
  const mutationKey = ['apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete>>,
    { userId: number; roleName: string }
  > = (props) => {
    const { userId, roleName } = props ?? {}

    return apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete(
      userId,
      roleName,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete>>
  >

export type ApiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDeleteMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Roles.Revoke
 */
export const useApiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete>>,
      TError,
      { userId: number; roleName: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDelete>>,
  TError,
  { userId: number; roleName: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersRolesRevokeApiAdminUsersUserIdRolesRoleNameDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Permissions.Grant
 */
export const apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost = (
  userId: MaybeRef<number>,
  grantPermissionPayload: MaybeRef<GrantPermissionPayload>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  userId = unref(userId)
  grantPermissionPayload = unref(grantPermissionPayload)

  return request<AdminUserWrapperOut>(
    {
      url: `/api/admin/users/${userId}/permissions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: grantPermissionPayload,
      signal,
    },
    options,
  )
}

export const getApiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationOptions = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
    TError,
    { userId: number; data: GrantPermissionPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
  TError,
  { userId: number; data: GrantPermissionPayload },
  TContext
> => {
  const mutationKey = ['apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
    { userId: number; data: GrantPermissionPayload }
  > = (props) => {
    const { userId, data } = props ?? {}

    return apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost(
      userId,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>
  >
export type ApiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationBody =
  GrantPermissionPayload
export type ApiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationError =
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut
  | ApiErrorOut

/**
 * @summary Api.Admin.Users.Permissions.Grant
 */
export const useApiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
      TError,
      { userId: number; data: GrantPermissionPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof apiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPost>>,
  TError,
  { userId: number; data: GrantPermissionPayload },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersPermissionsGrantApiAdminUsersUserIdPermissionsPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Api.Admin.Users.Permissions.Revoke
 */
export const apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete = (
  userId: MaybeRef<number>,
  permissionName: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
) => {
  userId = unref(userId)
  permissionName = unref(permissionName)

  return request<AdminUserWrapperOut>(
    { url: `/api/admin/users/${userId}/permissions/${permissionName}`, method: 'DELETE' },
    options,
  )
}

export const getApiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDeleteMutationOptions =
  <
    TError =
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut
      | ApiErrorOut,
    TContext = unknown,
  >(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete
        >
      >,
      TError,
      { userId: number; permissionName: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  }): UseMutationOptions<
    Awaited<
      ReturnType<
        typeof apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete
      >
    >,
    TError,
    { userId: number; permissionName: string },
    TContext
  > => {
    const mutationKey = [
      'apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete',
    ]
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined }

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<
          typeof apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete
        >
      >,
      { userId: number; permissionName: string }
    > = (props) => {
      const { userId, permissionName } = props ?? {}

      return apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete(
        userId,
        permissionName,
        requestOptions,
      )
    }

    return { mutationFn, ...mutationOptions }
  }

export type ApiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDeleteMutationResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete
      >
    >
  >

export type ApiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDeleteMutationError =
  ApiErrorOut | ApiErrorOut | ApiErrorOut | ApiErrorOut | ApiErrorOut | ApiErrorOut | ApiErrorOut

/**
 * @summary Api.Admin.Users.Permissions.Revoke
 */
export const useApiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete = <
  TError =
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut
    | ApiErrorOut,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete
        >
      >,
      TError,
      { userId: number; permissionName: string },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<
    ReturnType<
      typeof apiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDelete
    >
  >,
  TError,
  { userId: number; permissionName: string },
  TContext
> => {
  const mutationOptions =
    getApiAdminUsersPermissionsRevokeApiAdminUsersUserIdPermissionsPermissionNameDeleteMutationOptions(
      options,
    )

  return useMutation(mutationOptions, queryClient)
}
