/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  AdminOrderListOut,
  AdminOrderWrapperOut,
  AdminOrdersBestSellersApiAdminOrdersBestSellersGetParams,
  AdminOrdersIndexApiAdminOrdersGetParams,
  BestSellersListOut,
  HTTPValidationError,
  UpdateOrderStatusPayload,
} from '.././schemas'

import { request } from '../../lib/api'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Admin.Orders.Index
 */
export const adminOrdersIndexApiAdminOrdersGet = (
  params?: MaybeRef<AdminOrdersIndexApiAdminOrdersGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<AdminOrderListOut>(
    { url: `/api/admin/orders`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getAdminOrdersIndexApiAdminOrdersGetQueryKey = (
  params?: MaybeRef<AdminOrdersIndexApiAdminOrdersGetParams>,
) => {
  return ['api', 'admin', 'orders', ...(params ? [params] : [])] as const
}

export const getAdminOrdersIndexApiAdminOrdersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminOrdersIndexApiAdminOrdersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminOrdersIndexApiAdminOrdersGetQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>> = ({
    signal,
  }) => adminOrdersIndexApiAdminOrdersGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>,
    TError,
    TData
  >
}

export type AdminOrdersIndexApiAdminOrdersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>
>
export type AdminOrdersIndexApiAdminOrdersGetQueryError = HTTPValidationError

/**
 * @summary Admin.Orders.Index
 */

export function useAdminOrdersIndexApiAdminOrdersGet<
  TData = Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminOrdersIndexApiAdminOrdersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminOrdersIndexApiAdminOrdersGet>>, TError, TData>
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminOrdersIndexApiAdminOrdersGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Orders.Best Sellers
 */
export const adminOrdersBestSellersApiAdminOrdersBestSellersGet = (
  params?: MaybeRef<AdminOrdersBestSellersApiAdminOrdersBestSellersGetParams>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return request<BestSellersListOut>(
    { url: `/api/admin/orders/best-sellers`, method: 'GET', params: unref(params), signal },
    options,
  )
}

export const getAdminOrdersBestSellersApiAdminOrdersBestSellersGetQueryKey = (
  params?: MaybeRef<AdminOrdersBestSellersApiAdminOrdersBestSellersGetParams>,
) => {
  return ['api', 'admin', 'orders', 'best-sellers', ...(params ? [params] : [])] as const
}

export const getAdminOrdersBestSellersApiAdminOrdersBestSellersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminOrdersBestSellersApiAdminOrdersBestSellersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminOrdersBestSellersApiAdminOrdersBestSellersGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>
  > = ({ signal }) =>
    adminOrdersBestSellersApiAdminOrdersBestSellersGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>,
    TError,
    TData
  >
}

export type AdminOrdersBestSellersApiAdminOrdersBestSellersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>
>
export type AdminOrdersBestSellersApiAdminOrdersBestSellersGetQueryError = HTTPValidationError

/**
 * @summary Admin.Orders.Best Sellers
 */

export function useAdminOrdersBestSellersApiAdminOrdersBestSellersGet<
  TData = Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<AdminOrdersBestSellersApiAdminOrdersBestSellersGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminOrdersBestSellersApiAdminOrdersBestSellersGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminOrdersBestSellersApiAdminOrdersBestSellersGetQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Orders.Show
 */
export const adminOrdersShowApiAdminOrdersOrderIdGet = (
  orderId: MaybeRef<string>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  orderId = unref(orderId)

  return request<AdminOrderWrapperOut>(
    { url: `/api/admin/orders/${orderId}`, method: 'GET', signal },
    options,
  )
}

export const getAdminOrdersShowApiAdminOrdersOrderIdGetQueryKey = (orderId?: MaybeRef<string>) => {
  return ['api', 'admin', 'orders', orderId] as const
}

export const getAdminOrdersShowApiAdminOrdersOrderIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>,
  TError = HTTPValidationError,
>(
  orderId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getAdminOrdersShowApiAdminOrdersOrderIdGetQueryKey(orderId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>
  > = ({ signal }) => adminOrdersShowApiAdminOrdersOrderIdGet(orderId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(orderId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>,
    TError,
    TData
  >
}

export type AdminOrdersShowApiAdminOrdersOrderIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>
>
export type AdminOrdersShowApiAdminOrdersOrderIdGetQueryError = HTTPValidationError

/**
 * @summary Admin.Orders.Show
 */

export function useAdminOrdersShowApiAdminOrdersOrderIdGet<
  TData = Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>,
  TError = HTTPValidationError,
>(
  orderId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminOrdersShowApiAdminOrdersOrderIdGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminOrdersShowApiAdminOrdersOrderIdGetQueryOptions(orderId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Admin.Orders.Update Status
 */
export const adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch = (
  orderId: MaybeRef<string>,
  updateOrderStatusPayload: MaybeRef<UpdateOrderStatusPayload>,
  options?: SecondParameter<typeof request>,
) => {
  orderId = unref(orderId)
  updateOrderStatusPayload = unref(updateOrderStatusPayload)

  return request<AdminOrderWrapperOut>(
    {
      url: `/api/admin/orders/${orderId}/status`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateOrderStatusPayload,
    },
    options,
  )
}

export const getAdminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch>>,
    TError,
    { orderId: string; data: UpdateOrderStatusPayload },
    TContext
  >
  request?: SecondParameter<typeof request>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch>>,
  TError,
  { orderId: string; data: UpdateOrderStatusPayload },
  TContext
> => {
  const mutationKey = ['adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch>>,
    { orderId: string; data: UpdateOrderStatusPayload }
  > = (props) => {
    const { orderId, data } = props ?? {}

    return adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch(orderId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch>>
>
export type AdminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatchMutationBody =
  UpdateOrderStatusPayload
export type AdminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatchMutationError =
  HTTPValidationError

/**
 * @summary Admin.Orders.Update Status
 */
export const useAdminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch>>,
      TError,
      { orderId: string; data: UpdateOrderStatusPayload },
      TContext
    >
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatch>>,
  TError,
  { orderId: string; data: UpdateOrderStatusPayload },
  TContext
> => {
  const mutationOptions =
    getAdminOrdersUpdateStatusApiAdminOrdersOrderIdStatusPatchMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
