"""Laravel-style Schema DSL that compiles to SQLAlchemy / Alembic operations.

The DSL never emits raw SQL (ADR-012). Each Blueprint accumulates a list of
``Column``-and-``Constraint`` objects, then ``Schema.create / Schema.table``
hand them to Alembic via ``op.create_table`` / ``op.add_column``.

For the QA-Pre phase we don't yet have a live Alembic ``MigrationContext``,
so ``Schema.create`` and friends accept an optional ``executor`` callable
(default: the real ``alembic.op`` module). Tests pass a recording executor
to assert what would have been emitted without touching a database.
"""

from __future__ import annotations

import enum
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any, Protocol, cast

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.types import TypeDecorator


class JsonB(TypeDecorator[dict[str, Any]]):
    """PostgreSQL JSONB — degrades to JSON on non-PG dialects (e.g. SQLite in CI).

    Use Blueprint.jsonb() rather than Blueprint.json() when you need GIN indexing
    or containment operators (@>, <@, ?) on PostgreSQL.
    """

    impl = JSON
    cache_ok = True

    def load_dialect_impl(self, dialect: Any) -> Any:
        if dialect.name == "postgresql":
            from sqlalchemy.dialects.postgresql import JSONB

            return dialect.type_descriptor(JSONB())
        return dialect.type_descriptor(JSON())

    def process_bind_param(
        self, value: dict[str, Any] | None, dialect: Any
    ) -> dict[str, Any] | None:
        return value

    def process_result_value(
        self, value: dict[str, Any] | None, dialect: Any
    ) -> dict[str, Any] | None:
        return value


class _TsVector(TypeDecorator[str]):
    """PostgreSQL TSVECTOR — degrades to TEXT on non-PG dialects (e.g. SQLite in CI)."""

    impl = Text
    cache_ok = True

    def load_dialect_impl(self, dialect: Any) -> Any:
        if dialect.name == "postgresql":
            from sqlalchemy.dialects.postgresql import TSVECTOR

            return dialect.type_descriptor(TSVECTOR())
        return dialect.type_descriptor(Text())

    def compile(self, dialect: Any = None) -> str:
        if dialect is not None and getattr(dialect, "name", None) == "postgresql":
            return "TSVECTOR"
        return "TEXT"

    def process_bind_param(self, value: str | None, dialect: Any) -> str | None:
        return value

    def process_result_value(self, value: str | None, dialect: Any) -> str | None:
        return value


class IdType(enum.Enum):
    """Primary-key column strategy for ``Blueprint.id()``.

    - ``INT`` — INTEGER AUTOINCREMENT (default)
    - ``BIGINT`` — BIGINT AUTOINCREMENT (compatible with integer FKs)
    - ``UUID`` — UUID v7 stored as native UUID / VARCHAR(36); generated by the
      application layer (``uuid.uuid7()``), never by the database
    """

    INT = Integer
    BIGINT = BigInteger
    UUID = Uuid


class ForeignKeyAction(enum.Enum):
    """Action to take when a foreign key is updated or deleted."""

    CASCADE = "CASCADE"
    RESTRICT = "RESTRICT"
    SET_NULL = "SET NULL"
    SET_DEFAULT = "SET DEFAULT"


class _Executor(Protocol):
    """Subset of ``alembic.op`` we use.

    Tests can substitute a recorder.
    """

    def create_table(self, name: str, *columns: Column[Any], **kw: Any) -> None: ...
    def drop_table(self, name: str, **kw: Any) -> None: ...
    def add_column(self, table_name: str, column: Column[Any], **kw: Any) -> None: ...
    def drop_column(self, table_name: str, column_name: str, **kw: Any) -> None: ...
    def create_index(self, name: str, table: str, columns: list[str | Any], **kw: Any) -> None: ...
    def drop_index(self, name: str, table_name: str | None = None, **kw: Any) -> None: ...
    def execute(self, clause: Any, **kw: Any) -> None: ...


def _default_executor() -> _Executor:
    """Return ``alembic.op`` lazily so tests don't require an Alembic context."""
    from alembic import op

    return cast("_Executor", op)


@dataclass
class PendingColumn:
    """A column being built inside a Blueprint."""

    name: str
    type_: Any
    nullable_value: bool = True
    primary_key: bool = False
    unique_value: bool = False
    default_value: Any = None
    server_default_value: Any = None
    server_on_update: Any = None
    fk_target: str | None = None
    fk_on_delete: ForeignKeyAction | None = None
    fk_on_update: ForeignKeyAction | None = None
    autoincrement_value: bool = False
    # When set via ``Blueprint.raw_column(...)`` the column is emitted verbatim
    # and every chain modifier (``unique()``, ``nullable()``, …) is ignored.
    raw_sa_column: Column[Any] | None = None

    def primary(self, value: bool = True) -> PendingColumn:
        self.primary_key = value
        return self

    def autoincrement(self, value: bool = True) -> PendingColumn:
        self.autoincrement_value = value
        return self

    def nullable(self, value: bool = True) -> PendingColumn:
        self.nullable_value = value
        return self

    def unique(self, value: bool = True) -> PendingColumn:
        self.unique_value = value
        return self

    def on_delete(self, value: ForeignKeyAction | None = None) -> PendingColumn:
        self.fk_on_delete = value
        return self

    def on_update(self, value: ForeignKeyAction | None = None) -> PendingColumn:
        self.fk_on_update = value
        return self

    def default(self, value: Any) -> PendingColumn:
        self.default_value = value
        return self

    def server_default(self, value: str | Any) -> PendingColumn:
        """Set a server-side column default evaluated by the database.

        Pass a SQL string and it is wrapped in ``text()`` automatically::

            t.jsonb("meta").nullable(value=False).server_default("'{}'::jsonb")
            t.integer("status").server_default("0")
        """
        from sqlalchemy import text as _text

        self.server_default_value = _text(value) if isinstance(value, str) else value
        return self

    def use_current(self, *, on_update: bool = False) -> PendingColumn:
        """Set DEFAULT CURRENT_TIMESTAMP (and optionally ON UPDATE CURRENT_TIMESTAMP).

        - use_current()               → server_default = func.now()
        - use_current(on_update=True) → server_default + server_onupdate = FetchedValue()

        ON UPDATE is only emitted as DDL by MySQL/MariaDB dialects; on other dialects
        FetchedValue() is accepted by SQLAlchemy without raising an error.
        """
        from sqlalchemy import func
        from sqlalchemy.schema import FetchedValue

        self.server_default_value = func.now()
        if on_update:
            self.server_on_update = FetchedValue()
        return self

    def cascade(self) -> PendingColumn:
        """Shorthand: on_delete=CASCADE, on_update=CASCADE."""
        self.fk_on_delete = ForeignKeyAction.CASCADE
        self.fk_on_update = ForeignKeyAction.CASCADE
        return self

    def restrict(self) -> PendingColumn:
        """Shorthand: on_delete=RESTRICT, on_update=RESTRICT."""
        self.fk_on_delete = ForeignKeyAction.RESTRICT
        self.fk_on_update = ForeignKeyAction.RESTRICT
        return self

    def set_null(self) -> PendingColumn:
        """Shorthand: on_delete=SET NULL."""
        self.fk_on_delete = ForeignKeyAction.SET_NULL
        return self

    def comment(self, text: str) -> PendingColumn:
        """Attach a comment to the column (stored as metadata, dialect-dependent DDL)."""
        self._comment = text
        return self

    def after(self, column: str) -> PendingColumn:
        """Hint to place this column after ``column`` (MySQL only; no-op elsewhere)."""
        self._after = column
        return self

    def cascade_on_delete(self) -> PendingColumn:
        """Shorthand: on_delete=CASCADE."""
        self.fk_on_delete = ForeignKeyAction.CASCADE
        return self

    def null_on_delete(self) -> PendingColumn:
        """Shorthand: on_delete=SET NULL."""
        self.fk_on_delete = ForeignKeyAction.SET_NULL
        return self

    def restrict_on_delete(self) -> PendingColumn:
        """Shorthand: on_delete=RESTRICT."""
        self.fk_on_delete = ForeignKeyAction.RESTRICT
        return self

    def constrained(
        self,
        table: str | None = None,
        *,
        on_delete: ForeignKeyAction | None = None,
        on_update: ForeignKeyAction | None = None,
    ) -> PendingColumn:
        """Mark a foreign-key column as constrained to ``table.id``.

        ``table`` defaults to the column-name minus the trailing ``_id`` and
        pluralised (basic, snake-only).
        """
        if table is None:
            base = self.name.removesuffix("_id")
            table = base + "s"
        self.fk_target = f"{table}.id"
        self.fk_on_delete = on_delete
        self.fk_on_update = on_update
        return self

    def to_sqla_column(self) -> Column[Any]:
        if self.raw_sa_column is not None:
            return self.raw_sa_column
        kwargs: dict[str, Any] = {
            "nullable": self.nullable_value,
            "primary_key": self.primary_key,
            "unique": self.unique_value,
        }
        if self.default_value is not None:
            kwargs["default"] = self.default_value
        if self.server_default_value is not None:
            kwargs["server_default"] = self.server_default_value
        if self.server_on_update is not None:
            kwargs["server_onupdate"] = self.server_on_update
        if self.autoincrement_value:
            kwargs["autoincrement"] = True
        args: list[Any] = []
        if self.fk_target:
            args.append(
                ForeignKey(
                    self.fk_target,
                    ondelete=self.fk_on_delete.value if self.fk_on_delete else None,
                    onupdate=self.fk_on_update.value if self.fk_on_update else None,
                )
            )
        return Column(self.name, self.type_, *args, **kwargs)


@dataclass
class Blueprint:
    """The table definition builder passed into ``Schema.create / Schema.table``."""

    # Each field uses a parameterised list[T] as default_factory so pyright
    # sees the factory's return type as list[T] (not list[Unknown]). This is
    # equivalent to default_factory=list at runtime — calling list[T]() yields
    # an empty list — but carries the element type through the typing pipeline.
    table_name: str
    columns: list[PendingColumn] = field(default_factory=list[PendingColumn])
    indexes: list[tuple[str, list[str], bool, dict[str, Any]]] = field(
        default_factory=list[tuple[str, list[str], bool, dict[str, Any]]]
    )
    # Expression indexes — columns are raw SQL fragments wrapped in text().
    expression_indexes: list[tuple[str, str, bool]] = field(
        default_factory=list[tuple[str, str, bool]]
    )
    gin_indexes: list[tuple[str, list[str]]] = field(default_factory=list[tuple[str, list[str]]])
    uniques: list[tuple[str, list[str], bool | None]] = field(
        default_factory=list[tuple[str, list[str], bool | None]]
    )
    drops: list[str] = field(default_factory=list[str])
    drop_indexes: list[str] = field(default_factory=list[str])
    renames: list[tuple[str, str]] = field(default_factory=list[tuple[str, str]])
    modifies: list[tuple[str, Any, Any]] = field(default_factory=list[tuple[str, Any, Any]])

    # ---- column helpers ----

    def _add(self, col: PendingColumn) -> PendingColumn:
        self.columns.append(col)
        return col

    def make_pending_column_for_test(self, name: str, col_type: str) -> PendingColumn:
        """Test helper — create a standalone PendingColumn without registering it."""
        from sqlalchemy import DateTime, String

        _type_map: dict[str, Any] = {
            "string": String(255),
            "datetime": DateTime(timezone=True),
            "text": Text(),
        }
        return PendingColumn(name=name, type_=_type_map.get(col_type, String(255)))

    def id(
        self,
        name: str = "id",
        *,
        id_type: IdType = IdType.INT,
        primary_key: bool = True,
        autoincrement: bool = True,
        nullable: bool = False,
    ) -> PendingColumn:
        if id_type == IdType.UUID:
            autoincrement = False

        return self._add(
            PendingColumn(
                name=name,
                type_=id_type.value(),
                primary_key=primary_key,
                nullable_value=nullable,
                autoincrement_value=autoincrement,
            )
        )

    def big_integer(self, name: str, *, unsigned: bool = False) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Integer()))

    def integer(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Integer()))

    def string(self, name: str, length: int = 255) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=String(length=length)))

    def text(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Text()))

    def medium_text(self, name: str) -> PendingColumn:
        """MEDIUMTEXT on MySQL/MariaDB; TEXT on other dialects."""
        return self._add(PendingColumn(name=name, type_=Text(length=16777215)))

    def long_text(self, name: str) -> PendingColumn:
        """LONGTEXT on MySQL/MariaDB; unbounded TEXT on PostgreSQL / SQLite."""
        return self._add(PendingColumn(name=name, type_=Text(length=4294967295)))

    def tiny_integer(self, name: str) -> PendingColumn:
        """TINYINT (stored as INTEGER on SQLite)."""
        return self._add(PendingColumn(name=name, type_=Integer()))

    def boolean(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Boolean()))

    def float(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Float()))

    def decimal(self, name: str, precision: int = 10, scale: int = 2) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Numeric(precision=precision, scale=scale)))

    def datetime(self, name: str, *, timezone: bool = True, nullable: bool = True) -> PendingColumn:
        return self._add(
            PendingColumn(name=name, type_=DateTime(timezone=timezone), nullable_value=nullable)
        )

    def json(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=JSON()))

    def jsonb(self, name: str) -> PendingColumn:
        """PostgreSQL JSONB column. Degrades to JSON on non-PG dialects.

        Pair with Blueprint.gin_index() for containment-query GIN indexes.
        """
        return self._add(PendingColumn(name=name, type_=JsonB()))

    def binary(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=LargeBinary()))

    def foreign_id(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Integer()))

    def timestamps(
        self, *, nullable: bool = False, on_update: bool = True
    ) -> tuple[PendingColumn, PendingColumn]:
        created_at = self.datetime("created_at", nullable=nullable).use_current()
        updated_at = self.datetime("updated_at", nullable=nullable).use_current(on_update=on_update)

        return created_at, updated_at

    def uuid(self, name: str) -> PendingColumn:
        return self._add(PendingColumn(name=name, type_=Uuid()))

    def ulid(self, name: str) -> PendingColumn:
        """ULID stored as CHAR(26)."""
        return self._add(PendingColumn(name=name, type_=String(26)))

    def enum(self, name: str, values: list[str]) -> PendingColumn:
        from sqlalchemy import Enum as SaEnum

        return self._add(
            PendingColumn(name=name, type_=SaEnum(*values, name=f"{self.table_name}_{name}"))
        )

    def ip_address(self, name: str) -> PendingColumn:
        """IPv4/IPv6 stored as VARCHAR(45)."""
        return self._add(PendingColumn(name=name, type_=String(45)))

    def geometry(self, name: str) -> PendingColumn:
        """Geometry column stored as TEXT for portability."""
        return self._add(PendingColumn(name=name, type_=Text()))

    def raw_column(self, column: Column[Any]) -> PendingColumn:
        """Add a fully-formed SQLAlchemy ``Column`` verbatim.

        Use when the fluent helpers don't expose a feature you need — e.g. a
        Postgres ``JSONB`` column with a ``GIN`` index, a custom
        ``TypeDecorator``, ``Computed`` defaults, or vendor-specific column
        flags. The column is emitted as-is; chain modifiers on the returned
        ``PendingColumn`` (``.unique()``, ``.nullable()``, …) are no-ops.

        The column MUST have its ``name`` set::

            t.raw_column(Column("payload", JSONB, nullable=False))

        Raises ``ValueError`` if the column is unnamed.
        """
        if not column.name:
            raise ValueError("raw_column requires a Column with a non-empty name")
        return self._add(PendingColumn(name=column.name, type_=column.type, raw_sa_column=column))

    def soft_deletes(self, name: str = "deleted_at", *, index: bool = True) -> PendingColumn:
        col = self.datetime(name, nullable=True)
        if index:
            idx_name = f"ix_{self.table_name}_{name}_active"
            self.indexes.append(
                (
                    idx_name,
                    [name],
                    False,
                    {"postgresql_where": text(f"{name} IS NULL")},
                )
            )
        return col

    def drop_timestamps(self) -> None:
        """Drop the standard created_at and updated_at columns."""
        self.drops.extend(["created_at", "updated_at"])

    def drop_soft_deletes(self, name: str = "deleted_at") -> None:
        """Drop the soft-delete column."""
        self.drops.append(name)

    def drop_morphs(self, base_name: str) -> None:
        """Drop the polymorphic type and id columns added by morphs()."""
        self.drops.extend([f"{base_name}_type", f"{base_name}_id"])

    def morphs(self, base_name: str) -> tuple[PendingColumn, PendingColumn]:
        type_col = self._add(
            PendingColumn(name=f"{base_name}_type", type_=String(length=255), nullable_value=False)
        )
        id_col = self._add(
            PendingColumn(name=f"{base_name}_id", type_=Integer(), nullable_value=False)
        )
        self.indexes.append(
            (
                f"ix_{self.table_name}_{base_name}",
                [f"{base_name}_type", f"{base_name}_id"],
                False,
                {},
            )
        )
        return type_col, id_col

    # ---- index helpers ----

    def tsvector(self, name: str) -> PendingColumn:
        """Add a TSVECTOR column (PostgreSQL). Falls back to TEXT on other dialects."""
        return self._add(PendingColumn(name=name, type_=_TsVector()))

    def gin_index(self, table: str, *cols: str, name: str | None = None) -> None:
        """Add a GIN index covering the given columns (PostgreSQL-specific)."""
        idx_name = name or f"gin_{table}_{'_'.join(cols)}"
        self.gin_indexes.append((idx_name, list(cols)))

    def index(
        self,
        columns: list[str] | str,
        *,
        name: str | None = None,
        unique: bool = False,
        where: str | Any | None = None,
    ) -> None:
        cols = [columns] if isinstance(columns, str) else columns
        name = name or f"ix_{self.table_name}_{'_'.join(cols)}"
        extra: dict[str, Any] = {}
        if where is not None:
            extra["postgresql_where"] = text(where) if isinstance(where, str) else where
        self.indexes.append((name, cols, unique, extra))

    def unique(
        self,
        columns: list[str] | str,
        *,
        name: str | None = None,
        nulls_not_distinct: bool | None = None,
    ) -> None:
        cols = [columns] if isinstance(columns, str) else columns
        name = name or f"uq_{self.table_name}_{'_'.join(cols)}"
        self.uniques.append((name, cols, nulls_not_distinct))

    def expression_index(
        self,
        expression: str,
        *,
        name: str,
        unique: bool = False,
    ) -> None:
        """Add a PostgreSQL functional/expression index.

        Use this for indexes on JSONB paths or any computed column that the
        standard ``index()`` / ``unique()`` helpers can't express, e.g.::

            t.expression_index("(slug->>'en')", name="categories_slug_en_unique", unique=True)
        """
        self.expression_indexes.append((name, expression, unique))

    # ---- alter helpers (used inside Schema.table) ----

    def drop_column(self, column: str) -> None:
        self.drops.append(column)

    def drop_index(self, name: str) -> None:
        self.drop_indexes.append(name)

    def rename_column(self, old_name: str, new_name: str) -> None:
        self.renames.append((old_name, new_name))

    def modify_column(self, name: str, *, nullable: bool | None = None, type_: Any = None) -> None:
        """Record a column type/nullability modification."""
        self.modifies.append((name, nullable, type_))


def materialized_view_names(inspector: Any) -> list[str]:
    """Return materialized view names when the dialect supports them."""
    getter = getattr(inspector, "get_materialized_view_names", None)
    if getter is None:
        return []
    try:
        return list(getter())
    except NotImplementedError:
        return []


def _inspector_from_active_session() -> Any:
    """Return a sync ``Inspector`` from the active session's bind, or ``None``.

    Wrapped in a narrow ``SQLAlchemyError`` guard: an unbound session, a closed
    connection, or a backend with no introspection support all surface as
    SQLAlchemy errors, and the introspection helpers degrade gracefully in
    those cases rather than crashing the caller.
    """
    from sqlalchemy import inspect as sqla_inspect
    from sqlalchemy.exc import SQLAlchemyError

    from arvel.database.session import get_optional_session

    sess = get_optional_session()
    if sess is None:
        return None
    try:
        bind = sess.sync_session.get_bind()
    except SQLAlchemyError:
        return None
    return sqla_inspect(bind)


class Schema:
    """Facade — every public method is a classmethod.

    ``executor=`` lets tests inject a recorder instead of touching Alembic.
    """

    # ---- introspection helpers ----

    @classmethod
    async def has_table(cls, engine_or_name: Any, table_name: str | None = None) -> bool:
        """Return True if the table exists.

        Accepts two call signatures:
        - ``await Schema.has_table(engine, "table_name")``
        - ``await Schema.has_table("table_name")``  (uses active session's bind)
        """
        from sqlalchemy import inspect as sqla_inspect
        from sqlalchemy.ext.asyncio import AsyncEngine

        if table_name is None:
            inspector = _inspector_from_active_session()
            if inspector is None:
                return False
            return bool(inspector.has_table(engine_or_name))

        engine = engine_or_name
        if isinstance(engine, AsyncEngine):
            async with engine.connect() as conn:
                return await conn.run_sync(lambda c: bool(sqla_inspect(c).has_table(table_name)))
        return bool(sqla_inspect(engine).has_table(table_name))

    @classmethod
    async def has_column(
        cls, engine_or_name: Any, table_name_or_col: str, column_name: str | None = None
    ) -> bool:
        """Return True if the column exists on the given table.

        Signatures:
        - ``await Schema.has_column(engine, "table", "column")``
        - ``await Schema.has_column("table", "column")``
        """
        from sqlalchemy import inspect as sqla_inspect
        from sqlalchemy.ext.asyncio import AsyncEngine

        if column_name is None:
            t_name, c_name = engine_or_name, table_name_or_col
            inspector = _inspector_from_active_session()
            if inspector is None:
                return False
            return c_name in [col["name"] for col in inspector.get_columns(t_name)]

        engine, t_name, c_name = engine_or_name, table_name_or_col, column_name
        if isinstance(engine, AsyncEngine):
            async with engine.connect() as conn:
                cols = await conn.run_sync(
                    lambda c: [x["name"] for x in sqla_inspect(c).get_columns(t_name)]
                )
                return c_name in cols
        return c_name in [col["name"] for col in sqla_inspect(engine).get_columns(t_name)]

    @classmethod
    async def get_columns(
        cls, engine_or_name: Any, table_name: str | None = None
    ) -> list[dict[str, Any]]:
        """Return list of column info dicts for a table.

        Signatures:
        - ``await Schema.get_columns(engine, "table")``
        - ``await Schema.get_columns("table")``
        """
        from sqlalchemy import inspect as sqla_inspect
        from sqlalchemy.ext.asyncio import AsyncEngine

        if table_name is None:
            inspector = _inspector_from_active_session()
            if inspector is None:
                return []
            # ``ReflectedColumn`` is a ``TypedDict`` over plain dicts.
            return cast("list[dict[str, Any]]", list(inspector.get_columns(engine_or_name)))

        engine = engine_or_name
        if isinstance(engine, AsyncEngine):
            async with engine.connect() as conn:
                return cast(
                    "list[dict[str, Any]]",
                    await conn.run_sync(lambda c: list(sqla_inspect(c).get_columns(table_name))),
                )
        return cast("list[dict[str, Any]]", list(sqla_inspect(engine).get_columns(table_name)))

    @classmethod
    async def has_view(cls, engine_or_name: Any, view_name: str | None = None) -> bool:
        """Return True if the view exists.

        Signatures:
        - ``await Schema.has_view(engine, "view_name")``
        - ``await Schema.has_view("view_name")``  (uses active session's bind)
        """
        from sqlalchemy import inspect as sqla_inspect
        from sqlalchemy.ext.asyncio import AsyncEngine

        if view_name is None:
            inspector = _inspector_from_active_session()
            if inspector is None:
                return False
            return engine_or_name in inspector.get_view_names()

        engine, v_name = engine_or_name, view_name
        if isinstance(engine, AsyncEngine):
            async with engine.connect() as conn:
                return await conn.run_sync(lambda c: v_name in sqla_inspect(c).get_view_names())
        return view_name in sqla_inspect(engine).get_view_names()

    @classmethod
    def run_sql(cls, sql: str, *, executor: _Executor | None = None) -> None:
        """Execute arbitrary SQL through the active migration context."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(text(sql))

    @classmethod
    def install_extension(cls, extension_name: str, *, executor: _Executor | None = None) -> None:
        """Emit ``CREATE EXTENSION IF NOT EXISTS "extension_name"``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(
            text(f'CREATE EXTENSION IF NOT EXISTS "{extension_name}"')
        )

    @classmethod
    def uninstall_extension(cls, extension_name: str, *, executor: _Executor | None = None) -> None:
        """Emit ``DROP EXTENSION IF EXISTS "extension_name"``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(
            text(f'DROP EXTENSION IF EXISTS "{extension_name}"')
        )

    @classmethod
    def create_view(
        cls,
        view_name: str,
        select_sql: str,
        *,
        executor: _Executor | None = None,
    ) -> None:
        """Emit ``CREATE VIEW view_name AS select_sql``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(text(f"CREATE VIEW {view_name} AS {select_sql}"))

    @classmethod
    def drop_view(cls, view_name: str, *, executor: _Executor | None = None) -> None:
        """Emit ``DROP VIEW view_name``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(text(f"DROP VIEW {view_name}"))

    @classmethod
    def drop_view_if_exists(cls, view_name: str, *, executor: _Executor | None = None) -> None:
        """Emit ``DROP VIEW IF EXISTS view_name``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(text(f"DROP VIEW IF EXISTS {view_name}"))

    @classmethod
    def create_materialized_view(
        cls,
        view_name: str,
        select_sql: str,
        *,
        with_data: bool = True,
        executor: _Executor | None = None,
    ) -> None:
        """Emit ``CREATE MATERIALIZED VIEW view_name AS select_sql`` (PostgreSQL only)."""
        from sqlalchemy import text

        suffix = "" if with_data else " WITH NO DATA"
        (executor or _default_executor()).execute(
            text(f"CREATE MATERIALIZED VIEW {view_name} AS {select_sql}{suffix}")
        )

    @classmethod
    def refresh_materialized_view(
        cls,
        view_name: str,
        *,
        concurrently: bool = False,
        executor: _Executor | None = None,
    ) -> None:
        """Emit ``REFRESH MATERIALIZED VIEW [CONCURRENTLY] view_name`` (PostgreSQL only)."""
        from sqlalchemy import text

        keyword = (
            "REFRESH MATERIALIZED VIEW CONCURRENTLY"
            if concurrently
            else "REFRESH MATERIALIZED VIEW"
        )
        (executor or _default_executor()).execute(text(f"{keyword} {view_name}"))

    @classmethod
    def drop_materialized_view(cls, view_name: str, *, executor: _Executor | None = None) -> None:
        """Emit ``DROP MATERIALIZED VIEW view_name``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(text(f"DROP MATERIALIZED VIEW {view_name}"))

    @classmethod
    def drop_materialized_view_if_exists(
        cls, view_name: str, *, executor: _Executor | None = None
    ) -> None:
        """Emit ``DROP MATERIALIZED VIEW IF EXISTS view_name``."""
        from sqlalchemy import text

        (executor or _default_executor()).execute(
            text(f"DROP MATERIALIZED VIEW IF EXISTS {view_name}")
        )

    @classmethod
    def create_index(
        cls,
        name: str,
        table: str,
        columns: list[str],
        *,
        unique: bool = False,
        using: str | None = None,
        executor: _Executor | None = None,
    ) -> None:
        """Create a plain column index on any relation (table or materialized view).

        Use this outside a ``schema.create()`` callback — for materialized views or
        for indexes added in a later ``schema.table()`` call::

            schema.create_index("idx_foo_bar", "foo", ["bar"], unique=True)
            schema.create_index("idx_foo_vec_gin", "foo", ["vec"], using="gin")
        """
        kw: dict[str, Any] = {}
        if using:
            kw["postgresql_using"] = using
        (executor or _default_executor()).create_index(name, table, columns, unique=unique, **kw)

    @classmethod
    def create_expression_index(
        cls,
        name: str,
        table: str,
        expression: str,
        *,
        unique: bool = False,
        executor: _Executor | None = None,
    ) -> None:
        """Create a PostgreSQL functional/expression index on any relation.

        The expression is any SQL fragment accepted by ``CREATE INDEX … ON t (expr)``,
        including descending columns, JSONB paths, and computed values::

            schema.create_expression_index(
                "idx_foo_bar_desc", "foo", "bar DESC"
            )
            schema.create_expression_index(
                "idx_foo_slug_en", "foo", "(slug->>'en')", unique=True
            )
        """
        (executor or _default_executor()).create_index(
            name,
            table,
            [text(expression)],
            unique=unique,
        )

    @classmethod
    async def has_materialized_view(cls, engine_or_name: Any, view_name: str | None = None) -> bool:
        """Return True if the materialized view exists (PostgreSQL only).

        Signatures:
        - ``await Schema.has_materialized_view(engine, "view_name")``
        - ``await Schema.has_materialized_view("view_name")``  (active session bind)
        """
        from sqlalchemy.ext.asyncio import AsyncEngine

        if view_name is None:
            inspector = _inspector_from_active_session()
            if inspector is None:
                return False
            return engine_or_name in materialized_view_names(inspector)

        engine, v_name = engine_or_name, view_name
        if isinstance(engine, AsyncEngine):
            async with engine.connect() as conn:

                def _check(sync_conn: Any) -> bool:
                    from sqlalchemy import inspect as sqla_inspect

                    return v_name in materialized_view_names(sqla_inspect(sync_conn))

                return await conn.run_sync(_check)
        from sqlalchemy import inspect as sqla_inspect

        return v_name in materialized_view_names(sqla_inspect(engine))

    @classmethod
    def create(
        cls,
        table_name: str,
        build: Callable[[Blueprint], None],
        *,
        executor: _Executor | None = None,
    ) -> None:
        bp = Blueprint(table_name=table_name)
        build(bp)
        cls._emit_create(bp, executor or _default_executor())

    @classmethod
    def table(
        cls,
        table_name: str,
        build: Callable[[Blueprint], None],
        *,
        executor: _Executor | None = None,
    ) -> None:
        bp = Blueprint(table_name=table_name)
        build(bp)
        cls._emit_alter(bp, executor or _default_executor())

    @classmethod
    def drop(cls, table_name: str, *, executor: _Executor | None = None) -> None:
        (executor or _default_executor()).drop_table(table_name)

    @classmethod
    def drop_if_exists(cls, table_name: str, *, executor: _Executor | None = None) -> None:
        (executor or _default_executor()).drop_table(table_name)

    @classmethod
    def rename(
        cls,
        from_name: str,
        to_name: str,
        *,
        executor: _Executor | None = None,
    ) -> None:
        ex = executor or _default_executor()
        rename_table = getattr(ex, "rename_table", None)
        if rename_table is None:
            raise NotImplementedError("executor does not support rename_table")
        rename_table(from_name, to_name)

    # ---- compile helpers ----

    @classmethod
    def _emit_create(cls, bp: Blueprint, executor: _Executor) -> None:
        sqla_columns = [col.to_sqla_column() for col in bp.columns]
        constraints: list[Any] = []
        for name, cols, nulls_not_distinct in bp.uniques:
            pg_kw: dict[str, Any] = {}
            if nulls_not_distinct is not None:
                pg_kw["postgresql_nulls_not_distinct"] = nulls_not_distinct
            constraints.append(UniqueConstraint(*cols, name=name, **pg_kw))
        executor.create_table(bp.table_name, *sqla_columns, *constraints)
        for name, cols, unique, extra_kw in bp.indexes:
            executor.create_index(name, bp.table_name, cols, unique=unique, **extra_kw)
        for name, expr, unique in bp.expression_indexes:
            executor.create_index(name, bp.table_name, [text(expr)], unique=unique)
        for name, cols in bp.gin_indexes:
            executor.create_index(name, bp.table_name, cols, postgresql_using="gin")

    @classmethod
    def _emit_alter(cls, bp: Blueprint, executor: _Executor) -> None:
        for col in bp.columns:
            executor.add_column(bp.table_name, col.to_sqla_column())
        for name, cols, unique, extra_kw in bp.indexes:
            executor.create_index(name, bp.table_name, cols, unique=unique, **extra_kw)
        for name, expr, unique in bp.expression_indexes:
            executor.create_index(name, bp.table_name, [text(expr)], unique=unique)
        for name, cols in bp.gin_indexes:
            executor.create_index(name, bp.table_name, cols, postgresql_using="gin")
        for col_name in bp.drops:
            executor.drop_column(bp.table_name, col_name)
        for idx_name in bp.drop_indexes:
            executor.drop_index(idx_name, bp.table_name)
        cls._apply_column_alterations(bp, executor)

    @classmethod
    def _apply_column_alterations(cls, bp: Blueprint, executor: _Executor) -> None:
        alter_column = getattr(executor, "alter_column", None)
        if alter_column is None:
            return
        for old_name, new_name in bp.renames:
            alter_column(bp.table_name, old_name, new_column_name=new_name)
        for col_name, nullable, col_type in bp.modifies:
            kwargs: dict[str, Any] = {}
            if nullable is not None:
                kwargs["nullable"] = nullable
            if col_type is not None:
                kwargs["type_"] = col_type
            alter_column(bp.table_name, col_name, **kwargs)


__all__ = ["Blueprint", "ForeignKeyAction", "IdType", "Index", "JsonB", "PendingColumn", "Schema"]
