"""Arvent — Arvel's ORM, built on SQLAlchemy.

A branded front door to ``arvel.database``. Every symbol here is the same
object as the one in ``arvel.database``; no copies, no wrappers.

    from arvent import Model, Timestamps, id_, string
"""

from arvel.database import (
    DB,
    ActiveRecord,
    Blueprint,
    Collection,
    CursorPaginator,
    DatabaseConnectionError,
    DatabaseSeeder,
    DecryptionError,
    EncryptedType,
    EnumType,
    Factory,
    ForeignKeyAction,
    GlobalScope,
    IdType,
    MassAssignmentError,
    Migration,
    MigrationNotReversibleError,
    Model,
    ModelNotFoundError,
    MultipleResultsError,
    Observer,
    Paginator,
    PydanticType,
    QueryBuilder,
    RelationNotLoadedError,
    Schema,
    Seeder,
    SimplePaginator,
    SoftDeletes,
    TableQueryBuilder,
    Timestamps,
    UnknownRelationError,
    accessor,
    big_integer,
    boolean,
    datetime,
    foreign_id,
    id_,
    integer,
    json,
    mutator,
    scope,
    string,
    text,
    uuid,
)

__all__ = [
    "DB",
    "ActiveRecord",
    "Blueprint",
    "Collection",
    "CursorPaginator",
    "DatabaseConnectionError",
    "DatabaseSeeder",
    "DecryptionError",
    "EncryptedType",
    "EnumType",
    "Factory",
    "ForeignKeyAction",
    "GlobalScope",
    "IdType",
    "MassAssignmentError",
    "Migration",
    "MigrationNotReversibleError",
    "Model",
    "ModelNotFoundError",
    "MultipleResultsError",
    "Observer",
    "Paginator",
    "PydanticType",
    "QueryBuilder",
    "RelationNotLoadedError",
    "Schema",
    "Seeder",
    "SimplePaginator",
    "SoftDeletes",
    "TableQueryBuilder",
    "Timestamps",
    "UnknownRelationError",
    "accessor",
    "big_integer",
    "boolean",
    "datetime",
    "foreign_id",
    "id_",
    "integer",
    "json",
    "mutator",
    "scope",
    "string",
    "text",
    "uuid",
]
