import { QueryClient, VueQueryPlugin } from '@tanstack/vue-query'
import { createPinia } from 'pinia'
import { createApp } from 'vue'
import { createI18n } from 'vue-i18n'
import App from './App.vue'
import router from './router'
import './assets/main.css'
import { apiI18nCatalogueApiI18nLocaleGet } from './api/i18n/i18n'
import { setUnauthorizedHandler } from './lib/api'
import {
  applyDocumentLocale,
  cacheTranslations,
  getCachedTranslations,
  getStoredLocale,
  SUPPORTED_LOCALES,
} from './lib/i18n'
import type { SupportedLocale } from './types'

async function loadMessages(locale: SupportedLocale): Promise<Record<string, string>> {
  const cached = getCachedTranslations(locale)
  if (cached) return cached
  try {
    const messages = (await apiI18nCatalogueApiI18nLocaleGet(locale)) as Record<string, string>
    cacheTranslations(locale, messages)
    return messages
  } catch {
    return {}
  }
}

// Static fallbacks for UI strings not in the backend catalogue.
// Backend messages override these when they exist for the same key.
const UI_FALLBACKS: Record<SupportedLocale, Record<string, string>> = {
  en: {
    // nav
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.specials': 'Specials',
    'nav.categories': 'Categories',
    'nav.search': 'Search',
    'nav.cart': 'Cart',
    'nav.account': 'Account',
    'nav.orders': 'My Orders',
    'nav.admin': 'Admin',
    'nav.login': 'Log in',
    'nav.logout': 'Log out',
    'nav.theme': 'Toggle theme',
    'nav.admin_mode': 'Admin mode',
    'nav.edit_product': 'Edit this product',
    'nav.manage_products': 'Manage products',
    'nav.admin_panel': 'Admin panel →',
    // search
    'search.placeholder': 'Search products…',
    'search.results': 'Search Results',
    // hero
    'hero.eyebrow': 'New Collection',
    'hero.sale_title': 'SUMMER',
    'hero.sale_accent': '10% SALE',
    'hero.promo_hint': 'Use this code at checkout',
    'hero.price_from': 'From',
    'hero.top_rated': 'Top Rated',
    'hero.browse': 'Browse All',
    'hero.discount': '20% OFF',
    'hero.title': 'Essentials, reimagined.',
    'hero.subtitle': 'Premium materials. Timeless design. Free shipping on orders over $75.',
    'hero.cta': 'Shop Now',
    // home
    'home.shop_by_category': 'Shop by Category',
    'home.new_arrivals': 'New Arrivals',
    'home.new_arrivals_sub': 'Fresh picks, just dropped',
    'home.categories': 'Top Categories',
    'home.flash_sale': 'Flash Sale',
    'home.view_all': 'View all',
    'home.big_sale_eyebrow': 'Big Saving on Top-selling Electronics',
    'home.big_sale_title': 'Get Up To',
    'home.big_sale_highlight': '85% OFF',
    'home.big_sale_suffix': 'on Big Billion Day',
    'flash.title': 'Deal of the Day',
    // promo banners
    'promo.shop_now': 'Shop Now',
    'promo.mobiles.eyebrow': 'Flat 15% OFF',
    'promo.mobiles.title': 'Smart Mobiles',
    'promo.mobiles.subtitle': 'Indulge in latest models',
    'promo.headsets.eyebrow': 'Flat 10% OFF',
    'promo.headsets.title': 'Smart Headset',
    'promo.headsets.subtitle': 'Enjoy wireless freedom',
    'promo.speakers.eyebrow': 'Flat 15% OFF',
    'promo.speakers.title': 'Portable Speaker',
    'promo.speakers.subtitle': 'Take your music anywhere',
    // products
    'products.all': 'All Products',
    'products.category': 'Category',
    // product
    'product.add_to_cart': 'Add to Cart',
    'product.adding': 'Adding…',
    'product.quantity': 'Qty',
    // cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continue': 'Continue Shopping',
    'cart.subtotal': 'Subtotal',
    'cart.checkout': 'Proceed to Checkout',
    // checkout
    'checkout.title': 'Checkout',
    'checkout.place_order': 'Place Order',
    // account
    'account.title': 'My Orders',
    // auth
    'auth.welcome': 'Welcome to Arvel',
    'auth.admin_sign_in': 'Admin Sign In',
    'auth.login': 'Log in',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.full_name': 'Full name',
    'auth.signing_in': 'Signing in…',
    'auth.creating_account': 'Creating account…',
    // shared order labels
    'order.product': 'Product',
    'order.price': 'Price',
    'order.quantity': 'Quantity',
    'order.qty': 'Qty',
    'order.subtotal': 'Subtotal',
    'order.shipping': 'Shipping',
    'order.taxes': 'Taxes',
    'order.total': 'Total',
    'order.items': 'Items',
    'order.free': 'Free',
    'order.summary': 'Order Summary',
    'order.cod': 'Cash on Delivery',
    'order.id': 'Order ID',
    'order.date': 'Date',
    'order.address': 'Address',
    'order.payment': 'Payment',
    'order.delivery_date': 'Delivery Date',
    'order.status': 'Status',
    'order.details': 'Details',
    // checkout steps + form
    'checkout.steps.shipping': 'Shipping',
    'checkout.steps.review': 'Review',
    'checkout.steps.confirmation': 'Confirmation',
    'checkout.confirmed_title': 'Order Confirmation',
    'checkout.confirmed_sub': 'Thank you for your order!',
    'checkout.full_name': 'Full name',
    'checkout.full_name_placeholder': 'John Smith',
    'checkout.street': 'Street address',
    'checkout.street_placeholder': '123 Main Street',
    'checkout.city': 'City',
    'checkout.city_placeholder': 'New York',
    'checkout.country': 'Country',
    'checkout.country_placeholder': 'United States',
    'checkout.cod_sub': 'Pay when your order arrives',
    'checkout.review_order': 'Review Order',
    'checkout.back': 'Back',
    'checkout.back_to_shop': 'Back to Shop',
    'checkout.placing': 'Placing order…',
    'checkout.view_orders': 'View My Orders',
    'checkout.failed': 'Checkout failed. Please try again.',
    // account
    'account.order_placed': 'Order placed successfully!',
    'account.no_orders': 'No orders yet',
    'account.col_order': 'Order',
    'account.col_date': 'Date',
    'account.col_items': 'Items',
    'account.col_payment': 'Payment',
    'account.col_status': 'Status',
    'account.col_details': 'Details',
    'account.drawer_order': 'Order',
    // admin — sidebar
    'admin.sidebar.admin_panel': 'Admin Panel',
    'admin.sidebar.collapse': 'Collapse',
    'admin.sidebar.dashboard': 'Dashboard',
    'admin.sidebar.products': 'Products',
    'admin.sidebar.categories': 'Categories',
    'admin.sidebar.vendors': 'Vendors',
    'admin.sidebar.orders': 'Orders',
    'admin.sidebar.users': 'Users',
    'admin.sidebar.roles': 'Roles',
    'admin.sidebar.logout': 'Sign out',
    // admin — dashboard
    'admin.dashboard.title': 'Dashboard',
    'admin.dashboard.subtitle': 'Overview of your store performance',
    'admin.stat.revenue': 'Total Revenue',
    'admin.stat.orders': 'Orders',
    'admin.stat.customers': 'Customers',
    'admin.stat.vs_last_month': 'vs last month',
    'admin.stat.avg_order': 'Avg. Order',
    'admin.dashboard.status_breakdown': 'Order Status',
    'admin.dashboard.greeting_morning': 'Good morning',
    'admin.dashboard.greeting_afternoon': 'Good afternoon',
    'admin.dashboard.greeting_evening': 'Good evening',
    'admin.dashboard.all_orders': 'All Orders',
    'admin.chart.revenue_7d': '7-Day Revenue',
    'admin.chart.last_7_days': 'Last 7 days',
    'admin.chart.no_data': 'No orders in this period',
    'admin.status.total': 'Total',
    'admin.recent_orders.title': 'Recent Orders',
    'admin.recent_orders.view_all': 'View all',
    'admin.recent_orders.empty': 'No recent orders',
    'admin.best_sellers.title': 'Best Sellers',
    'admin.best_sellers.items': '{n} item(s)',
    'admin.best_sellers.units': '{n} units sold',
    'admin.best_sellers.empty': 'No sales data yet',
    // admin — catalog list
    'admin.catalog.products': 'Products',
    'admin.catalog.categories': 'Categories',
    'admin.catalog.vendors': 'Vendors',
    'admin.catalog.product_singular': 'Product',
    'admin.catalog.category_singular': 'Category',
    'admin.catalog.vendor_singular': 'Vendor',
    'admin.catalog.items_count': '{n} items',
    'admin.catalog.refresh': 'Refresh Catalog',
    'admin.catalog.refreshing': 'Refreshing…',
    'admin.catalog.catalog_refreshed': 'Catalog refreshed — {count} products indexed',
    'admin.catalog.add': 'Add {item}',
    'admin.catalog.col_name': 'Name',
    'admin.catalog.col_status': 'Status',
    'admin.catalog.col_visibility': 'Visibility',
    'admin.catalog.col_actions': 'Actions',
    'admin.catalog.loading': 'Loading…',
    'admin.catalog.empty': 'No items',
    'admin.catalog.action_edit': 'Edit',
    'admin.catalog.action_publish': 'Publish',
    'admin.catalog.action_unpublish': 'Unpublish',
    'admin.catalog.action_restore': 'Restore',
    'admin.catalog.action_delete': 'Delete',
    'admin.catalog.delete_confirm': 'Delete this item?',
    'admin.catalog.saving': 'Saving…',
    'admin.catalog.save': 'Save',
    'admin.catalog.cancel': 'Cancel',
    'admin.catalog.field_slug': 'Slug',
    'admin.catalog.field_description': 'Description',
    'admin.catalog.field_price': 'Price',
    'admin.catalog.field_stock': 'Stock',
    'admin.catalog.field_category': 'Category',
    'admin.catalog.field_vendor': 'Vendor',
    'admin.catalog.no_vendor': 'No vendor',
    'admin.catalog.select_category': 'Select category…',
    'admin.catalog.prev': 'Prev',
    'admin.catalog.next': 'Next',
    'admin.catalog.page_of': 'Page {page} of {total} ({count} items)',
    'admin.catalog.form_create': 'Create {item}',
    'admin.catalog.form_edit': 'Edit {item}',
    'admin.catalog.toast_created': '{item} created',
    'admin.catalog.toast_saved': 'Changes saved',
    'admin.catalog.toast_deleted': '{item} deleted',
    'admin.catalog.toast_published': '{item} published',
    'admin.catalog.toast_unpublished': '{item} unpublished',
    'admin.catalog.toast_restored': '{item} restored',
    'admin.catalog.op_failed': 'Operation failed',
    'admin.catalog.show_trashed': 'Show deleted',
    // admin — real_status labels
    'admin.real_status.visible': 'Visible',
    'admin.real_status.draft': 'Draft',
    'admin.real_status.not_scheduled': 'Not scheduled',
    'admin.real_status.scheduled': 'Scheduled',
    'admin.status.published': 'Published',
    'admin.status.draft': 'Draft',
    // order status labels
    'admin.order_status.pending': 'Pending',
    'admin.order_status.confirmed': 'Confirmed',
    'admin.order_status.processing': 'Processing',
    'admin.order_status.shipped': 'Shipped',
    'admin.order_status.delivered': 'Delivered',
    'admin.order_status.cancelled': 'Cancelled',
    'admin.real_status.category_deleted': 'Category deleted',
    'admin.real_status.category_hidden': 'Category hidden',
    'admin.real_status.vendor_deleted': 'Vendor deleted',
    'admin.real_status.vendor_hidden': 'Vendor hidden',
    // admin — edit page
    'admin.edit.back': 'Back',
    'admin.edit.title': 'Edit {item}',
    'admin.edit.field_name': 'Name',
    'admin.edit.field_slug': 'Slug',
    'admin.edit.field_description': 'Description',
    'admin.edit.field_price': 'Price',
    'admin.edit.field_stock': 'Stock',
    'admin.edit.field_category': 'Category',
    'admin.edit.field_vendor': 'Vendor',
    'admin.edit.no_vendor': 'No vendor',
    'admin.edit.select_category': 'Select category…',
    'admin.edit.parent_category': 'Parent category',
    'admin.edit.no_parent': 'None (top-level)',
    'admin.edit.published_label': 'Published',
    'admin.edit.visible_storefront': 'Visible in the storefront',
    'admin.edit.hidden_storefront': 'Hidden from the storefront',
    'admin.edit.save_changes': 'Save changes',
    'admin.edit.saving': 'Saving…',
    'admin.edit.cancel': 'Cancel',
    'admin.edit.save_failed': 'Save failed',
    'admin.edit.toast_saved': 'Changes saved',
    'admin.edit.toast_published': 'Category published',
    'admin.edit.toast_unpublished': 'Category unpublished',
    'admin.edit.publish_failed': 'Publish failed',
    'admin.edit.unpublish_failed': 'Unpublish failed',
    // admin — order detail
    'admin.order.back': 'Back to orders',
    'admin.order.customer': 'Customer',
    'admin.order.shipping': 'Shipping',
    'admin.order.items': 'Items',
    'admin.order.update_status': 'Update Status',
    'admin.order.update': 'Update',
    'admin.order.saving': 'Saving…',
    'admin.order.status_updated': 'Order status updated to "{status}"',
    'admin.order.update_failed': 'Failed to update status',
    // admin — list page (orders & users)
    'admin.list.records': '{n} records',
    'admin.list.search_users': 'Search users…',
    'admin.list.col_order': 'Order',
    'admin.list.col_customer': 'Customer',
    'admin.list.col_status': 'Status',
    'admin.list.col_total': 'Total',
    'admin.list.col_name': 'Name',
    'admin.list.col_email': 'Email',
    'admin.list.col_roles': 'Roles',
    'admin.list.col_actions': 'Actions',
    'admin.list.loading': 'Loading…',
    'admin.list.manage': 'Manage',
    'admin.list.no_orders': 'No orders',
    'admin.list.no_users': 'No users',
    'admin.list.prev': 'Prev',
    'admin.list.next': 'Next',
    'admin.list.page_of': 'Page {page} of {total} ({count} records)',
    'admin.list.show_deleted': 'Show deleted',
    // admin — user detail
    'admin.user.back': 'Back to users',
    'admin.user.suspended': 'Suspended',
    'admin.user.roles': 'Roles',
    'admin.user.no_roles': 'No roles assigned',
    'admin.user.select_role': 'Select role…',
    'admin.user.assign': 'Assign',
    'admin.user.permissions': 'Permissions',
    'admin.user.no_permissions': 'No direct permissions',
    'admin.user.toast_assigned': 'Role "{role}" assigned',
    'admin.user.toast_removed': 'Role "{role}" removed',
    'admin.user.assign_failed': 'Failed to assign role',
    'admin.user.remove_failed': 'Failed to remove role',
    // admin — permissions page
    'admin.perms.title': 'Permissions',
    'admin.perms.summary': '{count} permissions across {domains} domains',
    'admin.perms.col_permission': 'Permission',
    // admin — roles page
    'admin.roles.title': 'Roles',
    'admin.roles.summary': '{count} roles — numeric hierarchy',
    'admin.roles.col_role': 'Role',
    'admin.roles.col_guard': 'Guard',
    'admin.roles.col_level': 'Level',
    'admin.roles.col_access': 'Access',
    'admin.roles.super_admin': 'Super Admin',
    'admin.roles.admin': 'Admin',
    'admin.roles.manager': 'Manager',
    'admin.roles.support': 'Support',
    // admin — placeholder page
    'admin.placeholder.roles_perms': 'Roles & Permissions',
    'admin.placeholder.translations': 'Translations',
    'admin.placeholder.roles': 'Roles',
    'admin.placeholder.level': 'Level {level}',
    'admin.placeholder.no_roles': 'No roles',
    'admin.placeholder.permissions': 'Permissions',
    'admin.placeholder.no_permissions': 'No permissions',
    'admin.placeholder.col_model': 'Model',
    'admin.placeholder.col_id': 'ID',
    'admin.placeholder.col_fields': 'Fields',
    'admin.placeholder.no_translations': 'No translations',
    // footer
    'footer.tagline': 'Thoughtfully designed essentials for everyday life.',
    'footer.quick_links': 'Quick Links',
    'footer.support': 'Support',
    'footer.shipping': 'Free shipping over $75',
    'footer.returns': '30-day returns',
    'footer.products': 'Products',
    'footer.search': 'Search',
    'footer.account': 'Account',
    'footer.copyright': 'Arvel. All rights reserved.',
    // flash sale
    'flash.limited_time': 'Limited Time',
    'flash.hrs': 'Hrs',
    'flash.min': 'Min',
    'flash.sec': 'Sec',
    // product card
    'product.out_of_stock': 'Out of Stock',
    // feature badges
    'badge.return_title': 'Easy to buy & return',
    'badge.return_subtitle': 'Single click returns & refunds',
    'badge.payment_title': 'Secure Payments',
    'badge.payment_subtitle': '100% protected transactions',
    'badge.support_title': '24/7 Support Available',
    'badge.support_subtitle': 'Dedicated support team',
    'badge.app_title': 'Shop with our App',
    'badge.app_subtitle': 'Get exclusive app-only offers',
  },
  ar: {
    // nav
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.specials': 'عروض خاصة',
    'nav.categories': 'الفئات',
    'nav.search': 'بحث',
    'nav.cart': 'عربة التسوق',
    'nav.account': 'الحساب',
    'nav.orders': 'طلباتي',
    'nav.admin': 'الإدارة',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.theme': 'تبديل السمة',
    'nav.admin_mode': 'وضع الإدارة',
    'nav.edit_product': 'تعديل هذا المنتج',
    'nav.manage_products': 'إدارة المنتجات',
    'nav.admin_panel': '← لوحة الإدارة',
    // search
    'search.placeholder': 'ابحث عن منتجات…',
    'search.results': 'نتائج البحث',
    // hero
    'hero.eyebrow': 'مجموعة جديدة',
    'hero.sale_title': 'صيف',
    'hero.sale_accent': 'خصم 10%',
    'hero.promo_hint': 'استخدم هذا الكود عند الدفع',
    'hero.price_from': 'من',
    'hero.top_rated': 'الأعلى تقييمًا',
    'hero.browse': 'تصفح الكل',
    'hero.discount': '20% خصم',
    'hero.title': 'أساسيات، بتصميم جديد.',
    'hero.subtitle': 'مواد فاخرة. تصميم خالد. شحن مجاني على الطلبات فوق $75.',
    'hero.cta': 'تسوق الآن',
    // home
    'home.shop_by_category': 'تسوق حسب الفئة',
    'home.new_arrivals': 'وصل حديثًا',
    'home.new_arrivals_sub': 'أحدث المنتجات',
    'home.categories': 'أبرز الفئات',
    'home.flash_sale': 'تخفيضات محدودة',
    'home.view_all': 'عرض الكل',
    'home.big_sale_eyebrow': 'وفّر على أبرز منتجات الإلكترونيات',
    'home.big_sale_title': 'احصل على',
    'home.big_sale_highlight': 'خصم 85%',
    'home.big_sale_suffix': 'في يوم التسوق الكبير',
    'flash.title': 'عرض اليوم',
    // promo banners
    'promo.shop_now': 'تسوق الآن',
    'promo.mobiles.eyebrow': 'خصم 15% على الكل',
    'promo.mobiles.title': 'الهواتف الذكية',
    'promo.mobiles.subtitle': 'استمتع بأحدث الموديلات',
    'promo.headsets.eyebrow': 'خصم 10% على الكل',
    'promo.headsets.title': 'سماعات ذكية',
    'promo.headsets.subtitle': 'استمتع بالحرية اللاسلكية',
    'promo.speakers.eyebrow': 'خصم 15% على الكل',
    'promo.speakers.title': 'سماعة محمولة',
    'promo.speakers.subtitle': 'موسيقاك معك أينما ذهبت',
    // products
    'products.all': 'جميع المنتجات',
    'products.category': 'الفئة',
    // product
    'product.add_to_cart': 'أضف إلى السلة',
    'product.adding': 'جارٍ الإضافة…',
    'product.quantity': 'الكمية',
    // cart
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلتك فارغة',
    'cart.continue': 'مواصلة التسوق',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.checkout': 'إتمام الشراء',
    // checkout
    'checkout.title': 'إتمام الطلب',
    'checkout.place_order': 'تأكيد الطلب',
    // account
    'account.title': 'طلباتي',
    // auth
    'auth.welcome': 'مرحبًا بك في أرفيل',
    'auth.admin_sign_in': 'تسجيل دخول المسؤول',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.full_name': 'الاسم الكامل',
    'auth.signing_in': 'جارٍ تسجيل الدخول…',
    'auth.creating_account': 'جارٍ إنشاء الحساب…',
    // shared order labels
    'order.product': 'المنتج',
    'order.price': 'السعر',
    'order.quantity': 'الكمية',
    'order.qty': 'الكمية',
    'order.subtotal': 'المجموع الفرعي',
    'order.shipping': 'الشحن',
    'order.taxes': 'الضرائب',
    'order.total': 'الإجمالي',
    'order.items': 'المنتجات',
    'order.free': 'مجاني',
    'order.summary': 'ملخص الطلب',
    'order.cod': 'الدفع عند الاستلام',
    'order.id': 'رقم الطلب',
    'order.date': 'التاريخ',
    'order.address': 'العنوان',
    'order.payment': 'طريقة الدفع',
    'order.delivery_date': 'تاريخ التسليم',
    'order.status': 'الحالة',
    'order.details': 'التفاصيل',
    // checkout steps + form
    'checkout.steps.shipping': 'الشحن',
    'checkout.steps.review': 'المراجعة',
    'checkout.steps.confirmation': 'التأكيد',
    'checkout.confirmed_title': 'تأكيد الطلب',
    'checkout.confirmed_sub': 'شكرًا على طلبك!',
    'checkout.full_name': 'الاسم الكامل',
    'checkout.full_name_placeholder': 'محمد أحمد',
    'checkout.street': 'عنوان الشارع',
    'checkout.street_placeholder': 'شارع الرئيسي 123',
    'checkout.city': 'المدينة',
    'checkout.city_placeholder': 'القاهرة',
    'checkout.country': 'الدولة',
    'checkout.country_placeholder': 'مصر',
    'checkout.cod_sub': 'ادفع عند وصول طلبك',
    'checkout.review_order': 'مراجعة الطلب',
    'checkout.back': 'رجوع',
    'checkout.back_to_shop': 'العودة للتسوق',
    'checkout.placing': 'جارٍ تأكيد الطلب…',
    'checkout.view_orders': 'عرض طلباتي',
    'checkout.failed': 'فشل إتمام الشراء. حاول مرة أخرى.',
    // account
    'account.order_placed': 'تم تقديم الطلب بنجاح!',
    'account.no_orders': 'لا توجد طلبات بعد',
    'account.col_order': 'الطلب',
    'account.col_date': 'التاريخ',
    'account.col_items': 'المنتجات',
    'account.col_payment': 'الدفع',
    'account.col_status': 'الحالة',
    'account.col_details': 'التفاصيل',
    'account.drawer_order': 'الطلب',
    // admin — sidebar
    'admin.sidebar.admin_panel': 'لوحة الإدارة',
    'admin.sidebar.collapse': 'طي القائمة',
    'admin.sidebar.dashboard': 'لوحة التحكم',
    'admin.sidebar.products': 'المنتجات',
    'admin.sidebar.categories': 'التصنيفات',
    'admin.sidebar.vendors': 'الموردون',
    'admin.sidebar.orders': 'الطلبات',
    'admin.sidebar.users': 'المستخدمون',
    'admin.sidebar.roles': 'الأدوار',
    'admin.sidebar.logout': 'تسجيل الخروج',
    // admin — dashboard
    'admin.dashboard.title': 'لوحة التحكم',
    'admin.dashboard.subtitle': 'نظرة عامة على أداء متجرك',
    'admin.stat.revenue': 'إجمالي الإيرادات',
    'admin.stat.orders': 'الطلبات',
    'admin.stat.customers': 'العملاء',
    'admin.stat.vs_last_month': 'مقارنة بالشهر الماضي',
    'admin.stat.avg_order': 'متوسط الطلب',
    'admin.dashboard.status_breakdown': 'حالات الطلبات',
    'admin.dashboard.greeting_morning': 'صباح الخير',
    'admin.dashboard.greeting_afternoon': 'مساء الخير',
    'admin.dashboard.greeting_evening': 'مساء النور',
    'admin.dashboard.all_orders': 'جميع الطلبات',
    'admin.chart.revenue_7d': 'إيرادات آخر 7 أيام',
    'admin.chart.last_7_days': 'آخر 7 أيام',
    'admin.chart.no_data': 'لا توجد طلبات في هذه الفترة',
    'admin.status.total': 'الإجمالي',
    'admin.recent_orders.title': 'الطلبات الأخيرة',
    'admin.recent_orders.view_all': 'عرض الكل',
    'admin.recent_orders.empty': 'لا توجد طلبات حديثة',
    'admin.best_sellers.title': 'الأكثر مبيعًا',
    'admin.best_sellers.items': '{n} عنصر',
    'admin.best_sellers.units': '{n} وحدة مباعة',
    'admin.best_sellers.empty': 'لا توجد بيانات مبيعات بعد',
    // admin — catalog list
    'admin.catalog.products': 'المنتجات',
    'admin.catalog.categories': 'التصنيفات',
    'admin.catalog.vendors': 'الموردون',
    'admin.catalog.product_singular': 'منتج',
    'admin.catalog.category_singular': 'تصنيف',
    'admin.catalog.vendor_singular': 'مورد',
    'admin.catalog.items_count': '{n} عناصر',
    'admin.catalog.refresh': 'تحديث الكتالوج',
    'admin.catalog.refreshing': 'جارٍ التحديث…',
    'admin.catalog.catalog_refreshed': 'تم تحديث الكتالوج — {count} منتج مُفهرس',
    'admin.catalog.add': 'إضافة {item}',
    'admin.catalog.col_name': 'الاسم',
    'admin.catalog.col_status': 'الحالة',
    'admin.catalog.col_visibility': 'الظهور',
    'admin.catalog.col_actions': 'الإجراءات',
    'admin.catalog.loading': 'جارٍ التحميل…',
    'admin.catalog.empty': 'لا توجد عناصر',
    'admin.catalog.action_edit': 'تعديل',
    'admin.catalog.action_publish': 'نشر',
    'admin.catalog.action_unpublish': 'إلغاء النشر',
    'admin.catalog.action_restore': 'استعادة',
    'admin.catalog.action_delete': 'حذف',
    'admin.catalog.delete_confirm': 'هل تريد حذف هذا العنصر؟',
    'admin.catalog.saving': 'جارٍ الحفظ…',
    'admin.catalog.save': 'حفظ',
    'admin.catalog.cancel': 'إلغاء',
    'admin.catalog.field_slug': 'الاختصار',
    'admin.catalog.field_description': 'الوصف',
    'admin.catalog.field_price': 'السعر',
    'admin.catalog.field_stock': 'المخزون',
    'admin.catalog.field_category': 'الفئة',
    'admin.catalog.field_vendor': 'المورد',
    'admin.catalog.no_vendor': 'بدون مورد',
    'admin.catalog.select_category': 'اختر فئة…',
    'admin.catalog.prev': 'السابق',
    'admin.catalog.next': 'التالي',
    'admin.catalog.page_of': 'الصفحة {page} من {total} ({count} عنصر)',
    'admin.catalog.form_create': 'إنشاء {item}',
    'admin.catalog.form_edit': 'تعديل {item}',
    'admin.catalog.toast_created': 'تم إنشاء {item}',
    'admin.catalog.toast_saved': 'تم حفظ التغييرات',
    'admin.catalog.toast_deleted': 'تم حذف {item}',
    'admin.catalog.toast_published': 'تم نشر {item}',
    'admin.catalog.toast_unpublished': 'تم إلغاء نشر {item}',
    'admin.catalog.toast_restored': 'تم استعادة {item}',
    'admin.catalog.op_failed': 'فشلت العملية',
    'admin.catalog.show_trashed': 'عرض المحذوفات',
    // admin — real_status labels
    'admin.real_status.visible': 'مرئي',
    'admin.real_status.draft': 'مسودة',
    'admin.real_status.not_scheduled': 'غير مجدول',
    'admin.real_status.scheduled': 'مجدول',
    'admin.status.published': 'منشور',
    'admin.status.draft': 'مسودة',
    // order status labels
    'admin.order_status.pending': 'قيد الانتظار',
    'admin.order_status.confirmed': 'مؤكد',
    'admin.order_status.processing': 'جارٍ المعالجة',
    'admin.order_status.shipped': 'تم الشحن',
    'admin.order_status.delivered': 'تم التوصيل',
    'admin.order_status.cancelled': 'ملغى',
    'admin.real_status.category_deleted': 'الفئة محذوفة',
    'admin.real_status.category_hidden': 'الفئة مخفية',
    'admin.real_status.vendor_deleted': 'المورد محذوف',
    'admin.real_status.vendor_hidden': 'المورد مخفي',
    // admin — edit page
    'admin.edit.back': 'رجوع',
    'admin.edit.title': 'تعديل {item}',
    'admin.edit.field_name': 'الاسم',
    'admin.edit.field_slug': 'الاختصار',
    'admin.edit.field_description': 'الوصف',
    'admin.edit.field_price': 'السعر',
    'admin.edit.field_stock': 'المخزون',
    'admin.edit.field_category': 'الفئة',
    'admin.edit.field_vendor': 'المورد',
    'admin.edit.no_vendor': 'بدون مورد',
    'admin.edit.select_category': 'اختر فئة…',
    'admin.edit.parent_category': 'الفئة الأم',
    'admin.edit.no_parent': 'لا شيء (مستوى أعلى)',
    'admin.edit.published_label': 'منشور',
    'admin.edit.visible_storefront': 'مرئي في المتجر',
    'admin.edit.hidden_storefront': 'مخفي من المتجر',
    'admin.edit.save_changes': 'حفظ التغييرات',
    'admin.edit.saving': 'جارٍ الحفظ…',
    'admin.edit.cancel': 'إلغاء',
    'admin.edit.save_failed': 'فشل الحفظ',
    'admin.edit.toast_saved': 'تم حفظ التغييرات',
    'admin.edit.toast_published': 'تم نشر الفئة',
    'admin.edit.toast_unpublished': 'تم إلغاء نشر الفئة',
    'admin.edit.publish_failed': 'فشل النشر',
    'admin.edit.unpublish_failed': 'فشل إلغاء النشر',
    // admin — order detail
    'admin.order.back': 'العودة إلى الطلبات',
    'admin.order.customer': 'العميل',
    'admin.order.shipping': 'الشحن',
    'admin.order.items': 'المنتجات',
    'admin.order.update_status': 'تحديث الحالة',
    'admin.order.update': 'تحديث',
    'admin.order.saving': 'جارٍ الحفظ…',
    'admin.order.status_updated': 'تم تحديث حالة الطلب إلى "{status}"',
    'admin.order.update_failed': 'فشل تحديث الحالة',
    // admin — list page
    'admin.list.records': '{n} سجل',
    'admin.list.search_users': 'البحث عن مستخدمين…',
    'admin.list.col_order': 'الطلب',
    'admin.list.col_customer': 'العميل',
    'admin.list.col_status': 'الحالة',
    'admin.list.col_total': 'الإجمالي',
    'admin.list.col_name': 'الاسم',
    'admin.list.col_email': 'البريد الإلكتروني',
    'admin.list.col_roles': 'الأدوار',
    'admin.list.col_actions': 'الإجراءات',
    'admin.list.loading': 'جارٍ التحميل…',
    'admin.list.manage': 'إدارة',
    'admin.list.no_orders': 'لا توجد طلبات',
    'admin.list.no_users': 'لا يوجد مستخدمون',
    'admin.list.prev': 'السابق',
    'admin.list.next': 'التالي',
    'admin.list.page_of': 'الصفحة {page} من {total} ({count} سجل)',
    'admin.list.show_deleted': 'عرض المحذوفين',
    // admin — user detail
    'admin.user.back': 'العودة إلى المستخدمين',
    'admin.user.suspended': 'موقوف',
    'admin.user.roles': 'الأدوار',
    'admin.user.no_roles': 'لا توجد أدوار مخصصة',
    'admin.user.select_role': 'اختر دورًا…',
    'admin.user.assign': 'تعيين',
    'admin.user.permissions': 'الصلاحيات',
    'admin.user.no_permissions': 'لا توجد صلاحيات مباشرة',
    'admin.user.toast_assigned': 'تم تعيين الدور "{role}"',
    'admin.user.toast_removed': 'تم إزالة الدور "{role}"',
    'admin.user.assign_failed': 'فشل تعيين الدور',
    'admin.user.remove_failed': 'فشل إزالة الدور',
    // admin — permissions page
    'admin.perms.title': 'الصلاحيات',
    'admin.perms.summary': '{count} صلاحية عبر {domains} نطاق',
    'admin.perms.col_permission': 'الصلاحية',
    // admin — roles page
    'admin.roles.title': 'الأدوار',
    'admin.roles.summary': '{count} أدوار — تسلسل هرمي رقمي',
    'admin.roles.col_role': 'الدور',
    'admin.roles.col_guard': 'الحارس',
    'admin.roles.col_level': 'المستوى',
    'admin.roles.col_access': 'الوصول',
    'admin.roles.super_admin': 'مدير عام',
    'admin.roles.admin': 'مدير',
    'admin.roles.manager': 'مشرف',
    'admin.roles.support': 'دعم',
    // admin — placeholder page
    'admin.placeholder.roles_perms': 'الأدوار والصلاحيات',
    'admin.placeholder.translations': 'الترجمات',
    'admin.placeholder.roles': 'الأدوار',
    'admin.placeholder.level': 'المستوى {level}',
    'admin.placeholder.no_roles': 'لا توجد أدوار',
    'admin.placeholder.permissions': 'الصلاحيات',
    'admin.placeholder.no_permissions': 'لا توجد صلاحيات',
    'admin.placeholder.col_model': 'النموذج',
    'admin.placeholder.col_id': 'المعرف',
    'admin.placeholder.col_fields': 'الحقول',
    'admin.placeholder.no_translations': 'لا توجد ترجمات',
    // footer
    'footer.tagline': 'أساسيات مصممة بعناية للحياة اليومية.',
    'footer.quick_links': 'روابط سريعة',
    'footer.support': 'الدعم',
    'footer.shipping': 'شحن مجاني فوق $75',
    'footer.returns': 'إرجاع خلال 30 يومًا',
    'footer.products': 'المنتجات',
    'footer.search': 'بحث',
    'footer.account': 'الحساب',
    'footer.copyright': 'أرفيل. جميع الحقوق محفوظة.',
    // flash sale
    'flash.limited_time': 'وقت محدود',
    'flash.hrs': 'ساعة',
    'flash.min': 'دقيقة',
    'flash.sec': 'ثانية',
    // product card
    'product.out_of_stock': 'نفد من المخزون',
    // feature badges
    'badge.return_title': 'شراء وإرجاع سهل',
    'badge.return_subtitle': 'إرجاع ومبالغ مستردة بنقرة واحدة',
    'badge.payment_title': 'مدفوعات آمنة',
    'badge.payment_subtitle': 'معاملات محمية بنسبة 100%',
    'badge.support_title': 'دعم متاح على مدار الساعة',
    'badge.support_subtitle': 'فريق دعم متخصص',
    'badge.app_title': 'تسوق مع تطبيقنا',
    'badge.app_subtitle': 'احصل على عروض حصرية للتطبيق',
  },
  tr: {
    // nav
    'nav.home': 'Ana Sayfa',
    'nav.products': 'Ürünler',
    'nav.specials': 'Fırsatlar',
    'nav.categories': 'Kategoriler',
    'nav.search': 'Ara',
    'nav.cart': 'Sepet',
    'nav.account': 'Hesap',
    'nav.orders': 'Siparişlerim',
    'nav.admin': 'Yönetim',
    'nav.login': 'Giriş yap',
    'nav.logout': 'Çıkış yap',
    'nav.theme': 'Temayı değiştir',
    'nav.admin_mode': 'Yönetici modu',
    'nav.edit_product': 'Bu ürünü düzenle',
    'nav.manage_products': 'Ürünleri yönet',
    'nav.admin_panel': 'Yönetici paneli →',
    // search
    'search.placeholder': 'Ürün ara…',
    'search.results': 'Arama Sonuçları',
    // hero
    'hero.eyebrow': 'Yeni Koleksiyon',
    'hero.sale_title': 'YAZ',
    'hero.sale_accent': '%10 İNDİRİM',
    'hero.promo_hint': 'Bu kodu ödeme sırasında kullanın',
    'hero.price_from': 'Başlayan',
    'hero.top_rated': 'En Yüksek Puan',
    'hero.browse': 'Tümüne Göz At',
    'hero.discount': '-%20 İNDİRİM',
    'hero.title': 'Temel ürünler, yeniden hayal edildi.',
    'hero.subtitle': 'Premium malzemeler. Zamansız tasarım. $75 üzeri ücretsiz kargo.',
    'hero.cta': 'Şimdi Alışveriş Yap',
    // home
    'home.shop_by_category': 'Kategoriye Göre Alışveriş',
    'home.new_arrivals': 'Yeni Gelenler',
    'home.new_arrivals_sub': 'Taze seçimler, yeni geldi',
    'home.categories': 'Öne Çıkan Kategoriler',
    'home.flash_sale': 'Flaş Satış',
    'home.view_all': 'Tümünü gör',
    'home.big_sale_eyebrow': 'En Çok Satan Elektronikte Büyük Tasarruf',
    'home.big_sale_title': 'Büyük Alışveriş Gününde',
    'home.big_sale_highlight': '%85 İNDİRİM',
    'home.big_sale_suffix': 'Kazan',
    'flash.title': 'Günün Fırsatı',
    // promo banners
    'promo.shop_now': 'Şimdi Al',
    'promo.mobiles.eyebrow': 'Düz %15 İndirim',
    'promo.mobiles.title': 'Akıllı Telefonlar',
    'promo.mobiles.subtitle': 'En son modelleri keşfedin',
    'promo.headsets.eyebrow': 'Düz %10 İndirim',
    'promo.headsets.title': 'Akıllı Kulaklık',
    'promo.headsets.subtitle': 'Kablosuz özgürlüğün tadını çıkarın',
    'promo.speakers.eyebrow': 'Düz %15 İndirim',
    'promo.speakers.title': 'Taşınabilir Hoparlör',
    'promo.speakers.subtitle': 'Müziğinizi her yere götürün',
    // products
    'products.all': 'Tüm Ürünler',
    'products.category': 'Kategori',
    // product
    'product.add_to_cart': 'Sepete Ekle',
    'product.adding': 'Ekleniyor…',
    'product.quantity': 'Adet',
    // cart
    'cart.title': 'Sepetiniz',
    'cart.empty': 'Sepetiniz boş',
    'cart.continue': 'Alışverişe devam et',
    'cart.subtotal': 'Ara toplam',
    'cart.checkout': 'Ödemeye geç',
    // checkout
    'checkout.title': 'Ödeme',
    'checkout.place_order': 'Siparişi ver',
    // account
    'account.title': 'Siparişlerim',
    // auth
    'auth.welcome': "Arvel'e Hoş Geldiniz",
    'auth.admin_sign_in': 'Yönetici Girişi',
    'auth.login': 'Giriş yap',
    'auth.register': 'Kayıt ol',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.full_name': 'Ad Soyad',
    'auth.signing_in': 'Giriş yapılıyor…',
    'auth.creating_account': 'Hesap oluşturuluyor…',
    // shared order labels
    'order.product': 'Ürün',
    'order.price': 'Fiyat',
    'order.quantity': 'Adet',
    'order.qty': 'Adet',
    'order.subtotal': 'Ara toplam',
    'order.shipping': 'Kargo',
    'order.taxes': 'Vergiler',
    'order.total': 'Toplam',
    'order.items': 'Ürünler',
    'order.free': 'Ücretsiz',
    'order.summary': 'Sipariş Özeti',
    'order.cod': 'Kapıda Ödeme',
    'order.id': 'Sipariş No',
    'order.date': 'Tarih',
    'order.address': 'Adres',
    'order.payment': 'Ödeme',
    'order.delivery_date': 'Teslim Tarihi',
    'order.status': 'Durum',
    'order.details': 'Detaylar',
    // checkout steps + form
    'checkout.steps.shipping': 'Kargo',
    'checkout.steps.review': 'İnceleme',
    'checkout.steps.confirmation': 'Onay',
    'checkout.confirmed_title': 'Sipariş Onayı',
    'checkout.confirmed_sub': 'Siparişiniz için teşekkürler!',
    'checkout.full_name': 'Ad Soyad',
    'checkout.full_name_placeholder': 'Ahmet Yılmaz',
    'checkout.street': 'Sokak adresi',
    'checkout.street_placeholder': 'Atatürk Cad. 123',
    'checkout.city': 'Şehir',
    'checkout.city_placeholder': 'İstanbul',
    'checkout.country': 'Ülke',
    'checkout.country_placeholder': 'Türkiye',
    'checkout.cod_sub': 'Siparişiniz geldiğinde ödeyin',
    'checkout.review_order': 'Siparişi İncele',
    'checkout.back': 'Geri',
    'checkout.back_to_shop': 'Alışverişe Dön',
    'checkout.placing': 'Sipariş veriliyor…',
    'checkout.view_orders': 'Siparişlerimi Gör',
    'checkout.failed': 'Ödeme başarısız. Lütfen tekrar deneyin.',
    // account
    'account.order_placed': 'Sipariş başarıyla verildi!',
    'account.no_orders': 'Henüz sipariş yok',
    'account.col_order': 'Sipariş',
    'account.col_date': 'Tarih',
    'account.col_items': 'Ürünler',
    'account.col_payment': 'Ödeme',
    'account.col_status': 'Durum',
    'account.col_details': 'Detaylar',
    'account.drawer_order': 'Sipariş',
    // admin — sidebar
    'admin.sidebar.admin_panel': 'Yönetim Paneli',
    'admin.sidebar.collapse': 'Küçült',
    'admin.sidebar.dashboard': 'Panel',
    'admin.sidebar.products': 'Ürünler',
    'admin.sidebar.categories': 'Kategoriler',
    'admin.sidebar.vendors': 'Tedarikçiler',
    'admin.sidebar.orders': 'Siparişler',
    'admin.sidebar.users': 'Kullanıcılar',
    'admin.sidebar.roles': 'Roller',
    'admin.sidebar.logout': 'Çıkış yap',
    // admin — dashboard
    'admin.dashboard.title': 'Panel',
    'admin.dashboard.subtitle': 'Mağazanızın performansına genel bakış',
    'admin.stat.revenue': 'Toplam Gelir',
    'admin.stat.orders': 'Siparişler',
    'admin.stat.customers': 'Müşteriler',
    'admin.stat.vs_last_month': 'geçen aya kıyasla',
    'admin.stat.avg_order': 'Ort. Sipariş',
    'admin.dashboard.status_breakdown': 'Sipariş Durumları',
    'admin.dashboard.greeting_morning': 'Günaydın',
    'admin.dashboard.greeting_afternoon': 'İyi öğleden sonralar',
    'admin.dashboard.greeting_evening': 'İyi akşamlar',
    'admin.dashboard.all_orders': 'Tüm Siparişler',
    'admin.chart.revenue_7d': '7 Günlük Gelir',
    'admin.chart.last_7_days': 'Son 7 gün',
    'admin.chart.no_data': 'Bu dönemde sipariş yok',
    'admin.status.total': 'Toplam',
    'admin.recent_orders.title': 'Son Siparişler',
    'admin.recent_orders.view_all': 'Tümünü gör',
    'admin.recent_orders.empty': 'Son sipariş yok',
    'admin.best_sellers.title': 'En Çok Satanlar',
    'admin.best_sellers.items': '{n} öğe',
    'admin.best_sellers.units': '{n} adet satıldı',
    'admin.best_sellers.empty': 'Henüz satış verisi yok',
    // admin — catalog list
    'admin.catalog.products': 'Ürünler',
    'admin.catalog.categories': 'Kategoriler',
    'admin.catalog.vendors': 'Tedarikçiler',
    'admin.catalog.product_singular': 'Ürün',
    'admin.catalog.category_singular': 'Kategori',
    'admin.catalog.vendor_singular': 'Tedarikçi',
    'admin.catalog.items_count': '{n} öğe',
    'admin.catalog.refresh': 'Kataloğu Yenile',
    'admin.catalog.refreshing': 'Yenileniyor…',
    'admin.catalog.catalog_refreshed': 'Katalog yenilendi — {count} ürün dizinlendi',
    'admin.catalog.add': '{item} Ekle',
    'admin.catalog.col_name': 'Ad',
    'admin.catalog.col_status': 'Durum',
    'admin.catalog.col_visibility': 'Görünürlük',
    'admin.catalog.col_actions': 'İşlemler',
    'admin.catalog.loading': 'Yükleniyor…',
    'admin.catalog.empty': 'Öğe yok',
    'admin.catalog.action_edit': 'Düzenle',
    'admin.catalog.action_publish': 'Yayınla',
    'admin.catalog.action_unpublish': 'Yayından Kaldır',
    'admin.catalog.action_restore': 'Geri Yükle',
    'admin.catalog.action_delete': 'Sil',
    'admin.catalog.delete_confirm': 'Bu öğeyi silmek istiyor musunuz?',
    'admin.catalog.saving': 'Kaydediliyor…',
    'admin.catalog.save': 'Kaydet',
    'admin.catalog.cancel': 'İptal',
    'admin.catalog.field_slug': 'Kısa Ad',
    'admin.catalog.field_description': 'Açıklama',
    'admin.catalog.field_price': 'Fiyat',
    'admin.catalog.field_stock': 'Stok',
    'admin.catalog.field_category': 'Kategori',
    'admin.catalog.field_vendor': 'Tedarikçi',
    'admin.catalog.no_vendor': 'Tedarikçi yok',
    'admin.catalog.select_category': 'Kategori seç…',
    'admin.catalog.prev': 'Önceki',
    'admin.catalog.next': 'Sonraki',
    'admin.catalog.page_of': 'Sayfa {page}/{total} ({count} öğe)',
    'admin.catalog.form_create': '{item} Oluştur',
    'admin.catalog.form_edit': '{item} Düzenle',
    'admin.catalog.toast_created': '{item} oluşturuldu',
    'admin.catalog.toast_saved': 'Değişiklikler kaydedildi',
    'admin.catalog.toast_deleted': '{item} silindi',
    'admin.catalog.toast_published': '{item} yayınlandı',
    'admin.catalog.toast_unpublished': '{item} yayından kaldırıldı',
    'admin.catalog.toast_restored': '{item} geri yüklendi',
    'admin.catalog.op_failed': 'İşlem başarısız',
    'admin.catalog.show_trashed': 'Silinenleri Göster',
    // admin — real_status labels
    'admin.real_status.visible': 'Görünür',
    'admin.real_status.draft': 'Taslak',
    'admin.real_status.not_scheduled': 'Zamanlanmamış',
    'admin.real_status.scheduled': 'Zamanlanmış',
    'admin.status.published': 'Yayında',
    'admin.status.draft': 'Taslak',
    // order status labels
    'admin.order_status.pending': 'Bekliyor',
    'admin.order_status.confirmed': 'Onaylandı',
    'admin.order_status.processing': 'İşleniyor',
    'admin.order_status.shipped': 'Kargoda',
    'admin.order_status.delivered': 'Teslim Edildi',
    'admin.order_status.cancelled': 'İptal Edildi',
    'admin.real_status.category_deleted': 'Kategori silindi',
    'admin.real_status.category_hidden': 'Kategori gizlendi',
    'admin.real_status.vendor_deleted': 'Tedarikçi silindi',
    'admin.real_status.vendor_hidden': 'Tedarikçi gizlendi',
    // admin — edit page
    'admin.edit.back': 'Geri',
    'admin.edit.title': '{item} Düzenle',
    'admin.edit.field_name': 'Ad',
    'admin.edit.field_slug': 'Kısa Ad',
    'admin.edit.field_description': 'Açıklama',
    'admin.edit.field_price': 'Fiyat',
    'admin.edit.field_stock': 'Stok',
    'admin.edit.field_category': 'Kategori',
    'admin.edit.field_vendor': 'Tedarikçi',
    'admin.edit.no_vendor': 'Tedarikçi yok',
    'admin.edit.select_category': 'Kategori seç…',
    'admin.edit.parent_category': 'Üst kategori',
    'admin.edit.no_parent': 'Yok (üst düzey)',
    'admin.edit.published_label': 'Yayında',
    'admin.edit.visible_storefront': 'Mağazada görünür',
    'admin.edit.hidden_storefront': 'Mağazada gizli',
    'admin.edit.save_changes': 'Değişiklikleri Kaydet',
    'admin.edit.saving': 'Kaydediliyor…',
    'admin.edit.cancel': 'İptal',
    'admin.edit.save_failed': 'Kaydetme başarısız',
    'admin.edit.toast_saved': 'Değişiklikler kaydedildi',
    'admin.edit.toast_published': 'Kategori yayınlandı',
    'admin.edit.toast_unpublished': 'Kategori yayından kaldırıldı',
    'admin.edit.publish_failed': 'Yayınlama başarısız',
    'admin.edit.unpublish_failed': 'Yayından kaldırma başarısız',
    // admin — order detail
    'admin.order.back': 'Siparişlere dön',
    'admin.order.customer': 'Müşteri',
    'admin.order.shipping': 'Kargo',
    'admin.order.items': 'Ürünler',
    'admin.order.update_status': 'Durumu Güncelle',
    'admin.order.update': 'Güncelle',
    'admin.order.saving': 'Kaydediliyor…',
    'admin.order.status_updated': 'Sipariş durumu "{status}" olarak güncellendi',
    'admin.order.update_failed': 'Durum güncellenemedi',
    // admin — list page
    'admin.list.records': '{n} kayıt',
    'admin.list.search_users': 'Kullanıcı ara…',
    'admin.list.col_order': 'Sipariş',
    'admin.list.col_customer': 'Müşteri',
    'admin.list.col_status': 'Durum',
    'admin.list.col_total': 'Toplam',
    'admin.list.col_name': 'Ad',
    'admin.list.col_email': 'E-posta',
    'admin.list.col_roles': 'Roller',
    'admin.list.col_actions': 'İşlemler',
    'admin.list.loading': 'Yükleniyor…',
    'admin.list.manage': 'Yönet',
    'admin.list.no_orders': 'Sipariş yok',
    'admin.list.no_users': 'Kullanıcı yok',
    'admin.list.prev': 'Önceki',
    'admin.list.next': 'Sonraki',
    'admin.list.page_of': 'Sayfa {page}/{total} ({count} kayıt)',
    'admin.list.show_deleted': 'Silinenleri Göster',
    // admin — user detail
    'admin.user.back': 'Kullanıcılara dön',
    'admin.user.suspended': 'Askıya alındı',
    'admin.user.roles': 'Roller',
    'admin.user.no_roles': 'Atanmış rol yok',
    'admin.user.select_role': 'Rol seç…',
    'admin.user.assign': 'Ata',
    'admin.user.permissions': 'İzinler',
    'admin.user.no_permissions': 'Doğrudan izin yok',
    'admin.user.toast_assigned': '"{role}" rolü atandı',
    'admin.user.toast_removed': '"{role}" rolü kaldırıldı',
    'admin.user.assign_failed': 'Rol atanamadı',
    'admin.user.remove_failed': 'Rol kaldırılamadı',
    // admin — permissions page
    'admin.perms.title': 'İzinler',
    'admin.perms.summary': '{domains} alanda {count} izin',
    'admin.perms.col_permission': 'İzin',
    // admin — roles page
    'admin.roles.title': 'Roller',
    'admin.roles.summary': '{count} rol — sayısal hiyerarşi',
    'admin.roles.col_role': 'Rol',
    'admin.roles.col_guard': 'Guard',
    'admin.roles.col_level': 'Seviye',
    'admin.roles.col_access': 'Erişim',
    'admin.roles.super_admin': 'Süper Yönetici',
    'admin.roles.admin': 'Yönetici',
    'admin.roles.manager': 'Müdür',
    'admin.roles.support': 'Destek',
    // admin — placeholder page
    'admin.placeholder.roles_perms': 'Roller ve İzinler',
    'admin.placeholder.translations': 'Çeviriler',
    'admin.placeholder.roles': 'Roller',
    'admin.placeholder.level': 'Seviye {level}',
    'admin.placeholder.no_roles': 'Rol yok',
    'admin.placeholder.permissions': 'İzinler',
    'admin.placeholder.no_permissions': 'İzin yok',
    'admin.placeholder.col_model': 'Model',
    'admin.placeholder.col_id': 'Kimlik',
    'admin.placeholder.col_fields': 'Alanlar',
    'admin.placeholder.no_translations': 'Çeviri yok',
    // footer
    'footer.tagline': 'Günlük yaşam için özenle tasarlanmış temel ürünler.',
    'footer.quick_links': 'Hızlı Bağlantılar',
    'footer.support': 'Destek',
    'footer.shipping': '$75 üzeri ücretsiz kargo',
    'footer.returns': '30 gün iade',
    'footer.products': 'Ürünler',
    'footer.search': 'Ara',
    'footer.account': 'Hesap',
    'footer.copyright': 'Arvel. Tüm hakları saklıdır.',
    // flash sale
    'flash.limited_time': 'Sınırlı Süre',
    'flash.hrs': 'Saat',
    'flash.min': 'Dak',
    'flash.sec': 'Sn',
    // product card
    'product.out_of_stock': 'Stokta Yok',
    // feature badges
    'badge.return_title': 'Kolay alış & iade',
    'badge.return_subtitle': 'Tek tıkla iade ve geri ödeme',
    'badge.payment_title': 'Güvenli Ödemeler',
    'badge.payment_subtitle': '%100 korumalı işlemler',
    'badge.support_title': '7/24 Destek Mevcut',
    'badge.support_subtitle': 'Özel destek ekibi',
    'badge.app_title': 'Uygulamamızla Alışveriş',
    'badge.app_subtitle': 'Özel uygulama tekliflerini alın',
  },
}

async function bootstrap(): Promise<void> {
  const locale = getStoredLocale()
  applyDocumentLocale(locale)
  const backendMessages = await loadMessages(locale)

  // Static fallbacks first, then backend keys override them.
  const messages = { ...UI_FALLBACKS[locale], ...backendMessages }

  const i18n = createI18n({
    legacy: false,
    locale,
    fallbackLocale: 'en',
    messages: { [locale]: messages },
  })

  const app = createApp(App)
  const pinia = createPinia()
  // staleTime:0 — every component mount triggers a background refetch so the
  // admin UI never shows stale data after a mutation or a navigation.
  const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 0 } } })

  app.use(pinia)
  app.use(router)
  app.use(i18n)
  app.use(VueQueryPlugin, { queryClient })

  const { useAuthStore } = await import('./stores/auth')
  const { useToastStore } = await import('./stores/toast')
  const auth = useAuthStore()
  const toast = useToastStore()

  setUnauthorizedHandler(() => {
    // Only act if the user was actually logged in — avoids redirecting on
    // intentionally unauthenticated requests (e.g. public storefront endpoints).
    if (!auth.isAuthenticated) return
    auth.logout()
    toast.error('Your session has expired. Please log in again.')
    void router.push({ name: 'login' })
  })

  await auth.hydrate()
  if (auth.isAuthenticated) {
    const { useCartStore } = await import('./stores/cart')
    await useCartStore().load()
  }

  for (const loc of SUPPORTED_LOCALES) {
    if (loc !== locale) {
      void loadMessages(loc).then((backendMsgs) => {
        i18n.global.setLocaleMessage(loc, { ...UI_FALLBACKS[loc], ...backendMsgs })
      })
    }
  }

  app.mount('#app')
}

void bootstrap()
