"""Generate the type stub for arvel's facades (knowledge/port/06-facades.md §42-50).

Facades proxy attribute access to a container-resolved root via ``FacadeMeta.__getattr__``,
which is opaque to mypy/pyright. This script boots an app, resolves each facade's backing
object, introspects its public methods, and emits ``src/arvel/support/facades/__init__.pyi``
so type-checkers see real method names + arity on ``Cache.get(...)``, ``Route.post(...)``, etc.
Signatures use ``Any`` params/returns (preserving names + arity) to stay strict-gate-safe
without importing every backing type. Regenerate with ``make stubs``; the stub never drifts
because it is derived from the live classes.

A facade whose root can't be resolved (e.g. a binding needing config/extras unavailable at
generation time) gets a permissive ``def __getattr__(cls, name: str) -> Any: ...`` fallback
instead of explicit method stubs.
"""

from __future__ import annotations

import asyncio
import inspect
from pathlib import Path
from typing import Any

from cryptography.fernet import Fernet

import arvel.support.facades as facades_mod
from arvel.kernel.application import Application
from arvel.kernel.discovery import bootstrap_providers, clear_cache
from arvel.support.facades import Facade

STUB_PATH = Path(__file__).resolve().parent.parent / "src/arvel/support/facades/__init__.pyi"

# A valid (ephemeral) Fernet app.key so the Crypt facade's encrypter resolves during
# introspection. The value is irrelevant to the output (we read method *names*, not data),
# so a fresh key each run still yields a deterministic stub.
_DUMMY_KEY = Fernet.generate_key().decode()


def _boot() -> Application:
    clear_cache()
    app = Application.configure().with_config({"app": {"key": _DUMMY_KEY}}).create()
    bootstrap_providers(app)
    asyncio.run(app.boot())
    return app


def _facade_classes() -> list[type[Facade]]:
    out: list[type[Facade]] = []
    for name in dir(facades_mod):
        obj = getattr(facades_mod, name)
        if isinstance(obj, type) and issubclass(obj, Facade) and obj is not Facade:
            out.append(obj)
    return sorted(out, key=lambda c: c.__name__)


def _method_stub(name: str, member: Any) -> str | None:
    """Render one ``@classmethod`` stub line for a public callable, or ``None`` to skip."""
    try:
        sig = inspect.signature(member)
    except ValueError, TypeError:
        return f"    @classmethod\n    def {name}(cls, *args: Any, **kwargs: Any) -> Any: ..."
    params: list[str] = ["cls"]
    star_emitted = False
    for pname, p in sig.parameters.items():
        if pname in ("self", "cls"):
            continue
        if p.kind is p.VAR_POSITIONAL:
            params.append(f"*{pname}: Any")
            star_emitted = True
        elif p.kind is p.KEYWORD_ONLY:
            if not star_emitted:
                params.append("*")
                star_emitted = True
            params.append(f"{pname}: Any = ..." if p.default is not p.empty else f"{pname}: Any")
        elif p.kind is p.VAR_KEYWORD:
            params.append(f"**{pname}: Any")
        else:
            params.append(f"{pname}: Any = ..." if p.default is not p.empty else f"{pname}: Any")
    return f"    @classmethod\n    def {name}({', '.join(params)}) -> Any: ..."


def _members(backing: type) -> tuple[list[str], list[str]]:
    """Return (method_stub_lines, attribute_lines) for a backing class's public surface."""
    methods: list[str] = []
    attrs: list[str] = []
    for name in sorted(dir(backing)):
        if name.startswith("_"):
            continue
        try:
            member = inspect.getattr_static(backing, name)
        except AttributeError:
            continue
        if isinstance(member, property):
            attrs.append(f"    {name}: Any")
            continue
        resolved = getattr(backing, name, None)
        if callable(resolved):
            line = _method_stub(name, resolved)
            if line is not None:
                methods.append(line)
        else:
            attrs.append(f"    {name}: Any")
    return methods, attrs


def _render(app: Application) -> str:
    lines: list[str] = [
        "# Generated by tools/gen_facade_stubs.py (make stubs) — do not edit by hand.",
        "# Gives type-checkers facade method names + arity (FacadeMeta.__getattr__ is opaque).",
        "from typing import Any",
        "",
        "# __getattr__ mirrors the runtime metaclass: any attribute not explicitly stubbed below",
        "# (e.g. manager-proxied methods like Cache.get) falls back to Any instead of erroring.",
        "class FacadeMeta(type):",
        "    def __getattr__(cls, name: str) -> Any: ...",
        "",
        "class Facade(metaclass=FacadeMeta):",
        "    @classmethod",
        "    def accessor(cls) -> str: ...",
        "    @classmethod",
        "    def swap(cls, instance: Any) -> Any: ...",
        "    @classmethod",
        "    def fake(cls) -> Any: ...",
        "    @classmethod",
        "    def fake_class(cls) -> type: ...",
        "    @classmethod",
        "    def clear_swapped(cls) -> None: ...",
        "",
        "def set_application(app: Any) -> None: ...",
        "",
    ]
    for facade in _facade_classes():
        acc = facade.accessor()
        try:
            root = app.make(acc)
            backing = root if isinstance(root, type) else type(root)
            methods, attrs = _members(backing)
            body = [*attrs, *methods]
        except Exception:  # unresolved root (e.g. translator unbound) -> permissive fallback
            body = []
        lines.append(f"class {facade.__name__}(Facade):")
        # Unresolved/empty → inherits FacadeMeta.__getattr__ (Any) — no explicit body needed.
        lines.extend(body if body else ["    ..."])
        lines.append("")
    # Emit exactly one trailing newline (no trailing blank line) so the pre-commit
    # end-of-file-fixer leaves the generated stub untouched and the equality test stays stable.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def main() -> None:
    app = _boot()
    STUB_PATH.write_text(_render(app))
    print(f"wrote {STUB_PATH.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
