"""View / template rendering configuration for the e-commerce demo.

``paths`` lists the directories Jinja2 searches when ``render_template``
is called (mailables today, ad-hoc views as needed). Paths are relative
to the project root (``backend/``); the renderer resolves them to
absolute paths at first render.

The ``resources/views`` convention matches ``arvel make:view`` so any
template generated by the framework's scaffolder lands in the same
search root.
"""

from __future__ import annotations

paths: list[str] = ["resources/views"]
